(* This file is generated by ortac qcheck-stm,
   edit how you run the tool instead *)
[@@@ocaml.warning "-26-27-69-32-34-38"]
open Demo_wrapped
module Ortac_runtime = Ortac_runtime_qcheck_stm
module SUT =
  (Ortac_runtime.SUT.Make)(struct
                             type sut = char t
                             let init () = make 100 'a'
                           end)
module ModelElt =
  struct
    type nonrec elt = {
      size: int ;
      contents: char list }
    let init =
      let i = 100
      and a_1 = 'a' in
      {
        size =
          (try i
           with
           | e ->
               raise
                 (Ortac_runtime.Partial_function
                    (e,
                      {
                        Ortac_runtime.start =
                          {
                            pos_fname = "../lib/demo_wrapped.mli";
                            pos_lnum = 14;
                            pos_bol = 615;
                            pos_cnum = 636
                          };
                        Ortac_runtime.stop =
                          {
                            pos_fname = "../lib/demo_wrapped.mli";
                            pos_lnum = 14;
                            pos_bol = 615;
                            pos_cnum = 637
                          }
                      })));
        contents =
          (try
             Ortac_runtime.Gospelstdlib.List.init
               (Ortac_runtime.Gospelstdlib.integer_of_int i) (fun _ -> a_1)
           with
           | e ->
               raise
                 (Ortac_runtime.Partial_function
                    (e,
                      {
                        Ortac_runtime.start =
                          {
                            pos_fname = "../lib/demo_wrapped.mli";
                            pos_lnum = 15;
                            pos_bol = 638;
                            pos_cnum = 663
                          };
                        Ortac_runtime.stop =
                          {
                            pos_fname = "../lib/demo_wrapped.mli";
                            pos_lnum = 15;
                            pos_bol = 638;
                            pos_cnum = 687
                          }
                      })))
      }
  end
module Model = (Ortac_runtime.Model.Make)(ModelElt)
module Spec =
  struct
    open STM
    type _ ty +=  
      | Integer: Ortac_runtime.integer ty 
    let integer = (Integer, Ortac_runtime.string_of_integer)
    type _ ty +=  
      | SUT: SUT.elt ty 
    let sut = (SUT, (fun _ -> "<sut>"))
    type sut = SUT.t
    let init_sut = SUT.create 1
    type state = Model.t
    let init_state = Model.create 1 ()
    type cmd =
      | To_size 
      | To_list 
      | Make of int * char 
      | Get of int 
      | Set of int * char 
    let show_cmd cmd__001_ =
      match cmd__001_ with
      | To_size -> Format.asprintf "%s <sut>" "to_size"
      | To_list -> Format.asprintf "%s <sut>" "to_list"
      | Make (i, a_1) ->
          Format.asprintf "protect (fun () -> %s %a %a)" "make"
            (Util.Pp.pp_int true) i (Util.Pp.pp_char true) a_1
      | Get i_1 ->
          Format.asprintf "protect (fun () -> %s <sut> %a)" "get"
            (Util.Pp.pp_int true) i_1
      | Set (i_2, a_2) ->
          Format.asprintf "%s <sut> %a %a" "set" (Util.Pp.pp_int true) i_2
            (Util.Pp.pp_char true) a_2
    let cleanup _ = ()
    let arb_cmd _ =
      let open QCheck in
        make ~print:show_cmd
          (let open Gen in
             oneof
               [pure To_size;
               pure To_list;
               ((pure (fun i -> fun a_1 -> Make (i, a_1))) <*>
                  small_signed_int)
                 <*> char;
               (pure (fun i_1 -> Get i_1)) <*> int;
               ((pure (fun i_2 -> fun a_2 -> Set (i_2, a_2))) <*> int) <*>
                 char])
    let next_state cmd__002_ state__003_ =
      match cmd__002_ with
      | To_size ->
          let __arg0__004_ = Model.get state__003_ 0 in
          let __arg0__005_ = __arg0__004_ in
          Model.push (Model.drop_n state__003_ 1) __arg0__005_
      | To_list ->
          let __arg0_1__006_ = Model.get state__003_ 0 in
          let __arg0_1__007_ = __arg0_1__006_ in
          Model.push (Model.drop_n state__003_ 1) __arg0_1__007_
      | Make (i, a_1) ->
          if
            (try
               Ortac_runtime.Gospelstdlib.(>=)
                 (Ortac_runtime.Gospelstdlib.integer_of_int i)
                 (Ortac_runtime.Gospelstdlib.integer_of_int 0)
             with | e -> false)
          then
            let t_1__009_ =
              let open ModelElt in
                {
                  size =
                    (try i
                     with
                     | e ->
                         raise
                           (Ortac_runtime.Partial_function
                              (e,
                                {
                                  Ortac_runtime.start =
                                    {
                                      pos_fname = "../lib/demo_wrapped.mli";
                                      pos_lnum = 14;
                                      pos_bol = 615;
                                      pos_cnum = 636
                                    };
                                  Ortac_runtime.stop =
                                    {
                                      pos_fname = "../lib/demo_wrapped.mli";
                                      pos_lnum = 14;
                                      pos_bol = 615;
                                      pos_cnum = 637
                                    }
                                })));
                  contents =
                    (try
                       Ortac_runtime.Gospelstdlib.List.init
                         (Ortac_runtime.Gospelstdlib.integer_of_int i)
                         (fun _ -> a_1)
                     with
                     | e ->
                         raise
                           (Ortac_runtime.Partial_function
                              (e,
                                {
                                  Ortac_runtime.start =
                                    {
                                      pos_fname = "../lib/demo_wrapped.mli";
                                      pos_lnum = 15;
                                      pos_bol = 638;
                                      pos_cnum = 663
                                    };
                                  Ortac_runtime.stop =
                                    {
                                      pos_fname = "../lib/demo_wrapped.mli";
                                      pos_lnum = 15;
                                      pos_bol = 638;
                                      pos_cnum = 687
                                    }
                                })))
                } in
            Model.push (Model.drop_n state__003_ 0) t_1__009_
          else state__003_
      | Get i_1 ->
          let t_2__010_ = Model.get state__003_ 0 in
          let t_2__011_ = t_2__010_ in
          Model.push (Model.drop_n state__003_ 1) t_2__011_
      | Set (i_2, a_2) ->
          let t_3__012_ = Model.get state__003_ 0 in
          let t_3__013_ =
            let open ModelElt in
              {
                t_3__012_ with
                contents =
                  (try
                     Ortac_runtime.Gospelstdlib.List.mapi
                       (fun j ->
                          fun x ->
                            if
                              j =
                                (Ortac_runtime.Gospelstdlib.integer_of_int
                                   i_2)
                            then a_2
                            else x) t_3__012_.contents
                   with
                   | e ->
                       raise
                         (Ortac_runtime.Partial_function
                            (e,
                              {
                                Ortac_runtime.start =
                                  {
                                    pos_fname = "../lib/demo_wrapped.mli";
                                    pos_lnum = 26;
                                    pos_bol = 1152;
                                    pos_cnum = 1177
                                  };
                                Ortac_runtime.stop =
                                  {
                                    pos_fname = "../lib/demo_wrapped.mli";
                                    pos_lnum = 26;
                                    pos_bol = 1152;
                                    pos_cnum = 1251
                                  }
                              })))
              } in
          Model.push (Model.drop_n state__003_ 1) t_3__013_
    let precond cmd__026_ state__027_ =
      match cmd__026_ with
      | To_size -> true
      | To_list -> true
      | Make (i, a_1) -> true
      | Get i_1 -> true
      | Set (i_2, a_2) -> let t_3__028_ = Model.get state__027_ 0 in true
    let postcond _ _ _ = true
    let run cmd__029_ sut__030_ =
      match cmd__029_ with
      | To_size ->
          Res
            (int,
              (let __arg0__031_ = SUT.get sut__030_ 0 in
               let res__032_ = to_size __arg0__031_ in res__032_))
      | To_list ->
          Res
            ((list char),
              (let __arg0_1__033_ = SUT.get sut__030_ 0 in
               let res__034_ = to_list __arg0_1__033_ in res__034_))
      | Make (i, a_1) ->
          Res
            ((result sut exn),
              (let res__035_ = protect (fun () -> make i a_1) () in
               ((match res__035_ with
                 | Ok res -> SUT.push sut__030_ res
                 | Error _ -> ());
                res__035_)))
      | Get i_1 ->
          Res
            ((result char exn),
              (let t_2__036_ = SUT.get sut__030_ 0 in
               let res__037_ = protect (fun () -> get t_2__036_ i_1) () in
               res__037_))
      | Set (i_2, a_2) ->
          Res
            (unit,
              (let t_3__038_ = SUT.get sut__030_ 0 in
               let res__039_ = set t_3__038_ i_2 a_2 in res__039_))
  end
module STMTests = (Ortac_runtime.Make)(Spec)
let check_init_state () = ()
let ortac_show_cmd cmd__041_ state__042_ last__044_ res__043_ =
  let open Spec in
    let open STM in
      match (cmd__041_, res__043_) with
      | (To_size, Res ((Int, _), _)) ->
          let lhs = if last__044_ then "r" else "_"
          and shift = 0 in
          Format.asprintf "let %s = %s %s" lhs "to_size"
            (SUT.get_name state__042_ (0 + shift))
      | (To_list, Res ((List (Char), _), _)) ->
          let lhs = if last__044_ then "r" else "_"
          and shift = 0 in
          Format.asprintf "let %s = %s %s" lhs "to_list"
            (SUT.get_name state__042_ (0 + shift))
      | (Make (i, a_1), Res ((Result (SUT, Exn), _), t_1)) ->
          let lhs =
            if last__044_
            then "r"
            else
              (match t_1 with
               | Ok _ -> "Ok " ^ (SUT.get_name state__042_ 0)
               | Error _ -> "_")
          and shift = match t_1 with | Ok _ -> 1 | Error _ -> 0 in
          Format.asprintf "let %s = protect (fun () -> %s %a %a)" lhs "make"
            (Util.Pp.pp_int true) i (Util.Pp.pp_char true) a_1
      | (Get i_1, Res ((Result (Char, Exn), _), _)) ->
          let lhs = if last__044_ then "r" else "_"
          and shift = 0 in
          Format.asprintf "let %s = protect (fun () -> %s %s %a)" lhs "get"
            (SUT.get_name state__042_ (0 + shift)) (Util.Pp.pp_int true) i_1
      | (Set (i_2, a_2), Res ((Unit, _), _)) ->
          let lhs = if last__044_ then "r" else "_"
          and shift = 0 in
          Format.asprintf "let %s = %s %s %a %a" lhs "set"
            (SUT.get_name state__042_ (0 + shift)) (Util.Pp.pp_int true) i_2
            (Util.Pp.pp_char true) a_2
      | _ -> assert false
let ortac_postcond cmd__014_ state__015_ res__016_ =
  let open Spec in
    let open STM in
      let new_state__017_ = lazy (next_state cmd__014_ state__015_) in
      match (cmd__014_, res__016_) with
      | (To_size, Res ((Int, _), result)) -> None
      | (To_list, Res ((List (Char), _), result_1)) -> None
      | (Make (i, a_1), Res ((Result (SUT, Exn), _), t_1)) ->
          (match if
                   try
                     Ortac_runtime.Gospelstdlib.(>=)
                       (Ortac_runtime.Gospelstdlib.integer_of_int i)
                       (Ortac_runtime.Gospelstdlib.integer_of_int 0)
                   with | e -> false
                 then None
                 else
                   Some
                     (Ortac_runtime.report "Demo_wrapped" "make 100 'a'"
                        (try Ortac_runtime.Exception "Invalid_argument"
                         with | e -> Ortac_runtime.Out_of_domain) "make"
                        [("i >= 0",
                           {
                             Ortac_runtime.start =
                               {
                                 pos_fname = "../lib/demo_wrapped.mli";
                                 pos_lnum = 13;
                                 pos_bol = 597;
                                 pos_cnum = 608
                               };
                             Ortac_runtime.stop =
                               {
                                 pos_fname = "../lib/demo_wrapped.mli";
                                 pos_lnum = 13;
                                 pos_bol = 597;
                                 pos_cnum = 614
                               }
                           })])
           with
           | None -> (match t_1 with | Ok t_1 -> None | _ -> None)
           | _ ->
               (match t_1 with
                | Error (Invalid_argument _) -> None
                | _ ->
                    if
                      (try
                         Ortac_runtime.Gospelstdlib.(>=)
                           (Ortac_runtime.Gospelstdlib.integer_of_int i)
                           (Ortac_runtime.Gospelstdlib.integer_of_int 0)
                       with | e -> false)
                    then None
                    else
                      Some
                        (Ortac_runtime.report "Demo_wrapped" "make 100 'a'"
                           (try Ortac_runtime.Exception "Invalid_argument"
                            with | e -> Ortac_runtime.Out_of_domain) "make"
                           [("i >= 0",
                              {
                                Ortac_runtime.start =
                                  {
                                    pos_fname = "../lib/demo_wrapped.mli";
                                    pos_lnum = 13;
                                    pos_bol = 597;
                                    pos_cnum = 608
                                  };
                                Ortac_runtime.stop =
                                  {
                                    pos_fname = "../lib/demo_wrapped.mli";
                                    pos_lnum = 13;
                                    pos_bol = 597;
                                    pos_cnum = 614
                                  }
                              })])))
      | (Get i_1, Res ((Result (Char, Exn), _), a_3)) ->
          (match a_3 with
           | Ok a_3 ->
               if
                 let t_old__022_ = Model.get state__015_ 0
                 and t_new__023_ =
                   lazy (Model.get (Lazy.force new_state__017_) 0) in
                 (try
                    a_3 =
                      (Ortac_runtime.Gospelstdlib.List.nth
                         (Lazy.force t_new__023_).contents
                         (Ortac_runtime.Gospelstdlib.integer_of_int i_1))
                  with | e -> false)
               then None
               else
                 Some
                   (Ortac_runtime.report "Demo_wrapped" "make 100 'a'"
                      (try
                         Ortac_runtime.Protected_value
                           (Res
                              (char,
                                (let t_old__020_ = Model.get state__015_ 0
                                 and t_new__021_ =
                                   lazy
                                     (Model.get (Lazy.force new_state__017_)
                                        0) in
                                 Ortac_runtime.Gospelstdlib.List.nth
                                   (Lazy.force t_new__021_).contents
                                   (Ortac_runtime.Gospelstdlib.integer_of_int
                                      i_1))))
                       with | e -> Ortac_runtime.Out_of_domain) "get"
                      [("a = List.nth t.contents i",
                         {
                           Ortac_runtime.start =
                             {
                               pos_fname = "../lib/demo_wrapped.mli";
                               pos_lnum = 20;
                               pos_bol = 891;
                               pos_cnum = 903
                             };
                           Ortac_runtime.stop =
                             {
                               pos_fname = "../lib/demo_wrapped.mli";
                               pos_lnum = 20;
                               pos_bol = 891;
                               pos_cnum = 928
                             }
                         })])
           | _ -> None)
      | (Set (i_2, a_2), Res ((Unit, _), _)) -> None
      | _ -> None
let _ =
  QCheck_base_runner.run_tests_main
    (let count = 1000 in
     [STMTests.agree_test ~count ~name:"Demo_wrapped STM tests" 1
        check_init_state ortac_show_cmd ortac_postcond])
