(library
 (name demo_wrapped_config)
 (libraries demo_wrapped)
 (modules demo_wrapped_config))

(rule
 (alias runtest)
 (mode promote)
 (action
  (with-stdout-to
   dune.inc
   ; (pipe-stdout
    (run ortac dune qcheck-stm ../lib/demo_wrapped.mli)
    ; filter out the promote settings for the generated
    ; test code, so the test code is not committed.
    ; (run grep -v "alias runtest")
    ; (run grep -v "mode promote")
    ; )
  )))

(include dune.inc)
