(library
 (name demo_config)
 (libraries demo qcheck-core)
 (modules demo_config))

(rule
 (alias runtest)
 (mode promote)
 (action
  (with-stdout-to
   dune.inc
   (pipe-stdout
    (run ortac dune qcheck-stm ../lib/demo.mli)
    ; filter out the promote settings for the generated
    ; test code, so the test code is not committed.
    (run grep -v "alias runtest")
    (run grep -v "mode promote")
    )
  )))

(include dune.inc)

(test
 (name test_bincaml)
 (modules test_bincaml)
 (libraries bincaml_inline_tests))

(library
 (name bincaml_inline_tests)
 (inline_tests)
 (modules test_expr_print)
 (preprocess
  (pps ppx_expect_nobase)))
