(********************************************************)
(*           AUTOGENERATED FILE - DO NOT EDIT!          *)
(********************************************************)
(* Generated by: ocaml-protoc-plugin                    *)
(* https://github.com/andersfugmann/ocaml-protoc-plugin *)
(********************************************************)
(*
  Source: ByteInterval.proto
  Syntax: proto3
  Parameters:
    debug=false
    annot=''
    opens=[]
    int64_as_int=true
    int32_as_int=true
    fixed_as_int=false
    singleton_record=false
    prefix_output_with_package=false
*)
[@@@ocaml.alert "-protobuf"] (* Disable deprecation warnings for protobuf*)
(**/**)
module Runtime' = Ocaml_protoc_plugin [@@warning "-33"]
module Imported'modules = struct
  module CodeBlock = CodeBlock
  module DataBlock = DataBlock
  module SymbolicExpression = SymbolicExpression
end
(**/**)
module rec Gtirb : sig
  module rec Proto : sig
    module rec Block : sig
      type t = {
        offset:int;
        value:[ `not_set | `Code of Imported'modules.CodeBlock.Gtirb.Proto.CodeBlock.t | `Data of Imported'modules.DataBlock.Gtirb.Proto.DataBlock.t ];
      }
      val make: ?offset:int -> ?value:[ `not_set | `Code of Imported'modules.CodeBlock.Gtirb.Proto.CodeBlock.t | `Data of Imported'modules.DataBlock.Gtirb.Proto.DataBlock.t ] -> unit -> t
      (** Helper function to generate a message using default values *)

      val to_proto: t -> Runtime'.Writer.t
      (** Serialize the message to binary format *)

      val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from binary format *)

      val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
      (** Serialize to Json (compatible with Yojson.Basic.t) *)

      val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from Json (compatible with Yojson.Basic.t) *)

      val name: unit -> string
      (** Fully qualified protobuf name of this message *)

      (**/**)
      type make_t = ?offset:int -> ?value:[ `not_set | `Code of Imported'modules.CodeBlock.Gtirb.Proto.CodeBlock.t | `Data of Imported'modules.DataBlock.Gtirb.Proto.DataBlock.t ] -> unit -> t
      val merge: t -> t -> t
      val to_proto': Runtime'.Writer.t -> t -> unit
      val from_proto_exn: Runtime'.Reader.t -> t
      val from_json_exn: Runtime'.Json.t -> t
      (**/**)
    end

    and ByteInterval : sig
      type t = {
        uuid:bytes;
        blocks:Block.t list;
        symbolic_expressions:(int * Imported'modules.SymbolicExpression.Gtirb.Proto.SymbolicExpression.t option) list;
        has_address:bool;
        address:int;
        size:int;
        contents:bytes;
      }
      val make: ?uuid:bytes -> ?blocks:Block.t list -> ?symbolic_expressions:(int * Imported'modules.SymbolicExpression.Gtirb.Proto.SymbolicExpression.t option) list -> ?has_address:bool -> ?address:int -> ?size:int -> ?contents:bytes -> unit -> t
      (** Helper function to generate a message using default values *)

      val to_proto: t -> Runtime'.Writer.t
      (** Serialize the message to binary format *)

      val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from binary format *)

      val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
      (** Serialize to Json (compatible with Yojson.Basic.t) *)

      val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from Json (compatible with Yojson.Basic.t) *)

      val name: unit -> string
      (** Fully qualified protobuf name of this message *)

      (**/**)
      type make_t = ?uuid:bytes -> ?blocks:Block.t list -> ?symbolic_expressions:(int * Imported'modules.SymbolicExpression.Gtirb.Proto.SymbolicExpression.t option) list -> ?has_address:bool -> ?address:int -> ?size:int -> ?contents:bytes -> unit -> t
      val merge: t -> t -> t
      val to_proto': Runtime'.Writer.t -> t -> unit
      val from_proto_exn: Runtime'.Reader.t -> t
      val from_json_exn: Runtime'.Json.t -> t
      (**/**)
    end

  end
end = struct
  module rec Proto : sig
    module rec Block : sig
      type t = {
        offset:int;
        value:[ `not_set | `Code of Imported'modules.CodeBlock.Gtirb.Proto.CodeBlock.t | `Data of Imported'modules.DataBlock.Gtirb.Proto.DataBlock.t ];
      }
      val make: ?offset:int -> ?value:[ `not_set | `Code of Imported'modules.CodeBlock.Gtirb.Proto.CodeBlock.t | `Data of Imported'modules.DataBlock.Gtirb.Proto.DataBlock.t ] -> unit -> t
      (** Helper function to generate a message using default values *)

      val to_proto: t -> Runtime'.Writer.t
      (** Serialize the message to binary format *)

      val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from binary format *)

      val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
      (** Serialize to Json (compatible with Yojson.Basic.t) *)

      val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from Json (compatible with Yojson.Basic.t) *)

      val name: unit -> string
      (** Fully qualified protobuf name of this message *)

      (**/**)
      type make_t = ?offset:int -> ?value:[ `not_set | `Code of Imported'modules.CodeBlock.Gtirb.Proto.CodeBlock.t | `Data of Imported'modules.DataBlock.Gtirb.Proto.DataBlock.t ] -> unit -> t
      val merge: t -> t -> t
      val to_proto': Runtime'.Writer.t -> t -> unit
      val from_proto_exn: Runtime'.Reader.t -> t
      val from_json_exn: Runtime'.Json.t -> t
      (**/**)
    end

    and ByteInterval : sig
      type t = {
        uuid:bytes;
        blocks:Block.t list;
        symbolic_expressions:(int * Imported'modules.SymbolicExpression.Gtirb.Proto.SymbolicExpression.t option) list;
        has_address:bool;
        address:int;
        size:int;
        contents:bytes;
      }
      val make: ?uuid:bytes -> ?blocks:Block.t list -> ?symbolic_expressions:(int * Imported'modules.SymbolicExpression.Gtirb.Proto.SymbolicExpression.t option) list -> ?has_address:bool -> ?address:int -> ?size:int -> ?contents:bytes -> unit -> t
      (** Helper function to generate a message using default values *)

      val to_proto: t -> Runtime'.Writer.t
      (** Serialize the message to binary format *)

      val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from binary format *)

      val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
      (** Serialize to Json (compatible with Yojson.Basic.t) *)

      val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from Json (compatible with Yojson.Basic.t) *)

      val name: unit -> string
      (** Fully qualified protobuf name of this message *)

      (**/**)
      type make_t = ?uuid:bytes -> ?blocks:Block.t list -> ?symbolic_expressions:(int * Imported'modules.SymbolicExpression.Gtirb.Proto.SymbolicExpression.t option) list -> ?has_address:bool -> ?address:int -> ?size:int -> ?contents:bytes -> unit -> t
      val merge: t -> t -> t
      val to_proto': Runtime'.Writer.t -> t -> unit
      val from_proto_exn: Runtime'.Reader.t -> t
      val from_json_exn: Runtime'.Json.t -> t
      (**/**)
    end

  end = struct
    module rec Block : sig
      type t = {
        offset:int;
        value:[ `not_set | `Code of Imported'modules.CodeBlock.Gtirb.Proto.CodeBlock.t | `Data of Imported'modules.DataBlock.Gtirb.Proto.DataBlock.t ];
      }
      val make: ?offset:int -> ?value:[ `not_set | `Code of Imported'modules.CodeBlock.Gtirb.Proto.CodeBlock.t | `Data of Imported'modules.DataBlock.Gtirb.Proto.DataBlock.t ] -> unit -> t
      (** Helper function to generate a message using default values *)

      val to_proto: t -> Runtime'.Writer.t
      (** Serialize the message to binary format *)

      val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from binary format *)

      val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
      (** Serialize to Json (compatible with Yojson.Basic.t) *)

      val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from Json (compatible with Yojson.Basic.t) *)

      val name: unit -> string
      (** Fully qualified protobuf name of this message *)

      (**/**)
      type make_t = ?offset:int -> ?value:[ `not_set | `Code of Imported'modules.CodeBlock.Gtirb.Proto.CodeBlock.t | `Data of Imported'modules.DataBlock.Gtirb.Proto.DataBlock.t ] -> unit -> t
      val merge: t -> t -> t
      val to_proto': Runtime'.Writer.t -> t -> unit
      val from_proto_exn: Runtime'.Reader.t -> t
      val from_json_exn: Runtime'.Json.t -> t
      (**/**)
    end = struct
      module This'_ = Block
      let name () = ".gtirb.proto.Block"
      type t = {
        offset:int;
        value:[ `not_set | `Code of Imported'modules.CodeBlock.Gtirb.Proto.CodeBlock.t | `Data of Imported'modules.DataBlock.Gtirb.Proto.DataBlock.t ];
      }
      type make_t = ?offset:int -> ?value:[ `not_set | `Code of Imported'modules.CodeBlock.Gtirb.Proto.CodeBlock.t | `Data of Imported'modules.DataBlock.Gtirb.Proto.DataBlock.t ] -> unit -> t
      let make ?(offset = 0) ?(value = `not_set) () = { offset; value }
      let merge =
      let merge_offset = Runtime'.Merge.merge Runtime'.Spec.( basic ((1, "offset", "offset"), uint64_int, (0)) ) in
      let merge_oneof_value__Code = Runtime'.Merge.merge Runtime'.Spec.( basic_req ((0, "", ""), (message (module Imported'modules.CodeBlock.Gtirb.Proto.CodeBlock))) ) in
      let merge_oneof_value__Data = Runtime'.Merge.merge Runtime'.Spec.( basic_req ((0, "", ""), (message (module Imported'modules.DataBlock.Gtirb.Proto.DataBlock))) ) in
      fun t1 t2 -> {
      	offset = (merge_offset t1.offset t2.offset);
      	value = (match (t1.value, t2.value) with
      	| (`Code v1, `Code v2) -> `Code (merge_oneof_value__Code v1 v2)
      	| (`Data v1, `Data v2) -> `Data (merge_oneof_value__Data v1 v2)
      	| (v1, `not_set) -> v1
      	| (_, v2) -> v2);
       }
      let spec () = Runtime'.Spec.( basic ((1, "offset", "offset"), uint64_int, (0)) ^:: oneof (([ oneof_elem ((2, "code", "code"), (message (module Imported'modules.CodeBlock.Gtirb.Proto.CodeBlock)), ((fun v -> `Code v), (function `Code v -> v | _ -> raise (Invalid_argument "Cannot destruct given oneof")))); oneof_elem ((3, "data", "data"), (message (module Imported'modules.DataBlock.Gtirb.Proto.DataBlock)), ((fun v -> `Data v), (function `Data v -> v | _ -> raise (Invalid_argument "Cannot destruct given oneof")))) ], (function | `not_set -> failwith "Impossible case" | `Code _ -> 0 | `Data _ -> 1))) ^:: nil )
      let to_proto' =
        let serialize = Runtime'.apply_lazy (fun () -> Runtime'.Serialize.serialize (spec ())) in
        fun writer { offset; value } -> serialize writer offset value

      let to_proto t = let writer = Runtime'.Writer.init () in to_proto' writer t; writer
      let from_proto_exn =
        let constructor offset value = { offset; value } in
        Runtime'.apply_lazy (fun () -> Runtime'.Deserialize.deserialize (spec ()) constructor)
      let from_proto writer = Runtime'.Result.catch (fun () -> from_proto_exn writer)
      let to_json options =
        let serialize = Runtime'.Serialize_json.serialize ~message_name:(name ()) (spec ()) options in
        fun { offset; value } -> serialize offset value
      let from_json_exn =
        let constructor offset value = { offset; value } in
        Runtime'.apply_lazy (fun () -> Runtime'.Deserialize_json.deserialize ~message_name:(name ()) (spec ()) constructor)
      let from_json json = Runtime'.Result.catch (fun () -> from_json_exn json)
    end

    and ByteInterval : sig
      type t = {
        uuid:bytes;
        blocks:Block.t list;
        symbolic_expressions:(int * Imported'modules.SymbolicExpression.Gtirb.Proto.SymbolicExpression.t option) list;
        has_address:bool;
        address:int;
        size:int;
        contents:bytes;
      }
      val make: ?uuid:bytes -> ?blocks:Block.t list -> ?symbolic_expressions:(int * Imported'modules.SymbolicExpression.Gtirb.Proto.SymbolicExpression.t option) list -> ?has_address:bool -> ?address:int -> ?size:int -> ?contents:bytes -> unit -> t
      (** Helper function to generate a message using default values *)

      val to_proto: t -> Runtime'.Writer.t
      (** Serialize the message to binary format *)

      val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from binary format *)

      val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
      (** Serialize to Json (compatible with Yojson.Basic.t) *)

      val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from Json (compatible with Yojson.Basic.t) *)

      val name: unit -> string
      (** Fully qualified protobuf name of this message *)

      (**/**)
      type make_t = ?uuid:bytes -> ?blocks:Block.t list -> ?symbolic_expressions:(int * Imported'modules.SymbolicExpression.Gtirb.Proto.SymbolicExpression.t option) list -> ?has_address:bool -> ?address:int -> ?size:int -> ?contents:bytes -> unit -> t
      val merge: t -> t -> t
      val to_proto': Runtime'.Writer.t -> t -> unit
      val from_proto_exn: Runtime'.Reader.t -> t
      val from_json_exn: Runtime'.Json.t -> t
      (**/**)
    end = struct
      module This'_ = ByteInterval
      let name () = ".gtirb.proto.ByteInterval"
      type t = {
        uuid:bytes;
        blocks:Block.t list;
        symbolic_expressions:(int * Imported'modules.SymbolicExpression.Gtirb.Proto.SymbolicExpression.t option) list;
        has_address:bool;
        address:int;
        size:int;
        contents:bytes;
      }
      type make_t = ?uuid:bytes -> ?blocks:Block.t list -> ?symbolic_expressions:(int * Imported'modules.SymbolicExpression.Gtirb.Proto.SymbolicExpression.t option) list -> ?has_address:bool -> ?address:int -> ?size:int -> ?contents:bytes -> unit -> t
      let make ?(uuid = (Bytes.of_string {||})) ?(blocks = []) ?(symbolic_expressions = []) ?(has_address = false) ?(address = 0) ?(size = 0) ?(contents = (Bytes.of_string {||})) () = { uuid; blocks; symbolic_expressions; has_address; address; size; contents }
      let merge =
      let merge_uuid = Runtime'.Merge.merge Runtime'.Spec.( basic ((1, "uuid", "uuid"), bytes, ((Bytes.of_string {||}))) ) in
      let merge_blocks = Runtime'.Merge.merge Runtime'.Spec.( repeated ((2, "blocks", "blocks"), (message (module Block)), not_packed) ) in
      let merge_symbolic_expressions = Runtime'.Merge.merge Runtime'.Spec.( map ((3, "symbolic_expressions", "symbolicExpressions"), (uint64_int, basic_opt ((2, "value", "value"), (message (module Imported'modules.SymbolicExpression.Gtirb.Proto.SymbolicExpression))))) ) in
      let merge_has_address = Runtime'.Merge.merge Runtime'.Spec.( basic ((4, "has_address", "hasAddress"), bool, (false)) ) in
      let merge_address = Runtime'.Merge.merge Runtime'.Spec.( basic ((5, "address", "address"), uint64_int, (0)) ) in
      let merge_size = Runtime'.Merge.merge Runtime'.Spec.( basic ((6, "size", "size"), uint64_int, (0)) ) in
      let merge_contents = Runtime'.Merge.merge Runtime'.Spec.( basic ((7, "contents", "contents"), bytes, ((Bytes.of_string {||}))) ) in
      fun t1 t2 -> {
      	uuid = (merge_uuid t1.uuid t2.uuid);
      	blocks = (merge_blocks t1.blocks t2.blocks);
      	symbolic_expressions = (merge_symbolic_expressions t1.symbolic_expressions t2.symbolic_expressions);
      	has_address = (merge_has_address t1.has_address t2.has_address);
      	address = (merge_address t1.address t2.address);
      	size = (merge_size t1.size t2.size);
      	contents = (merge_contents t1.contents t2.contents);
       }
      let spec () = Runtime'.Spec.( basic ((1, "uuid", "uuid"), bytes, ((Bytes.of_string {||}))) ^:: repeated ((2, "blocks", "blocks"), (message (module Block)), not_packed) ^:: map ((3, "symbolic_expressions", "symbolicExpressions"), (uint64_int, basic_opt ((2, "value", "value"), (message (module Imported'modules.SymbolicExpression.Gtirb.Proto.SymbolicExpression))))) ^:: basic ((4, "has_address", "hasAddress"), bool, (false)) ^:: basic ((5, "address", "address"), uint64_int, (0)) ^:: basic ((6, "size", "size"), uint64_int, (0)) ^:: basic ((7, "contents", "contents"), bytes, ((Bytes.of_string {||}))) ^:: nil )
      let to_proto' =
        let serialize = Runtime'.apply_lazy (fun () -> Runtime'.Serialize.serialize (spec ())) in
        fun writer { uuid; blocks; symbolic_expressions; has_address; address; size; contents } -> serialize writer uuid blocks symbolic_expressions has_address address size contents

      let to_proto t = let writer = Runtime'.Writer.init () in to_proto' writer t; writer
      let from_proto_exn =
        let constructor uuid blocks symbolic_expressions has_address address size contents = { uuid; blocks; symbolic_expressions; has_address; address; size; contents } in
        Runtime'.apply_lazy (fun () -> Runtime'.Deserialize.deserialize (spec ()) constructor)
      let from_proto writer = Runtime'.Result.catch (fun () -> from_proto_exn writer)
      let to_json options =
        let serialize = Runtime'.Serialize_json.serialize ~message_name:(name ()) (spec ()) options in
        fun { uuid; blocks; symbolic_expressions; has_address; address; size; contents } -> serialize uuid blocks symbolic_expressions has_address address size contents
      let from_json_exn =
        let constructor uuid blocks symbolic_expressions has_address address size contents = { uuid; blocks; symbolic_expressions; has_address; address; size; contents } in
        Runtime'.apply_lazy (fun () -> Runtime'.Deserialize_json.deserialize ~message_name:(name ()) (spec ()) constructor)
      let from_json json = Runtime'.Result.catch (fun () -> from_json_exn json)
    end

  end
end

