(********************************************************)
(*           AUTOGENERATED FILE - DO NOT EDIT!          *)
(********************************************************)
(* Generated by: ocaml-protoc-plugin                    *)
(* https://github.com/andersfugmann/ocaml-protoc-plugin *)
(********************************************************)
(*
  Source: CFG.proto
  Syntax: proto3
  Parameters:
    debug=false
    annot=''
    opens=[]
    int64_as_int=true
    int32_as_int=true
    fixed_as_int=false
    singleton_record=false
    prefix_output_with_package=false
*)
[@@@ocaml.alert "-protobuf"] (* Disable deprecation warnings for protobuf*)
(**/**)
module Runtime' = Ocaml_protoc_plugin [@@warning "-33"]
module Imported'modules = struct
end
(**/**)
module rec Gtirb : sig
  module rec Proto : sig
    module rec EdgeType : sig
      type t =
        | Type_Branch
        | Type_Call
        | Type_Fallthrough
        | Type_Return
        | Type_Syscall
        | Type_Sysret

      val name: unit -> string
      (** Fully qualified protobuf name of this enum *)

      (**/**)
      val to_int: t -> int
      val from_int: int -> t Runtime'.Result.t
      val from_int_exn: int -> t
      val to_string: t -> string
      val from_string_exn: string -> t
      (**/**)
    end

    and EdgeLabel : sig
      type t = {
        conditional:bool;
        direct:bool;
        type':EdgeType.t;
      }
      val make: ?conditional:bool -> ?direct:bool -> ?type':EdgeType.t -> unit -> t
      (** Helper function to generate a message using default values *)

      val to_proto: t -> Runtime'.Writer.t
      (** Serialize the message to binary format *)

      val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from binary format *)

      val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
      (** Serialize to Json (compatible with Yojson.Basic.t) *)

      val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from Json (compatible with Yojson.Basic.t) *)

      val name: unit -> string
      (** Fully qualified protobuf name of this message *)

      (**/**)
      type make_t = ?conditional:bool -> ?direct:bool -> ?type':EdgeType.t -> unit -> t
      val merge: t -> t -> t
      val to_proto': Runtime'.Writer.t -> t -> unit
      val from_proto_exn: Runtime'.Reader.t -> t
      val from_json_exn: Runtime'.Json.t -> t
      (**/**)
    end

    and Edge : sig
      type t = {
        source_uuid:bytes;
        target_uuid:bytes;
        label:EdgeLabel.t option;
      }
      val make: ?source_uuid:bytes -> ?target_uuid:bytes -> ?label:EdgeLabel.t -> unit -> t
      (** Helper function to generate a message using default values *)

      val to_proto: t -> Runtime'.Writer.t
      (** Serialize the message to binary format *)

      val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from binary format *)

      val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
      (** Serialize to Json (compatible with Yojson.Basic.t) *)

      val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from Json (compatible with Yojson.Basic.t) *)

      val name: unit -> string
      (** Fully qualified protobuf name of this message *)

      (**/**)
      type make_t = ?source_uuid:bytes -> ?target_uuid:bytes -> ?label:EdgeLabel.t -> unit -> t
      val merge: t -> t -> t
      val to_proto': Runtime'.Writer.t -> t -> unit
      val from_proto_exn: Runtime'.Reader.t -> t
      val from_json_exn: Runtime'.Json.t -> t
      (**/**)
    end

    and CFG : sig
      type t = {
        edges:Edge.t list;
        vertices:bytes list;
      }
      val make: ?edges:Edge.t list -> ?vertices:bytes list -> unit -> t
      (** Helper function to generate a message using default values *)

      val to_proto: t -> Runtime'.Writer.t
      (** Serialize the message to binary format *)

      val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from binary format *)

      val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
      (** Serialize to Json (compatible with Yojson.Basic.t) *)

      val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from Json (compatible with Yojson.Basic.t) *)

      val name: unit -> string
      (** Fully qualified protobuf name of this message *)

      (**/**)
      type make_t = ?edges:Edge.t list -> ?vertices:bytes list -> unit -> t
      val merge: t -> t -> t
      val to_proto': Runtime'.Writer.t -> t -> unit
      val from_proto_exn: Runtime'.Reader.t -> t
      val from_json_exn: Runtime'.Json.t -> t
      (**/**)
    end

  end
end = struct
  module rec Proto : sig
    module rec EdgeType : sig
      type t =
        | Type_Branch
        | Type_Call
        | Type_Fallthrough
        | Type_Return
        | Type_Syscall
        | Type_Sysret

      val name: unit -> string
      (** Fully qualified protobuf name of this enum *)

      (**/**)
      val to_int: t -> int
      val from_int: int -> t Runtime'.Result.t
      val from_int_exn: int -> t
      val to_string: t -> string
      val from_string_exn: string -> t
      (**/**)
    end

    and EdgeLabel : sig
      type t = {
        conditional:bool;
        direct:bool;
        type':EdgeType.t;
      }
      val make: ?conditional:bool -> ?direct:bool -> ?type':EdgeType.t -> unit -> t
      (** Helper function to generate a message using default values *)

      val to_proto: t -> Runtime'.Writer.t
      (** Serialize the message to binary format *)

      val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from binary format *)

      val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
      (** Serialize to Json (compatible with Yojson.Basic.t) *)

      val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from Json (compatible with Yojson.Basic.t) *)

      val name: unit -> string
      (** Fully qualified protobuf name of this message *)

      (**/**)
      type make_t = ?conditional:bool -> ?direct:bool -> ?type':EdgeType.t -> unit -> t
      val merge: t -> t -> t
      val to_proto': Runtime'.Writer.t -> t -> unit
      val from_proto_exn: Runtime'.Reader.t -> t
      val from_json_exn: Runtime'.Json.t -> t
      (**/**)
    end

    and Edge : sig
      type t = {
        source_uuid:bytes;
        target_uuid:bytes;
        label:EdgeLabel.t option;
      }
      val make: ?source_uuid:bytes -> ?target_uuid:bytes -> ?label:EdgeLabel.t -> unit -> t
      (** Helper function to generate a message using default values *)

      val to_proto: t -> Runtime'.Writer.t
      (** Serialize the message to binary format *)

      val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from binary format *)

      val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
      (** Serialize to Json (compatible with Yojson.Basic.t) *)

      val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from Json (compatible with Yojson.Basic.t) *)

      val name: unit -> string
      (** Fully qualified protobuf name of this message *)

      (**/**)
      type make_t = ?source_uuid:bytes -> ?target_uuid:bytes -> ?label:EdgeLabel.t -> unit -> t
      val merge: t -> t -> t
      val to_proto': Runtime'.Writer.t -> t -> unit
      val from_proto_exn: Runtime'.Reader.t -> t
      val from_json_exn: Runtime'.Json.t -> t
      (**/**)
    end

    and CFG : sig
      type t = {
        edges:Edge.t list;
        vertices:bytes list;
      }
      val make: ?edges:Edge.t list -> ?vertices:bytes list -> unit -> t
      (** Helper function to generate a message using default values *)

      val to_proto: t -> Runtime'.Writer.t
      (** Serialize the message to binary format *)

      val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from binary format *)

      val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
      (** Serialize to Json (compatible with Yojson.Basic.t) *)

      val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from Json (compatible with Yojson.Basic.t) *)

      val name: unit -> string
      (** Fully qualified protobuf name of this message *)

      (**/**)
      type make_t = ?edges:Edge.t list -> ?vertices:bytes list -> unit -> t
      val merge: t -> t -> t
      val to_proto': Runtime'.Writer.t -> t -> unit
      val from_proto_exn: Runtime'.Reader.t -> t
      val from_json_exn: Runtime'.Json.t -> t
      (**/**)
    end

  end = struct
    module rec EdgeType : sig
      type t =
        | Type_Branch
        | Type_Call
        | Type_Fallthrough
        | Type_Return
        | Type_Syscall
        | Type_Sysret

      val name: unit -> string
      (** Fully qualified protobuf name of this enum *)

      (**/**)
      val to_int: t -> int
      val from_int: int -> t Runtime'.Result.t
      val from_int_exn: int -> t
      val to_string: t -> string
      val from_string_exn: string -> t
      (**/**)
    end = struct
      module This'_ = EdgeType
      type t =
        | Type_Branch
        | Type_Call
        | Type_Fallthrough
        | Type_Return
        | Type_Syscall
        | Type_Sysret

      let name () = ".gtirb.proto.EdgeType"
      let to_int = function
        | Type_Branch -> 0
        | Type_Call -> 1
        | Type_Fallthrough -> 2
        | Type_Return -> 3
        | Type_Syscall -> 4
        | Type_Sysret -> 5
      let from_int_exn = function
        | 0 -> Type_Branch
        | 1 -> Type_Call
        | 2 -> Type_Fallthrough
        | 3 -> Type_Return
        | 4 -> Type_Syscall
        | 5 -> Type_Sysret
        | n -> Runtime'.Result.raise (`Unknown_enum_value n)
      let from_int e = Runtime'.Result.catch (fun () -> from_int_exn e)
      let to_string = function
        | Type_Branch -> "Type_Branch"
        | Type_Call -> "Type_Call"
        | Type_Fallthrough -> "Type_Fallthrough"
        | Type_Return -> "Type_Return"
        | Type_Syscall -> "Type_Syscall"
        | Type_Sysret -> "Type_Sysret"
      let from_string_exn = function
        | "Type_Branch" -> Type_Branch
        | "Type_Call" -> Type_Call
        | "Type_Fallthrough" -> Type_Fallthrough
        | "Type_Return" -> Type_Return
        | "Type_Syscall" -> Type_Syscall
        | "Type_Sysret" -> Type_Sysret
        | s -> Runtime'.Result.raise (`Unknown_enum_name s)

    end

    and EdgeLabel : sig
      type t = {
        conditional:bool;
        direct:bool;
        type':EdgeType.t;
      }
      val make: ?conditional:bool -> ?direct:bool -> ?type':EdgeType.t -> unit -> t
      (** Helper function to generate a message using default values *)

      val to_proto: t -> Runtime'.Writer.t
      (** Serialize the message to binary format *)

      val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from binary format *)

      val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
      (** Serialize to Json (compatible with Yojson.Basic.t) *)

      val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from Json (compatible with Yojson.Basic.t) *)

      val name: unit -> string
      (** Fully qualified protobuf name of this message *)

      (**/**)
      type make_t = ?conditional:bool -> ?direct:bool -> ?type':EdgeType.t -> unit -> t
      val merge: t -> t -> t
      val to_proto': Runtime'.Writer.t -> t -> unit
      val from_proto_exn: Runtime'.Reader.t -> t
      val from_json_exn: Runtime'.Json.t -> t
      (**/**)
    end = struct
      module This'_ = EdgeLabel
      let name () = ".gtirb.proto.EdgeLabel"
      type t = {
        conditional:bool;
        direct:bool;
        type':EdgeType.t;
      }
      type make_t = ?conditional:bool -> ?direct:bool -> ?type':EdgeType.t -> unit -> t
      let make ?(conditional = false) ?(direct = false) ?(type' = EdgeType.from_int_exn 0) () = { conditional; direct; type' }
      let merge =
      let merge_conditional = Runtime'.Merge.merge Runtime'.Spec.( basic ((1, "conditional", "conditional"), bool, (false)) ) in
      let merge_direct = Runtime'.Merge.merge Runtime'.Spec.( basic ((2, "direct", "direct"), bool, (false)) ) in
      let merge_type' = Runtime'.Merge.merge Runtime'.Spec.( basic ((3, "type", "type"), (enum (module EdgeType)), (EdgeType.from_int_exn 0)) ) in
      fun t1 t2 -> {
      	conditional = (merge_conditional t1.conditional t2.conditional);
      	direct = (merge_direct t1.direct t2.direct);
      	type' = (merge_type' t1.type' t2.type');
       }
      let spec () = Runtime'.Spec.( basic ((1, "conditional", "conditional"), bool, (false)) ^:: basic ((2, "direct", "direct"), bool, (false)) ^:: basic ((3, "type", "type"), (enum (module EdgeType)), (EdgeType.from_int_exn 0)) ^:: nil )
      let to_proto' =
        let serialize = Runtime'.apply_lazy (fun () -> Runtime'.Serialize.serialize (spec ())) in
        fun writer { conditional; direct; type' } -> serialize writer conditional direct type'

      let to_proto t = let writer = Runtime'.Writer.init () in to_proto' writer t; writer
      let from_proto_exn =
        let constructor conditional direct type' = { conditional; direct; type' } in
        Runtime'.apply_lazy (fun () -> Runtime'.Deserialize.deserialize (spec ()) constructor)
      let from_proto writer = Runtime'.Result.catch (fun () -> from_proto_exn writer)
      let to_json options =
        let serialize = Runtime'.Serialize_json.serialize ~message_name:(name ()) (spec ()) options in
        fun { conditional; direct; type' } -> serialize conditional direct type'
      let from_json_exn =
        let constructor conditional direct type' = { conditional; direct; type' } in
        Runtime'.apply_lazy (fun () -> Runtime'.Deserialize_json.deserialize ~message_name:(name ()) (spec ()) constructor)
      let from_json json = Runtime'.Result.catch (fun () -> from_json_exn json)
    end

    and Edge : sig
      type t = {
        source_uuid:bytes;
        target_uuid:bytes;
        label:EdgeLabel.t option;
      }
      val make: ?source_uuid:bytes -> ?target_uuid:bytes -> ?label:EdgeLabel.t -> unit -> t
      (** Helper function to generate a message using default values *)

      val to_proto: t -> Runtime'.Writer.t
      (** Serialize the message to binary format *)

      val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from binary format *)

      val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
      (** Serialize to Json (compatible with Yojson.Basic.t) *)

      val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from Json (compatible with Yojson.Basic.t) *)

      val name: unit -> string
      (** Fully qualified protobuf name of this message *)

      (**/**)
      type make_t = ?source_uuid:bytes -> ?target_uuid:bytes -> ?label:EdgeLabel.t -> unit -> t
      val merge: t -> t -> t
      val to_proto': Runtime'.Writer.t -> t -> unit
      val from_proto_exn: Runtime'.Reader.t -> t
      val from_json_exn: Runtime'.Json.t -> t
      (**/**)
    end = struct
      module This'_ = Edge
      let name () = ".gtirb.proto.Edge"
      type t = {
        source_uuid:bytes;
        target_uuid:bytes;
        label:EdgeLabel.t option;
      }
      type make_t = ?source_uuid:bytes -> ?target_uuid:bytes -> ?label:EdgeLabel.t -> unit -> t
      let make ?(source_uuid = (Bytes.of_string {||})) ?(target_uuid = (Bytes.of_string {||})) ?label () = { source_uuid; target_uuid; label }
      let merge =
      let merge_source_uuid = Runtime'.Merge.merge Runtime'.Spec.( basic ((1, "source_uuid", "sourceUuid"), bytes, ((Bytes.of_string {||}))) ) in
      let merge_target_uuid = Runtime'.Merge.merge Runtime'.Spec.( basic ((2, "target_uuid", "targetUuid"), bytes, ((Bytes.of_string {||}))) ) in
      let merge_label = Runtime'.Merge.merge Runtime'.Spec.( basic_opt ((5, "label", "label"), (message (module EdgeLabel))) ) in
      fun t1 t2 -> {
      	source_uuid = (merge_source_uuid t1.source_uuid t2.source_uuid);
      	target_uuid = (merge_target_uuid t1.target_uuid t2.target_uuid);
      	label = (merge_label t1.label t2.label);
       }
      let spec () = Runtime'.Spec.( basic ((1, "source_uuid", "sourceUuid"), bytes, ((Bytes.of_string {||}))) ^:: basic ((2, "target_uuid", "targetUuid"), bytes, ((Bytes.of_string {||}))) ^:: basic_opt ((5, "label", "label"), (message (module EdgeLabel))) ^:: nil )
      let to_proto' =
        let serialize = Runtime'.apply_lazy (fun () -> Runtime'.Serialize.serialize (spec ())) in
        fun writer { source_uuid; target_uuid; label } -> serialize writer source_uuid target_uuid label

      let to_proto t = let writer = Runtime'.Writer.init () in to_proto' writer t; writer
      let from_proto_exn =
        let constructor source_uuid target_uuid label = { source_uuid; target_uuid; label } in
        Runtime'.apply_lazy (fun () -> Runtime'.Deserialize.deserialize (spec ()) constructor)
      let from_proto writer = Runtime'.Result.catch (fun () -> from_proto_exn writer)
      let to_json options =
        let serialize = Runtime'.Serialize_json.serialize ~message_name:(name ()) (spec ()) options in
        fun { source_uuid; target_uuid; label } -> serialize source_uuid target_uuid label
      let from_json_exn =
        let constructor source_uuid target_uuid label = { source_uuid; target_uuid; label } in
        Runtime'.apply_lazy (fun () -> Runtime'.Deserialize_json.deserialize ~message_name:(name ()) (spec ()) constructor)
      let from_json json = Runtime'.Result.catch (fun () -> from_json_exn json)
    end

    and CFG : sig
      type t = {
        edges:Edge.t list;
        vertices:bytes list;
      }
      val make: ?edges:Edge.t list -> ?vertices:bytes list -> unit -> t
      (** Helper function to generate a message using default values *)

      val to_proto: t -> Runtime'.Writer.t
      (** Serialize the message to binary format *)

      val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from binary format *)

      val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
      (** Serialize to Json (compatible with Yojson.Basic.t) *)

      val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from Json (compatible with Yojson.Basic.t) *)

      val name: unit -> string
      (** Fully qualified protobuf name of this message *)

      (**/**)
      type make_t = ?edges:Edge.t list -> ?vertices:bytes list -> unit -> t
      val merge: t -> t -> t
      val to_proto': Runtime'.Writer.t -> t -> unit
      val from_proto_exn: Runtime'.Reader.t -> t
      val from_json_exn: Runtime'.Json.t -> t
      (**/**)
    end = struct
      module This'_ = CFG
      let name () = ".gtirb.proto.CFG"
      type t = {
        edges:Edge.t list;
        vertices:bytes list;
      }
      type make_t = ?edges:Edge.t list -> ?vertices:bytes list -> unit -> t
      let make ?(edges = []) ?(vertices = []) () = { edges; vertices }
      let merge =
      let merge_edges = Runtime'.Merge.merge Runtime'.Spec.( repeated ((2, "edges", "edges"), (message (module Edge)), not_packed) ) in
      let merge_vertices = Runtime'.Merge.merge Runtime'.Spec.( repeated ((3, "vertices", "vertices"), bytes, not_packed) ) in
      fun t1 t2 -> {
      	edges = (merge_edges t1.edges t2.edges);
      	vertices = (merge_vertices t1.vertices t2.vertices);
       }
      let spec () = Runtime'.Spec.( repeated ((2, "edges", "edges"), (message (module Edge)), not_packed) ^:: repeated ((3, "vertices", "vertices"), bytes, not_packed) ^:: nil )
      let to_proto' =
        let serialize = Runtime'.apply_lazy (fun () -> Runtime'.Serialize.serialize (spec ())) in
        fun writer { edges; vertices } -> serialize writer edges vertices

      let to_proto t = let writer = Runtime'.Writer.init () in to_proto' writer t; writer
      let from_proto_exn =
        let constructor edges vertices = { edges; vertices } in
        Runtime'.apply_lazy (fun () -> Runtime'.Deserialize.deserialize (spec ()) constructor)
      let from_proto writer = Runtime'.Result.catch (fun () -> from_proto_exn writer)
      let to_json options =
        let serialize = Runtime'.Serialize_json.serialize ~message_name:(name ()) (spec ()) options in
        fun { edges; vertices } -> serialize edges vertices
      let from_json_exn =
        let constructor edges vertices = { edges; vertices } in
        Runtime'.apply_lazy (fun () -> Runtime'.Deserialize_json.deserialize ~message_name:(name ()) (spec ()) constructor)
      let from_json json = Runtime'.Result.catch (fun () -> from_json_exn json)
    end

  end
end

