(********************************************************)
(*           AUTOGENERATED FILE - DO NOT EDIT!          *)
(********************************************************)
(* Generated by: ocaml-protoc-plugin                    *)
(* https://github.com/andersfugmann/ocaml-protoc-plugin *)
(********************************************************)
(*
  Source: CodeBlock.proto
  Syntax: proto3
  Parameters:
    debug=false
    annot=''
    opens=[]
    int64_as_int=true
    int32_as_int=true
    fixed_as_int=false
    singleton_record=false
    prefix_output_with_package=false
*)
[@@@ocaml.alert "-protobuf"] (* Disable deprecation warnings for protobuf*)
(**/**)
module Runtime' = Ocaml_protoc_plugin [@@warning "-33"]
module Imported'modules = struct
end
(**/**)
module rec Gtirb : sig
  module rec Proto : sig
    module rec DecodeMode : sig
      type t =
        | All_Default
        | ARM_Thumb

      val name: unit -> string
      (** Fully qualified protobuf name of this enum *)

      (**/**)
      val to_int: t -> int
      val from_int: int -> t Runtime'.Result.t
      val from_int_exn: int -> t
      val to_string: t -> string
      val from_string_exn: string -> t
      (**/**)
    end

    and CodeBlock : sig
      type t = {
        uuid:bytes;
        size:int;
        decode_mode:DecodeMode.t;
      }
      val make: ?uuid:bytes -> ?size:int -> ?decode_mode:DecodeMode.t -> unit -> t
      (** Helper function to generate a message using default values *)

      val to_proto: t -> Runtime'.Writer.t
      (** Serialize the message to binary format *)

      val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from binary format *)

      val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
      (** Serialize to Json (compatible with Yojson.Basic.t) *)

      val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from Json (compatible with Yojson.Basic.t) *)

      val name: unit -> string
      (** Fully qualified protobuf name of this message *)

      (**/**)
      type make_t = ?uuid:bytes -> ?size:int -> ?decode_mode:DecodeMode.t -> unit -> t
      val merge: t -> t -> t
      val to_proto': Runtime'.Writer.t -> t -> unit
      val from_proto_exn: Runtime'.Reader.t -> t
      val from_json_exn: Runtime'.Json.t -> t
      (**/**)
    end

  end
end = struct
  module rec Proto : sig
    module rec DecodeMode : sig
      type t =
        | All_Default
        | ARM_Thumb

      val name: unit -> string
      (** Fully qualified protobuf name of this enum *)

      (**/**)
      val to_int: t -> int
      val from_int: int -> t Runtime'.Result.t
      val from_int_exn: int -> t
      val to_string: t -> string
      val from_string_exn: string -> t
      (**/**)
    end

    and CodeBlock : sig
      type t = {
        uuid:bytes;
        size:int;
        decode_mode:DecodeMode.t;
      }
      val make: ?uuid:bytes -> ?size:int -> ?decode_mode:DecodeMode.t -> unit -> t
      (** Helper function to generate a message using default values *)

      val to_proto: t -> Runtime'.Writer.t
      (** Serialize the message to binary format *)

      val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from binary format *)

      val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
      (** Serialize to Json (compatible with Yojson.Basic.t) *)

      val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from Json (compatible with Yojson.Basic.t) *)

      val name: unit -> string
      (** Fully qualified protobuf name of this message *)

      (**/**)
      type make_t = ?uuid:bytes -> ?size:int -> ?decode_mode:DecodeMode.t -> unit -> t
      val merge: t -> t -> t
      val to_proto': Runtime'.Writer.t -> t -> unit
      val from_proto_exn: Runtime'.Reader.t -> t
      val from_json_exn: Runtime'.Json.t -> t
      (**/**)
    end

  end = struct
    module rec DecodeMode : sig
      type t =
        | All_Default
        | ARM_Thumb

      val name: unit -> string
      (** Fully qualified protobuf name of this enum *)

      (**/**)
      val to_int: t -> int
      val from_int: int -> t Runtime'.Result.t
      val from_int_exn: int -> t
      val to_string: t -> string
      val from_string_exn: string -> t
      (**/**)
    end = struct
      module This'_ = DecodeMode
      type t =
        | All_Default
        | ARM_Thumb

      let name () = ".gtirb.proto.DecodeMode"
      let to_int = function
        | All_Default -> 0
        | ARM_Thumb -> 1
      let from_int_exn = function
        | 0 -> All_Default
        | 1 -> ARM_Thumb
        | n -> Runtime'.Result.raise (`Unknown_enum_value n)
      let from_int e = Runtime'.Result.catch (fun () -> from_int_exn e)
      let to_string = function
        | All_Default -> "All_Default"
        | ARM_Thumb -> "ARM_Thumb"
      let from_string_exn = function
        | "All_Default" -> All_Default
        | "ARM_Thumb" -> ARM_Thumb
        | s -> Runtime'.Result.raise (`Unknown_enum_name s)

    end

    and CodeBlock : sig
      type t = {
        uuid:bytes;
        size:int;
        decode_mode:DecodeMode.t;
      }
      val make: ?uuid:bytes -> ?size:int -> ?decode_mode:DecodeMode.t -> unit -> t
      (** Helper function to generate a message using default values *)

      val to_proto: t -> Runtime'.Writer.t
      (** Serialize the message to binary format *)

      val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from binary format *)

      val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
      (** Serialize to Json (compatible with Yojson.Basic.t) *)

      val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from Json (compatible with Yojson.Basic.t) *)

      val name: unit -> string
      (** Fully qualified protobuf name of this message *)

      (**/**)
      type make_t = ?uuid:bytes -> ?size:int -> ?decode_mode:DecodeMode.t -> unit -> t
      val merge: t -> t -> t
      val to_proto': Runtime'.Writer.t -> t -> unit
      val from_proto_exn: Runtime'.Reader.t -> t
      val from_json_exn: Runtime'.Json.t -> t
      (**/**)
    end = struct
      module This'_ = CodeBlock
      let name () = ".gtirb.proto.CodeBlock"
      type t = {
        uuid:bytes;
        size:int;
        decode_mode:DecodeMode.t;
      }
      type make_t = ?uuid:bytes -> ?size:int -> ?decode_mode:DecodeMode.t -> unit -> t
      let make ?(uuid = (Bytes.of_string {||})) ?(size = 0) ?(decode_mode = DecodeMode.from_int_exn 0) () = { uuid; size; decode_mode }
      let merge =
      let merge_uuid = Runtime'.Merge.merge Runtime'.Spec.( basic ((1, "uuid", "uuid"), bytes, ((Bytes.of_string {||}))) ) in
      let merge_size = Runtime'.Merge.merge Runtime'.Spec.( basic ((3, "size", "size"), uint64_int, (0)) ) in
      let merge_decode_mode = Runtime'.Merge.merge Runtime'.Spec.( basic ((4, "decode_mode", "decodeMode"), (enum (module DecodeMode)), (DecodeMode.from_int_exn 0)) ) in
      fun t1 t2 -> {
      	uuid = (merge_uuid t1.uuid t2.uuid);
      	size = (merge_size t1.size t2.size);
      	decode_mode = (merge_decode_mode t1.decode_mode t2.decode_mode);
       }
      let spec () = Runtime'.Spec.( basic ((1, "uuid", "uuid"), bytes, ((Bytes.of_string {||}))) ^:: basic ((3, "size", "size"), uint64_int, (0)) ^:: basic ((4, "decode_mode", "decodeMode"), (enum (module DecodeMode)), (DecodeMode.from_int_exn 0)) ^:: nil )
      let to_proto' =
        let serialize = Runtime'.apply_lazy (fun () -> Runtime'.Serialize.serialize (spec ())) in
        fun writer { uuid; size; decode_mode } -> serialize writer uuid size decode_mode

      let to_proto t = let writer = Runtime'.Writer.init () in to_proto' writer t; writer
      let from_proto_exn =
        let constructor uuid size decode_mode = { uuid; size; decode_mode } in
        Runtime'.apply_lazy (fun () -> Runtime'.Deserialize.deserialize (spec ()) constructor)
      let from_proto writer = Runtime'.Result.catch (fun () -> from_proto_exn writer)
      let to_json options =
        let serialize = Runtime'.Serialize_json.serialize ~message_name:(name ()) (spec ()) options in
        fun { uuid; size; decode_mode } -> serialize uuid size decode_mode
      let from_json_exn =
        let constructor uuid size decode_mode = { uuid; size; decode_mode } in
        Runtime'.apply_lazy (fun () -> Runtime'.Deserialize_json.deserialize ~message_name:(name ()) (spec ()) constructor)
      let from_json json = Runtime'.Result.catch (fun () -> from_json_exn json)
    end

  end
end

