(********************************************************)
(*           AUTOGENERATED FILE - DO NOT EDIT!          *)
(********************************************************)
(* Generated by: ocaml-protoc-plugin                    *)
(* https://github.com/andersfugmann/ocaml-protoc-plugin *)
(********************************************************)
(*
  Source: IR.proto
  Syntax: proto3
  Parameters:
    debug=false
    annot=''
    opens=[]
    int64_as_int=true
    int32_as_int=true
    fixed_as_int=false
    singleton_record=false
    prefix_output_with_package=false
*)
[@@@ocaml.alert "-protobuf"] (* Disable deprecation warnings for protobuf*)
(**/**)
module Runtime' = Ocaml_protoc_plugin [@@warning "-33"]
module Imported'modules = struct
  module AuxData = AuxData
  module CFG = CFG
  module Module = Module
end
(**/**)
module rec Gtirb : sig
  module rec Proto : sig
    module rec IR : sig
      type t = {
        uuid:bytes;
        modules:Imported'modules.Module.Gtirb.Proto.Module.t list;
        aux_data:(string * Imported'modules.AuxData.Gtirb.Proto.AuxData.t option) list;
        version:int;
        cfg:Imported'modules.CFG.Gtirb.Proto.CFG.t option;
      }
      val make: ?uuid:bytes -> ?modules:Imported'modules.Module.Gtirb.Proto.Module.t list -> ?aux_data:(string * Imported'modules.AuxData.Gtirb.Proto.AuxData.t option) list -> ?version:int -> ?cfg:Imported'modules.CFG.Gtirb.Proto.CFG.t -> unit -> t
      (** Helper function to generate a message using default values *)

      val to_proto: t -> Runtime'.Writer.t
      (** Serialize the message to binary format *)

      val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from binary format *)

      val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
      (** Serialize to Json (compatible with Yojson.Basic.t) *)

      val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from Json (compatible with Yojson.Basic.t) *)

      val name: unit -> string
      (** Fully qualified protobuf name of this message *)

      (**/**)
      type make_t = ?uuid:bytes -> ?modules:Imported'modules.Module.Gtirb.Proto.Module.t list -> ?aux_data:(string * Imported'modules.AuxData.Gtirb.Proto.AuxData.t option) list -> ?version:int -> ?cfg:Imported'modules.CFG.Gtirb.Proto.CFG.t -> unit -> t
      val merge: t -> t -> t
      val to_proto': Runtime'.Writer.t -> t -> unit
      val from_proto_exn: Runtime'.Reader.t -> t
      val from_json_exn: Runtime'.Json.t -> t
      (**/**)
    end

  end
end = struct
  module rec Proto : sig
    module rec IR : sig
      type t = {
        uuid:bytes;
        modules:Imported'modules.Module.Gtirb.Proto.Module.t list;
        aux_data:(string * Imported'modules.AuxData.Gtirb.Proto.AuxData.t option) list;
        version:int;
        cfg:Imported'modules.CFG.Gtirb.Proto.CFG.t option;
      }
      val make: ?uuid:bytes -> ?modules:Imported'modules.Module.Gtirb.Proto.Module.t list -> ?aux_data:(string * Imported'modules.AuxData.Gtirb.Proto.AuxData.t option) list -> ?version:int -> ?cfg:Imported'modules.CFG.Gtirb.Proto.CFG.t -> unit -> t
      (** Helper function to generate a message using default values *)

      val to_proto: t -> Runtime'.Writer.t
      (** Serialize the message to binary format *)

      val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from binary format *)

      val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
      (** Serialize to Json (compatible with Yojson.Basic.t) *)

      val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from Json (compatible with Yojson.Basic.t) *)

      val name: unit -> string
      (** Fully qualified protobuf name of this message *)

      (**/**)
      type make_t = ?uuid:bytes -> ?modules:Imported'modules.Module.Gtirb.Proto.Module.t list -> ?aux_data:(string * Imported'modules.AuxData.Gtirb.Proto.AuxData.t option) list -> ?version:int -> ?cfg:Imported'modules.CFG.Gtirb.Proto.CFG.t -> unit -> t
      val merge: t -> t -> t
      val to_proto': Runtime'.Writer.t -> t -> unit
      val from_proto_exn: Runtime'.Reader.t -> t
      val from_json_exn: Runtime'.Json.t -> t
      (**/**)
    end

  end = struct
    module rec IR : sig
      type t = {
        uuid:bytes;
        modules:Imported'modules.Module.Gtirb.Proto.Module.t list;
        aux_data:(string * Imported'modules.AuxData.Gtirb.Proto.AuxData.t option) list;
        version:int;
        cfg:Imported'modules.CFG.Gtirb.Proto.CFG.t option;
      }
      val make: ?uuid:bytes -> ?modules:Imported'modules.Module.Gtirb.Proto.Module.t list -> ?aux_data:(string * Imported'modules.AuxData.Gtirb.Proto.AuxData.t option) list -> ?version:int -> ?cfg:Imported'modules.CFG.Gtirb.Proto.CFG.t -> unit -> t
      (** Helper function to generate a message using default values *)

      val to_proto: t -> Runtime'.Writer.t
      (** Serialize the message to binary format *)

      val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from binary format *)

      val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
      (** Serialize to Json (compatible with Yojson.Basic.t) *)

      val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from Json (compatible with Yojson.Basic.t) *)

      val name: unit -> string
      (** Fully qualified protobuf name of this message *)

      (**/**)
      type make_t = ?uuid:bytes -> ?modules:Imported'modules.Module.Gtirb.Proto.Module.t list -> ?aux_data:(string * Imported'modules.AuxData.Gtirb.Proto.AuxData.t option) list -> ?version:int -> ?cfg:Imported'modules.CFG.Gtirb.Proto.CFG.t -> unit -> t
      val merge: t -> t -> t
      val to_proto': Runtime'.Writer.t -> t -> unit
      val from_proto_exn: Runtime'.Reader.t -> t
      val from_json_exn: Runtime'.Json.t -> t
      (**/**)
    end = struct
      module This'_ = IR
      let name () = ".gtirb.proto.IR"
      type t = {
        uuid:bytes;
        modules:Imported'modules.Module.Gtirb.Proto.Module.t list;
        aux_data:(string * Imported'modules.AuxData.Gtirb.Proto.AuxData.t option) list;
        version:int;
        cfg:Imported'modules.CFG.Gtirb.Proto.CFG.t option;
      }
      type make_t = ?uuid:bytes -> ?modules:Imported'modules.Module.Gtirb.Proto.Module.t list -> ?aux_data:(string * Imported'modules.AuxData.Gtirb.Proto.AuxData.t option) list -> ?version:int -> ?cfg:Imported'modules.CFG.Gtirb.Proto.CFG.t -> unit -> t
      let make ?(uuid = (Bytes.of_string {||})) ?(modules = []) ?(aux_data = []) ?(version = 0) ?cfg () = { uuid; modules; aux_data; version; cfg }
      let merge =
      let merge_uuid = Runtime'.Merge.merge Runtime'.Spec.( basic ((1, "uuid", "uuid"), bytes, ((Bytes.of_string {||}))) ) in
      let merge_modules = Runtime'.Merge.merge Runtime'.Spec.( repeated ((3, "modules", "modules"), (message (module Imported'modules.Module.Gtirb.Proto.Module)), not_packed) ) in
      let merge_aux_data = Runtime'.Merge.merge Runtime'.Spec.( map ((5, "aux_data", "auxData"), (string, basic_opt ((2, "value", "value"), (message (module Imported'modules.AuxData.Gtirb.Proto.AuxData))))) ) in
      let merge_version = Runtime'.Merge.merge Runtime'.Spec.( basic ((6, "version", "version"), uint32_int, (0)) ) in
      let merge_cfg = Runtime'.Merge.merge Runtime'.Spec.( basic_opt ((7, "cfg", "cfg"), (message (module Imported'modules.CFG.Gtirb.Proto.CFG))) ) in
      fun t1 t2 -> {
      	uuid = (merge_uuid t1.uuid t2.uuid);
      	modules = (merge_modules t1.modules t2.modules);
      	aux_data = (merge_aux_data t1.aux_data t2.aux_data);
      	version = (merge_version t1.version t2.version);
      	cfg = (merge_cfg t1.cfg t2.cfg);
       }
      let spec () = Runtime'.Spec.( basic ((1, "uuid", "uuid"), bytes, ((Bytes.of_string {||}))) ^:: repeated ((3, "modules", "modules"), (message (module Imported'modules.Module.Gtirb.Proto.Module)), not_packed) ^:: map ((5, "aux_data", "auxData"), (string, basic_opt ((2, "value", "value"), (message (module Imported'modules.AuxData.Gtirb.Proto.AuxData))))) ^:: basic ((6, "version", "version"), uint32_int, (0)) ^:: basic_opt ((7, "cfg", "cfg"), (message (module Imported'modules.CFG.Gtirb.Proto.CFG))) ^:: nil )
      let to_proto' =
        let serialize = Runtime'.apply_lazy (fun () -> Runtime'.Serialize.serialize (spec ())) in
        fun writer { uuid; modules; aux_data; version; cfg } -> serialize writer uuid modules aux_data version cfg

      let to_proto t = let writer = Runtime'.Writer.init () in to_proto' writer t; writer
      let from_proto_exn =
        let constructor uuid modules aux_data version cfg = { uuid; modules; aux_data; version; cfg } in
        Runtime'.apply_lazy (fun () -> Runtime'.Deserialize.deserialize (spec ()) constructor)
      let from_proto writer = Runtime'.Result.catch (fun () -> from_proto_exn writer)
      let to_json options =
        let serialize = Runtime'.Serialize_json.serialize ~message_name:(name ()) (spec ()) options in
        fun { uuid; modules; aux_data; version; cfg } -> serialize uuid modules aux_data version cfg
      let from_json_exn =
        let constructor uuid modules aux_data version cfg = { uuid; modules; aux_data; version; cfg } in
        Runtime'.apply_lazy (fun () -> Runtime'.Deserialize_json.deserialize ~message_name:(name ()) (spec ()) constructor)
      let from_json json = Runtime'.Result.catch (fun () -> from_json_exn json)
    end

  end
end

