(********************************************************)
(*           AUTOGENERATED FILE - DO NOT EDIT!          *)
(********************************************************)
(* Generated by: ocaml-protoc-plugin                    *)
(* https://github.com/andersfugmann/ocaml-protoc-plugin *)
(********************************************************)
(*
  Source: Module.proto
  Syntax: proto3
  Parameters:
    debug=false
    annot=''
    opens=[]
    int64_as_int=true
    int32_as_int=true
    fixed_as_int=false
    singleton_record=false
    prefix_output_with_package=false
*)
[@@@ocaml.alert "-protobuf"] (* Disable deprecation warnings for protobuf*)
(**/**)
module Runtime' = Ocaml_protoc_plugin [@@warning "-33"]
module Imported'modules = struct
  module AuxData = AuxData
  module ProxyBlock = ProxyBlock
  module Section = Section
  module Symbol = Symbol
end
(**/**)
module rec Gtirb : sig
  module rec Proto : sig
    module rec FileFormat : sig
      type t =
        | Format_Undefined
        | COFF
        | ELF
        | PE
        | IdaProDb32
        | IdaProDb64
        | XCOFF
        | MACHO
        | RAW

      val name: unit -> string
      (** Fully qualified protobuf name of this enum *)

      (**/**)
      val to_int: t -> int
      val from_int: int -> t Runtime'.Result.t
      val from_int_exn: int -> t
      val to_string: t -> string
      val from_string_exn: string -> t
      (**/**)
    end

    and ISA : sig
      type t =
        | ISA_Undefined
        | IA32
        | PPC32
        | X64
        | ARM
        | ValidButUnsupported
        | PPC64
        | ARM64
        | MIPS32
        | MIPS64

      val name: unit -> string
      (** Fully qualified protobuf name of this enum *)

      (**/**)
      val to_int: t -> int
      val from_int: int -> t Runtime'.Result.t
      val from_int_exn: int -> t
      val to_string: t -> string
      val from_string_exn: string -> t
      (**/**)
    end

    and ByteOrder : sig
      type t =
        | ByteOrder_Undefined
        | BigEndian
        | LittleEndian

      val name: unit -> string
      (** Fully qualified protobuf name of this enum *)

      (**/**)
      val to_int: t -> int
      val from_int: int -> t Runtime'.Result.t
      val from_int_exn: int -> t
      val to_string: t -> string
      val from_string_exn: string -> t
      (**/**)
    end

    and Module : sig
      type t = {
        uuid:bytes;
        binary_path:string;
        preferred_addr:int;
        rebase_delta:int;
        file_format:FileFormat.t;
        isa:ISA.t;
        name:string;
        symbols:Imported'modules.Symbol.Gtirb.Proto.Symbol.t list;
        sections:Imported'modules.Section.Gtirb.Proto.Section.t list;
        proxies:Imported'modules.ProxyBlock.Gtirb.Proto.ProxyBlock.t list;
        aux_data:(string * Imported'modules.AuxData.Gtirb.Proto.AuxData.t option) list;
        entry_point:bytes;
        byte_order:ByteOrder.t;
      }
      val make: ?uuid:bytes -> ?binary_path:string -> ?preferred_addr:int -> ?rebase_delta:int -> ?file_format:FileFormat.t -> ?isa:ISA.t -> ?name:string -> ?symbols:Imported'modules.Symbol.Gtirb.Proto.Symbol.t list -> ?sections:Imported'modules.Section.Gtirb.Proto.Section.t list -> ?proxies:Imported'modules.ProxyBlock.Gtirb.Proto.ProxyBlock.t list -> ?aux_data:(string * Imported'modules.AuxData.Gtirb.Proto.AuxData.t option) list -> ?entry_point:bytes -> ?byte_order:ByteOrder.t -> unit -> t
      (** Helper function to generate a message using default values *)

      val to_proto: t -> Runtime'.Writer.t
      (** Serialize the message to binary format *)

      val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from binary format *)

      val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
      (** Serialize to Json (compatible with Yojson.Basic.t) *)

      val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from Json (compatible with Yojson.Basic.t) *)

      val name: unit -> string
      (** Fully qualified protobuf name of this message *)

      (**/**)
      type make_t = ?uuid:bytes -> ?binary_path:string -> ?preferred_addr:int -> ?rebase_delta:int -> ?file_format:FileFormat.t -> ?isa:ISA.t -> ?name:string -> ?symbols:Imported'modules.Symbol.Gtirb.Proto.Symbol.t list -> ?sections:Imported'modules.Section.Gtirb.Proto.Section.t list -> ?proxies:Imported'modules.ProxyBlock.Gtirb.Proto.ProxyBlock.t list -> ?aux_data:(string * Imported'modules.AuxData.Gtirb.Proto.AuxData.t option) list -> ?entry_point:bytes -> ?byte_order:ByteOrder.t -> unit -> t
      val merge: t -> t -> t
      val to_proto': Runtime'.Writer.t -> t -> unit
      val from_proto_exn: Runtime'.Reader.t -> t
      val from_json_exn: Runtime'.Json.t -> t
      (**/**)
    end

  end
end = struct
  module rec Proto : sig
    module rec FileFormat : sig
      type t =
        | Format_Undefined
        | COFF
        | ELF
        | PE
        | IdaProDb32
        | IdaProDb64
        | XCOFF
        | MACHO
        | RAW

      val name: unit -> string
      (** Fully qualified protobuf name of this enum *)

      (**/**)
      val to_int: t -> int
      val from_int: int -> t Runtime'.Result.t
      val from_int_exn: int -> t
      val to_string: t -> string
      val from_string_exn: string -> t
      (**/**)
    end

    and ISA : sig
      type t =
        | ISA_Undefined
        | IA32
        | PPC32
        | X64
        | ARM
        | ValidButUnsupported
        | PPC64
        | ARM64
        | MIPS32
        | MIPS64

      val name: unit -> string
      (** Fully qualified protobuf name of this enum *)

      (**/**)
      val to_int: t -> int
      val from_int: int -> t Runtime'.Result.t
      val from_int_exn: int -> t
      val to_string: t -> string
      val from_string_exn: string -> t
      (**/**)
    end

    and ByteOrder : sig
      type t =
        | ByteOrder_Undefined
        | BigEndian
        | LittleEndian

      val name: unit -> string
      (** Fully qualified protobuf name of this enum *)

      (**/**)
      val to_int: t -> int
      val from_int: int -> t Runtime'.Result.t
      val from_int_exn: int -> t
      val to_string: t -> string
      val from_string_exn: string -> t
      (**/**)
    end

    and Module : sig
      type t = {
        uuid:bytes;
        binary_path:string;
        preferred_addr:int;
        rebase_delta:int;
        file_format:FileFormat.t;
        isa:ISA.t;
        name:string;
        symbols:Imported'modules.Symbol.Gtirb.Proto.Symbol.t list;
        sections:Imported'modules.Section.Gtirb.Proto.Section.t list;
        proxies:Imported'modules.ProxyBlock.Gtirb.Proto.ProxyBlock.t list;
        aux_data:(string * Imported'modules.AuxData.Gtirb.Proto.AuxData.t option) list;
        entry_point:bytes;
        byte_order:ByteOrder.t;
      }
      val make: ?uuid:bytes -> ?binary_path:string -> ?preferred_addr:int -> ?rebase_delta:int -> ?file_format:FileFormat.t -> ?isa:ISA.t -> ?name:string -> ?symbols:Imported'modules.Symbol.Gtirb.Proto.Symbol.t list -> ?sections:Imported'modules.Section.Gtirb.Proto.Section.t list -> ?proxies:Imported'modules.ProxyBlock.Gtirb.Proto.ProxyBlock.t list -> ?aux_data:(string * Imported'modules.AuxData.Gtirb.Proto.AuxData.t option) list -> ?entry_point:bytes -> ?byte_order:ByteOrder.t -> unit -> t
      (** Helper function to generate a message using default values *)

      val to_proto: t -> Runtime'.Writer.t
      (** Serialize the message to binary format *)

      val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from binary format *)

      val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
      (** Serialize to Json (compatible with Yojson.Basic.t) *)

      val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from Json (compatible with Yojson.Basic.t) *)

      val name: unit -> string
      (** Fully qualified protobuf name of this message *)

      (**/**)
      type make_t = ?uuid:bytes -> ?binary_path:string -> ?preferred_addr:int -> ?rebase_delta:int -> ?file_format:FileFormat.t -> ?isa:ISA.t -> ?name:string -> ?symbols:Imported'modules.Symbol.Gtirb.Proto.Symbol.t list -> ?sections:Imported'modules.Section.Gtirb.Proto.Section.t list -> ?proxies:Imported'modules.ProxyBlock.Gtirb.Proto.ProxyBlock.t list -> ?aux_data:(string * Imported'modules.AuxData.Gtirb.Proto.AuxData.t option) list -> ?entry_point:bytes -> ?byte_order:ByteOrder.t -> unit -> t
      val merge: t -> t -> t
      val to_proto': Runtime'.Writer.t -> t -> unit
      val from_proto_exn: Runtime'.Reader.t -> t
      val from_json_exn: Runtime'.Json.t -> t
      (**/**)
    end

  end = struct
    module rec FileFormat : sig
      type t =
        | Format_Undefined
        | COFF
        | ELF
        | PE
        | IdaProDb32
        | IdaProDb64
        | XCOFF
        | MACHO
        | RAW

      val name: unit -> string
      (** Fully qualified protobuf name of this enum *)

      (**/**)
      val to_int: t -> int
      val from_int: int -> t Runtime'.Result.t
      val from_int_exn: int -> t
      val to_string: t -> string
      val from_string_exn: string -> t
      (**/**)
    end = struct
      module This'_ = FileFormat
      type t =
        | Format_Undefined
        | COFF
        | ELF
        | PE
        | IdaProDb32
        | IdaProDb64
        | XCOFF
        | MACHO
        | RAW

      let name () = ".gtirb.proto.FileFormat"
      let to_int = function
        | Format_Undefined -> 0
        | COFF -> 1
        | ELF -> 2
        | PE -> 3
        | IdaProDb32 -> 4
        | IdaProDb64 -> 5
        | XCOFF -> 6
        | MACHO -> 7
        | RAW -> 8
      let from_int_exn = function
        | 0 -> Format_Undefined
        | 1 -> COFF
        | 2 -> ELF
        | 3 -> PE
        | 4 -> IdaProDb32
        | 5 -> IdaProDb64
        | 6 -> XCOFF
        | 7 -> MACHO
        | 8 -> RAW
        | n -> Runtime'.Result.raise (`Unknown_enum_value n)
      let from_int e = Runtime'.Result.catch (fun () -> from_int_exn e)
      let to_string = function
        | Format_Undefined -> "Format_Undefined"
        | COFF -> "COFF"
        | ELF -> "ELF"
        | PE -> "PE"
        | IdaProDb32 -> "IdaProDb32"
        | IdaProDb64 -> "IdaProDb64"
        | XCOFF -> "XCOFF"
        | MACHO -> "MACHO"
        | RAW -> "RAW"
      let from_string_exn = function
        | "Format_Undefined" -> Format_Undefined
        | "COFF" -> COFF
        | "ELF" -> ELF
        | "PE" -> PE
        | "IdaProDb32" -> IdaProDb32
        | "IdaProDb64" -> IdaProDb64
        | "XCOFF" -> XCOFF
        | "MACHO" -> MACHO
        | "RAW" -> RAW
        | s -> Runtime'.Result.raise (`Unknown_enum_name s)

    end

    and ISA : sig
      type t =
        | ISA_Undefined
        | IA32
        | PPC32
        | X64
        | ARM
        | ValidButUnsupported
        | PPC64
        | ARM64
        | MIPS32
        | MIPS64

      val name: unit -> string
      (** Fully qualified protobuf name of this enum *)

      (**/**)
      val to_int: t -> int
      val from_int: int -> t Runtime'.Result.t
      val from_int_exn: int -> t
      val to_string: t -> string
      val from_string_exn: string -> t
      (**/**)
    end = struct
      module This'_ = ISA
      type t =
        | ISA_Undefined
        | IA32
        | PPC32
        | X64
        | ARM
        | ValidButUnsupported
        | PPC64
        | ARM64
        | MIPS32
        | MIPS64

      let name () = ".gtirb.proto.ISA"
      let to_int = function
        | ISA_Undefined -> 0
        | IA32 -> 1
        | PPC32 -> 2
        | X64 -> 3
        | ARM -> 4
        | ValidButUnsupported -> 5
        | PPC64 -> 6
        | ARM64 -> 7
        | MIPS32 -> 8
        | MIPS64 -> 9
      let from_int_exn = function
        | 0 -> ISA_Undefined
        | 1 -> IA32
        | 2 -> PPC32
        | 3 -> X64
        | 4 -> ARM
        | 5 -> ValidButUnsupported
        | 6 -> PPC64
        | 7 -> ARM64
        | 8 -> MIPS32
        | 9 -> MIPS64
        | n -> Runtime'.Result.raise (`Unknown_enum_value n)
      let from_int e = Runtime'.Result.catch (fun () -> from_int_exn e)
      let to_string = function
        | ISA_Undefined -> "ISA_Undefined"
        | IA32 -> "IA32"
        | PPC32 -> "PPC32"
        | X64 -> "X64"
        | ARM -> "ARM"
        | ValidButUnsupported -> "ValidButUnsupported"
        | PPC64 -> "PPC64"
        | ARM64 -> "ARM64"
        | MIPS32 -> "MIPS32"
        | MIPS64 -> "MIPS64"
      let from_string_exn = function
        | "ISA_Undefined" -> ISA_Undefined
        | "IA32" -> IA32
        | "PPC32" -> PPC32
        | "X64" -> X64
        | "ARM" -> ARM
        | "ValidButUnsupported" -> ValidButUnsupported
        | "PPC64" -> PPC64
        | "ARM64" -> ARM64
        | "MIPS32" -> MIPS32
        | "MIPS64" -> MIPS64
        | s -> Runtime'.Result.raise (`Unknown_enum_name s)

    end

    and ByteOrder : sig
      type t =
        | ByteOrder_Undefined
        | BigEndian
        | LittleEndian

      val name: unit -> string
      (** Fully qualified protobuf name of this enum *)

      (**/**)
      val to_int: t -> int
      val from_int: int -> t Runtime'.Result.t
      val from_int_exn: int -> t
      val to_string: t -> string
      val from_string_exn: string -> t
      (**/**)
    end = struct
      module This'_ = ByteOrder
      type t =
        | ByteOrder_Undefined
        | BigEndian
        | LittleEndian

      let name () = ".gtirb.proto.ByteOrder"
      let to_int = function
        | ByteOrder_Undefined -> 0
        | BigEndian -> 1
        | LittleEndian -> 2
      let from_int_exn = function
        | 0 -> ByteOrder_Undefined
        | 1 -> BigEndian
        | 2 -> LittleEndian
        | n -> Runtime'.Result.raise (`Unknown_enum_value n)
      let from_int e = Runtime'.Result.catch (fun () -> from_int_exn e)
      let to_string = function
        | ByteOrder_Undefined -> "ByteOrder_Undefined"
        | BigEndian -> "BigEndian"
        | LittleEndian -> "LittleEndian"
      let from_string_exn = function
        | "ByteOrder_Undefined" -> ByteOrder_Undefined
        | "BigEndian" -> BigEndian
        | "LittleEndian" -> LittleEndian
        | s -> Runtime'.Result.raise (`Unknown_enum_name s)

    end

    and Module : sig
      type t = {
        uuid:bytes;
        binary_path:string;
        preferred_addr:int;
        rebase_delta:int;
        file_format:FileFormat.t;
        isa:ISA.t;
        name:string;
        symbols:Imported'modules.Symbol.Gtirb.Proto.Symbol.t list;
        sections:Imported'modules.Section.Gtirb.Proto.Section.t list;
        proxies:Imported'modules.ProxyBlock.Gtirb.Proto.ProxyBlock.t list;
        aux_data:(string * Imported'modules.AuxData.Gtirb.Proto.AuxData.t option) list;
        entry_point:bytes;
        byte_order:ByteOrder.t;
      }
      val make: ?uuid:bytes -> ?binary_path:string -> ?preferred_addr:int -> ?rebase_delta:int -> ?file_format:FileFormat.t -> ?isa:ISA.t -> ?name:string -> ?symbols:Imported'modules.Symbol.Gtirb.Proto.Symbol.t list -> ?sections:Imported'modules.Section.Gtirb.Proto.Section.t list -> ?proxies:Imported'modules.ProxyBlock.Gtirb.Proto.ProxyBlock.t list -> ?aux_data:(string * Imported'modules.AuxData.Gtirb.Proto.AuxData.t option) list -> ?entry_point:bytes -> ?byte_order:ByteOrder.t -> unit -> t
      (** Helper function to generate a message using default values *)

      val to_proto: t -> Runtime'.Writer.t
      (** Serialize the message to binary format *)

      val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from binary format *)

      val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
      (** Serialize to Json (compatible with Yojson.Basic.t) *)

      val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from Json (compatible with Yojson.Basic.t) *)

      val name: unit -> string
      (** Fully qualified protobuf name of this message *)

      (**/**)
      type make_t = ?uuid:bytes -> ?binary_path:string -> ?preferred_addr:int -> ?rebase_delta:int -> ?file_format:FileFormat.t -> ?isa:ISA.t -> ?name:string -> ?symbols:Imported'modules.Symbol.Gtirb.Proto.Symbol.t list -> ?sections:Imported'modules.Section.Gtirb.Proto.Section.t list -> ?proxies:Imported'modules.ProxyBlock.Gtirb.Proto.ProxyBlock.t list -> ?aux_data:(string * Imported'modules.AuxData.Gtirb.Proto.AuxData.t option) list -> ?entry_point:bytes -> ?byte_order:ByteOrder.t -> unit -> t
      val merge: t -> t -> t
      val to_proto': Runtime'.Writer.t -> t -> unit
      val from_proto_exn: Runtime'.Reader.t -> t
      val from_json_exn: Runtime'.Json.t -> t
      (**/**)
    end = struct
      module This'_ = Module
      let name () = ".gtirb.proto.Module"
      type t = {
        uuid:bytes;
        binary_path:string;
        preferred_addr:int;
        rebase_delta:int;
        file_format:FileFormat.t;
        isa:ISA.t;
        name:string;
        symbols:Imported'modules.Symbol.Gtirb.Proto.Symbol.t list;
        sections:Imported'modules.Section.Gtirb.Proto.Section.t list;
        proxies:Imported'modules.ProxyBlock.Gtirb.Proto.ProxyBlock.t list;
        aux_data:(string * Imported'modules.AuxData.Gtirb.Proto.AuxData.t option) list;
        entry_point:bytes;
        byte_order:ByteOrder.t;
      }
      type make_t = ?uuid:bytes -> ?binary_path:string -> ?preferred_addr:int -> ?rebase_delta:int -> ?file_format:FileFormat.t -> ?isa:ISA.t -> ?name:string -> ?symbols:Imported'modules.Symbol.Gtirb.Proto.Symbol.t list -> ?sections:Imported'modules.Section.Gtirb.Proto.Section.t list -> ?proxies:Imported'modules.ProxyBlock.Gtirb.Proto.ProxyBlock.t list -> ?aux_data:(string * Imported'modules.AuxData.Gtirb.Proto.AuxData.t option) list -> ?entry_point:bytes -> ?byte_order:ByteOrder.t -> unit -> t
      let make ?(uuid = (Bytes.of_string {||})) ?(binary_path = {||}) ?(preferred_addr = 0) ?(rebase_delta = 0) ?(file_format = FileFormat.from_int_exn 0) ?(isa = ISA.from_int_exn 0) ?(name = {||}) ?(symbols = []) ?(sections = []) ?(proxies = []) ?(aux_data = []) ?(entry_point = (Bytes.of_string {||})) ?(byte_order = ByteOrder.from_int_exn 0) () = { uuid; binary_path; preferred_addr; rebase_delta; file_format; isa; name; symbols; sections; proxies; aux_data; entry_point; byte_order }
      let merge =
      let merge_uuid = Runtime'.Merge.merge Runtime'.Spec.( basic ((1, "uuid", "uuid"), bytes, ((Bytes.of_string {||}))) ) in
      let merge_binary_path = Runtime'.Merge.merge Runtime'.Spec.( basic ((2, "binary_path", "binaryPath"), string, ({||})) ) in
      let merge_preferred_addr = Runtime'.Merge.merge Runtime'.Spec.( basic ((3, "preferred_addr", "preferredAddr"), uint64_int, (0)) ) in
      let merge_rebase_delta = Runtime'.Merge.merge Runtime'.Spec.( basic ((4, "rebase_delta", "rebaseDelta"), int64_int, (0)) ) in
      let merge_file_format = Runtime'.Merge.merge Runtime'.Spec.( basic ((5, "file_format", "fileFormat"), (enum (module FileFormat)), (FileFormat.from_int_exn 0)) ) in
      let merge_isa = Runtime'.Merge.merge Runtime'.Spec.( basic ((6, "isa", "isa"), (enum (module ISA)), (ISA.from_int_exn 0)) ) in
      let merge_name = Runtime'.Merge.merge Runtime'.Spec.( basic ((7, "name", "name"), string, ({||})) ) in
      let merge_symbols = Runtime'.Merge.merge Runtime'.Spec.( repeated ((9, "symbols", "symbols"), (message (module Imported'modules.Symbol.Gtirb.Proto.Symbol)), not_packed) ) in
      let merge_sections = Runtime'.Merge.merge Runtime'.Spec.( repeated ((12, "sections", "sections"), (message (module Imported'modules.Section.Gtirb.Proto.Section)), not_packed) ) in
      let merge_proxies = Runtime'.Merge.merge Runtime'.Spec.( repeated ((16, "proxies", "proxies"), (message (module Imported'modules.ProxyBlock.Gtirb.Proto.ProxyBlock)), not_packed) ) in
      let merge_aux_data = Runtime'.Merge.merge Runtime'.Spec.( map ((17, "aux_data", "auxData"), (string, basic_opt ((2, "value", "value"), (message (module Imported'modules.AuxData.Gtirb.Proto.AuxData))))) ) in
      let merge_entry_point = Runtime'.Merge.merge Runtime'.Spec.( basic ((18, "entry_point", "entryPoint"), bytes, ((Bytes.of_string {||}))) ) in
      let merge_byte_order = Runtime'.Merge.merge Runtime'.Spec.( basic ((19, "byte_order", "byteOrder"), (enum (module ByteOrder)), (ByteOrder.from_int_exn 0)) ) in
      fun t1 t2 -> {
      	uuid = (merge_uuid t1.uuid t2.uuid);
      	binary_path = (merge_binary_path t1.binary_path t2.binary_path);
      	preferred_addr = (merge_preferred_addr t1.preferred_addr t2.preferred_addr);
      	rebase_delta = (merge_rebase_delta t1.rebase_delta t2.rebase_delta);
      	file_format = (merge_file_format t1.file_format t2.file_format);
      	isa = (merge_isa t1.isa t2.isa);
      	name = (merge_name t1.name t2.name);
      	symbols = (merge_symbols t1.symbols t2.symbols);
      	sections = (merge_sections t1.sections t2.sections);
      	proxies = (merge_proxies t1.proxies t2.proxies);
      	aux_data = (merge_aux_data t1.aux_data t2.aux_data);
      	entry_point = (merge_entry_point t1.entry_point t2.entry_point);
      	byte_order = (merge_byte_order t1.byte_order t2.byte_order);
       }
      let spec () = Runtime'.Spec.( basic ((1, "uuid", "uuid"), bytes, ((Bytes.of_string {||}))) ^:: basic ((2, "binary_path", "binaryPath"), string, ({||})) ^:: basic ((3, "preferred_addr", "preferredAddr"), uint64_int, (0)) ^:: basic ((4, "rebase_delta", "rebaseDelta"), int64_int, (0)) ^:: basic ((5, "file_format", "fileFormat"), (enum (module FileFormat)), (FileFormat.from_int_exn 0)) ^:: basic ((6, "isa", "isa"), (enum (module ISA)), (ISA.from_int_exn 0)) ^:: basic ((7, "name", "name"), string, ({||})) ^:: repeated ((9, "symbols", "symbols"), (message (module Imported'modules.Symbol.Gtirb.Proto.Symbol)), not_packed) ^:: repeated ((12, "sections", "sections"), (message (module Imported'modules.Section.Gtirb.Proto.Section)), not_packed) ^:: repeated ((16, "proxies", "proxies"), (message (module Imported'modules.ProxyBlock.Gtirb.Proto.ProxyBlock)), not_packed) ^:: map ((17, "aux_data", "auxData"), (string, basic_opt ((2, "value", "value"), (message (module Imported'modules.AuxData.Gtirb.Proto.AuxData))))) ^:: basic ((18, "entry_point", "entryPoint"), bytes, ((Bytes.of_string {||}))) ^:: basic ((19, "byte_order", "byteOrder"), (enum (module ByteOrder)), (ByteOrder.from_int_exn 0)) ^:: nil )
      let to_proto' =
        let serialize = Runtime'.apply_lazy (fun () -> Runtime'.Serialize.serialize (spec ())) in
        fun writer { uuid; binary_path; preferred_addr; rebase_delta; file_format; isa; name; symbols; sections; proxies; aux_data; entry_point; byte_order } -> serialize writer uuid binary_path preferred_addr rebase_delta file_format isa name symbols sections proxies aux_data entry_point byte_order

      let to_proto t = let writer = Runtime'.Writer.init () in to_proto' writer t; writer
      let from_proto_exn =
        let constructor uuid binary_path preferred_addr rebase_delta file_format isa name symbols sections proxies aux_data entry_point byte_order = { uuid; binary_path; preferred_addr; rebase_delta; file_format; isa; name; symbols; sections; proxies; aux_data; entry_point; byte_order } in
        Runtime'.apply_lazy (fun () -> Runtime'.Deserialize.deserialize (spec ()) constructor)
      let from_proto writer = Runtime'.Result.catch (fun () -> from_proto_exn writer)
      let to_json options =
        let serialize = Runtime'.Serialize_json.serialize ~message_name:(name ()) (spec ()) options in
        fun { uuid; binary_path; preferred_addr; rebase_delta; file_format; isa; name; symbols; sections; proxies; aux_data; entry_point; byte_order } -> serialize uuid binary_path preferred_addr rebase_delta file_format isa name symbols sections proxies aux_data entry_point byte_order
      let from_json_exn =
        let constructor uuid binary_path preferred_addr rebase_delta file_format isa name symbols sections proxies aux_data entry_point byte_order = { uuid; binary_path; preferred_addr; rebase_delta; file_format; isa; name; symbols; sections; proxies; aux_data; entry_point; byte_order } in
        Runtime'.apply_lazy (fun () -> Runtime'.Deserialize_json.deserialize ~message_name:(name ()) (spec ()) constructor)
      let from_json json = Runtime'.Result.catch (fun () -> from_json_exn json)
    end

  end
end

