(********************************************************)
(*           AUTOGENERATED FILE - DO NOT EDIT!          *)
(********************************************************)
(* Generated by: ocaml-protoc-plugin                    *)
(* https://github.com/andersfugmann/ocaml-protoc-plugin *)
(********************************************************)
(*
  Source: Section.proto
  Syntax: proto3
  Parameters:
    debug=false
    annot=''
    opens=[]
    int64_as_int=true
    int32_as_int=true
    fixed_as_int=false
    singleton_record=false
    prefix_output_with_package=false
*)
[@@@ocaml.alert "-protobuf"] (* Disable deprecation warnings for protobuf*)
(**/**)
module Runtime' = Ocaml_protoc_plugin [@@warning "-33"]
module Imported'modules = struct
  module ByteInterval = ByteInterval
end
(**/**)
module rec Gtirb : sig
  module rec Proto : sig
    module rec SectionFlag : sig
      type t =
        | Section_Undefined
        | Readable
        | Writable
        | Executable
        | Loaded
        | Initialized
        | ThreadLocal

      val name: unit -> string
      (** Fully qualified protobuf name of this enum *)

      (**/**)
      val to_int: t -> int
      val from_int: int -> t Runtime'.Result.t
      val from_int_exn: int -> t
      val to_string: t -> string
      val from_string_exn: string -> t
      (**/**)
    end

    and Section : sig
      type t = {
        uuid:bytes;
        name:string;
        byte_intervals:Imported'modules.ByteInterval.Gtirb.Proto.ByteInterval.t list;
        section_flags:SectionFlag.t list;
      }
      val make: ?uuid:bytes -> ?name:string -> ?byte_intervals:Imported'modules.ByteInterval.Gtirb.Proto.ByteInterval.t list -> ?section_flags:SectionFlag.t list -> unit -> t
      (** Helper function to generate a message using default values *)

      val to_proto: t -> Runtime'.Writer.t
      (** Serialize the message to binary format *)

      val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from binary format *)

      val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
      (** Serialize to Json (compatible with Yojson.Basic.t) *)

      val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from Json (compatible with Yojson.Basic.t) *)

      val name: unit -> string
      (** Fully qualified protobuf name of this message *)

      (**/**)
      type make_t = ?uuid:bytes -> ?name:string -> ?byte_intervals:Imported'modules.ByteInterval.Gtirb.Proto.ByteInterval.t list -> ?section_flags:SectionFlag.t list -> unit -> t
      val merge: t -> t -> t
      val to_proto': Runtime'.Writer.t -> t -> unit
      val from_proto_exn: Runtime'.Reader.t -> t
      val from_json_exn: Runtime'.Json.t -> t
      (**/**)
    end

  end
end = struct
  module rec Proto : sig
    module rec SectionFlag : sig
      type t =
        | Section_Undefined
        | Readable
        | Writable
        | Executable
        | Loaded
        | Initialized
        | ThreadLocal

      val name: unit -> string
      (** Fully qualified protobuf name of this enum *)

      (**/**)
      val to_int: t -> int
      val from_int: int -> t Runtime'.Result.t
      val from_int_exn: int -> t
      val to_string: t -> string
      val from_string_exn: string -> t
      (**/**)
    end

    and Section : sig
      type t = {
        uuid:bytes;
        name:string;
        byte_intervals:Imported'modules.ByteInterval.Gtirb.Proto.ByteInterval.t list;
        section_flags:SectionFlag.t list;
      }
      val make: ?uuid:bytes -> ?name:string -> ?byte_intervals:Imported'modules.ByteInterval.Gtirb.Proto.ByteInterval.t list -> ?section_flags:SectionFlag.t list -> unit -> t
      (** Helper function to generate a message using default values *)

      val to_proto: t -> Runtime'.Writer.t
      (** Serialize the message to binary format *)

      val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from binary format *)

      val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
      (** Serialize to Json (compatible with Yojson.Basic.t) *)

      val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from Json (compatible with Yojson.Basic.t) *)

      val name: unit -> string
      (** Fully qualified protobuf name of this message *)

      (**/**)
      type make_t = ?uuid:bytes -> ?name:string -> ?byte_intervals:Imported'modules.ByteInterval.Gtirb.Proto.ByteInterval.t list -> ?section_flags:SectionFlag.t list -> unit -> t
      val merge: t -> t -> t
      val to_proto': Runtime'.Writer.t -> t -> unit
      val from_proto_exn: Runtime'.Reader.t -> t
      val from_json_exn: Runtime'.Json.t -> t
      (**/**)
    end

  end = struct
    module rec SectionFlag : sig
      type t =
        | Section_Undefined
        | Readable
        | Writable
        | Executable
        | Loaded
        | Initialized
        | ThreadLocal

      val name: unit -> string
      (** Fully qualified protobuf name of this enum *)

      (**/**)
      val to_int: t -> int
      val from_int: int -> t Runtime'.Result.t
      val from_int_exn: int -> t
      val to_string: t -> string
      val from_string_exn: string -> t
      (**/**)
    end = struct
      module This'_ = SectionFlag
      type t =
        | Section_Undefined
        | Readable
        | Writable
        | Executable
        | Loaded
        | Initialized
        | ThreadLocal

      let name () = ".gtirb.proto.SectionFlag"
      let to_int = function
        | Section_Undefined -> 0
        | Readable -> 1
        | Writable -> 2
        | Executable -> 3
        | Loaded -> 4
        | Initialized -> 5
        | ThreadLocal -> 6
      let from_int_exn = function
        | 0 -> Section_Undefined
        | 1 -> Readable
        | 2 -> Writable
        | 3 -> Executable
        | 4 -> Loaded
        | 5 -> Initialized
        | 6 -> ThreadLocal
        | n -> Runtime'.Result.raise (`Unknown_enum_value n)
      let from_int e = Runtime'.Result.catch (fun () -> from_int_exn e)
      let to_string = function
        | Section_Undefined -> "Section_Undefined"
        | Readable -> "Readable"
        | Writable -> "Writable"
        | Executable -> "Executable"
        | Loaded -> "Loaded"
        | Initialized -> "Initialized"
        | ThreadLocal -> "ThreadLocal"
      let from_string_exn = function
        | "Section_Undefined" -> Section_Undefined
        | "Readable" -> Readable
        | "Writable" -> Writable
        | "Executable" -> Executable
        | "Loaded" -> Loaded
        | "Initialized" -> Initialized
        | "ThreadLocal" -> ThreadLocal
        | s -> Runtime'.Result.raise (`Unknown_enum_name s)

    end

    and Section : sig
      type t = {
        uuid:bytes;
        name:string;
        byte_intervals:Imported'modules.ByteInterval.Gtirb.Proto.ByteInterval.t list;
        section_flags:SectionFlag.t list;
      }
      val make: ?uuid:bytes -> ?name:string -> ?byte_intervals:Imported'modules.ByteInterval.Gtirb.Proto.ByteInterval.t list -> ?section_flags:SectionFlag.t list -> unit -> t
      (** Helper function to generate a message using default values *)

      val to_proto: t -> Runtime'.Writer.t
      (** Serialize the message to binary format *)

      val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from binary format *)

      val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
      (** Serialize to Json (compatible with Yojson.Basic.t) *)

      val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from Json (compatible with Yojson.Basic.t) *)

      val name: unit -> string
      (** Fully qualified protobuf name of this message *)

      (**/**)
      type make_t = ?uuid:bytes -> ?name:string -> ?byte_intervals:Imported'modules.ByteInterval.Gtirb.Proto.ByteInterval.t list -> ?section_flags:SectionFlag.t list -> unit -> t
      val merge: t -> t -> t
      val to_proto': Runtime'.Writer.t -> t -> unit
      val from_proto_exn: Runtime'.Reader.t -> t
      val from_json_exn: Runtime'.Json.t -> t
      (**/**)
    end = struct
      module This'_ = Section
      let name () = ".gtirb.proto.Section"
      type t = {
        uuid:bytes;
        name:string;
        byte_intervals:Imported'modules.ByteInterval.Gtirb.Proto.ByteInterval.t list;
        section_flags:SectionFlag.t list;
      }
      type make_t = ?uuid:bytes -> ?name:string -> ?byte_intervals:Imported'modules.ByteInterval.Gtirb.Proto.ByteInterval.t list -> ?section_flags:SectionFlag.t list -> unit -> t
      let make ?(uuid = (Bytes.of_string {||})) ?(name = {||}) ?(byte_intervals = []) ?(section_flags = []) () = { uuid; name; byte_intervals; section_flags }
      let merge =
      let merge_uuid = Runtime'.Merge.merge Runtime'.Spec.( basic ((1, "uuid", "uuid"), bytes, ((Bytes.of_string {||}))) ) in
      let merge_name = Runtime'.Merge.merge Runtime'.Spec.( basic ((2, "name", "name"), string, ({||})) ) in
      let merge_byte_intervals = Runtime'.Merge.merge Runtime'.Spec.( repeated ((5, "byte_intervals", "byteIntervals"), (message (module Imported'modules.ByteInterval.Gtirb.Proto.ByteInterval)), not_packed) ) in
      let merge_section_flags = Runtime'.Merge.merge Runtime'.Spec.( repeated ((6, "section_flags", "sectionFlags"), (enum (module SectionFlag)), packed) ) in
      fun t1 t2 -> {
      	uuid = (merge_uuid t1.uuid t2.uuid);
      	name = (merge_name t1.name t2.name);
      	byte_intervals = (merge_byte_intervals t1.byte_intervals t2.byte_intervals);
      	section_flags = (merge_section_flags t1.section_flags t2.section_flags);
       }
      let spec () = Runtime'.Spec.( basic ((1, "uuid", "uuid"), bytes, ((Bytes.of_string {||}))) ^:: basic ((2, "name", "name"), string, ({||})) ^:: repeated ((5, "byte_intervals", "byteIntervals"), (message (module Imported'modules.ByteInterval.Gtirb.Proto.ByteInterval)), not_packed) ^:: repeated ((6, "section_flags", "sectionFlags"), (enum (module SectionFlag)), packed) ^:: nil )
      let to_proto' =
        let serialize = Runtime'.apply_lazy (fun () -> Runtime'.Serialize.serialize (spec ())) in
        fun writer { uuid; name; byte_intervals; section_flags } -> serialize writer uuid name byte_intervals section_flags

      let to_proto t = let writer = Runtime'.Writer.init () in to_proto' writer t; writer
      let from_proto_exn =
        let constructor uuid name byte_intervals section_flags = { uuid; name; byte_intervals; section_flags } in
        Runtime'.apply_lazy (fun () -> Runtime'.Deserialize.deserialize (spec ()) constructor)
      let from_proto writer = Runtime'.Result.catch (fun () -> from_proto_exn writer)
      let to_json options =
        let serialize = Runtime'.Serialize_json.serialize ~message_name:(name ()) (spec ()) options in
        fun { uuid; name; byte_intervals; section_flags } -> serialize uuid name byte_intervals section_flags
      let from_json_exn =
        let constructor uuid name byte_intervals section_flags = { uuid; name; byte_intervals; section_flags } in
        Runtime'.apply_lazy (fun () -> Runtime'.Deserialize_json.deserialize ~message_name:(name ()) (spec ()) constructor)
      let from_json json = Runtime'.Result.catch (fun () -> from_json_exn json)
    end

  end
end

