(********************************************************)
(*           AUTOGENERATED FILE - DO NOT EDIT!          *)
(********************************************************)
(* Generated by: ocaml-protoc-plugin                    *)
(* https://github.com/andersfugmann/ocaml-protoc-plugin *)
(********************************************************)
(*
  Source: SymbolicExpression.proto
  Syntax: proto3
  Parameters:
    debug=false
    annot=''
    opens=[]
    int64_as_int=true
    int32_as_int=true
    fixed_as_int=false
    singleton_record=false
    prefix_output_with_package=false
*)
[@@@ocaml.alert "-protobuf"] (* Disable deprecation warnings for protobuf*)
(**/**)
module Runtime' = Ocaml_protoc_plugin [@@warning "-33"]
module Imported'modules = struct
end
(**/**)
module rec Gtirb : sig
  module rec Proto : sig

    (**
{%html:
<p>NOTE:
We do not generalize or otherwise unify relocation attributes across
architectures and instead prefer an explicit mapping of attributes names
to the labels used in the assembly of each architecture.</p>
%}
    *)
    module rec SymAttribute : sig
      type t =
        | GOT
        (**
{%html:
<p>ELF</p>
%}
        *)

        | GOTPC
        | GOTOFF
        | GOTREL
        | PLT
        | PLTOFF
        | PCREL
        | SECREL
        | TLS
        | TLSGD
        | TLSLD
        | TLSLDM
        | TLSCALL
        | TLSDESC
        | TPREL
        | TPOFF
        | DTPREL
        | DTPOFF
        | NTPOFF
        | DTPMOD
        | PAGE
        | PAGEOFF
        | CALL
        | LO
        | HI
        | HIGHER
        | HIGHEST
        | GOTNTPOFF
        (**
{%html:
<p>X86</p>
%}
        *)

        | INDNTPOFF
        | G0
        (**
{%html:
<p>ARM</p>
%}
        *)

        | G1
        | G2
        | G3
        | UPPER16
        | LOWER16
        | LO12
        | LO15
        | LO14
        | HI12
        | HI21
        | S
        | PG
        | NC
        | ABS
        | PREL
        | PREL31
        | TARGET1
        | TARGET2
        | SBREL
        | TLSLDO
        | HI16
        (**
{%html:
<p>MIPS</p>
%}
        *)

        | LO16
        | GPREL
        | DISP
        | OFST
        | H
        (**
{%html:
<p>PPC</p>
%}
        *)

        | L
        | HA
        | HIGH
        | HIGHA
        | HIGHERA
        | HIGHESTA
        | TOCBASE
        | TOC
        | NOTOC

      val name: unit -> string
      (** Fully qualified protobuf name of this enum *)

      (**/**)
      val to_int: t -> int
      val from_int: int -> t Runtime'.Result.t
      val from_int_exn: int -> t
      val to_string: t -> string
      val from_string_exn: string -> t
      (**/**)
    end

    and SymStackConst : sig
      type t = {
        offset:int;
        symbol_uuid:bytes;
      }
      val make: ?offset:int -> ?symbol_uuid:bytes -> unit -> t
      (** Helper function to generate a message using default values *)

      val to_proto: t -> Runtime'.Writer.t
      (** Serialize the message to binary format *)

      val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from binary format *)

      val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
      (** Serialize to Json (compatible with Yojson.Basic.t) *)

      val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from Json (compatible with Yojson.Basic.t) *)

      val name: unit -> string
      (** Fully qualified protobuf name of this message *)

      (**/**)
      type make_t = ?offset:int -> ?symbol_uuid:bytes -> unit -> t
      val merge: t -> t -> t
      val to_proto': Runtime'.Writer.t -> t -> unit
      val from_proto_exn: Runtime'.Reader.t -> t
      val from_json_exn: Runtime'.Json.t -> t
      (**/**)
    end

    and SymAddrConst : sig
      type t = {
        offset:int;
        symbol_uuid:bytes;
      }
      val make: ?offset:int -> ?symbol_uuid:bytes -> unit -> t
      (** Helper function to generate a message using default values *)

      val to_proto: t -> Runtime'.Writer.t
      (** Serialize the message to binary format *)

      val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from binary format *)

      val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
      (** Serialize to Json (compatible with Yojson.Basic.t) *)

      val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from Json (compatible with Yojson.Basic.t) *)

      val name: unit -> string
      (** Fully qualified protobuf name of this message *)

      (**/**)
      type make_t = ?offset:int -> ?symbol_uuid:bytes -> unit -> t
      val merge: t -> t -> t
      val to_proto': Runtime'.Writer.t -> t -> unit
      val from_proto_exn: Runtime'.Reader.t -> t
      val from_json_exn: Runtime'.Json.t -> t
      (**/**)
    end

    and SymAddrAddr : sig
      type t = {
        scale:int;
        offset:int;
        symbol1_uuid:bytes;
        symbol2_uuid:bytes;
      }
      val make: ?scale:int -> ?offset:int -> ?symbol1_uuid:bytes -> ?symbol2_uuid:bytes -> unit -> t
      (** Helper function to generate a message using default values *)

      val to_proto: t -> Runtime'.Writer.t
      (** Serialize the message to binary format *)

      val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from binary format *)

      val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
      (** Serialize to Json (compatible with Yojson.Basic.t) *)

      val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from Json (compatible with Yojson.Basic.t) *)

      val name: unit -> string
      (** Fully qualified protobuf name of this message *)

      (**/**)
      type make_t = ?scale:int -> ?offset:int -> ?symbol1_uuid:bytes -> ?symbol2_uuid:bytes -> unit -> t
      val merge: t -> t -> t
      val to_proto': Runtime'.Writer.t -> t -> unit
      val from_proto_exn: Runtime'.Reader.t -> t
      val from_json_exn: Runtime'.Json.t -> t
      (**/**)
    end

    and SymbolicExpression : sig
      type t = {
        value:[ `not_set | `Addr_const of SymAddrConst.t | `Addr_addr of SymAddrAddr.t ];
        attribute_flags:SymAttribute.t list;
      }
      val make: ?value:[ `not_set | `Addr_const of SymAddrConst.t | `Addr_addr of SymAddrAddr.t ] -> ?attribute_flags:SymAttribute.t list -> unit -> t
      (** Helper function to generate a message using default values *)

      val to_proto: t -> Runtime'.Writer.t
      (** Serialize the message to binary format *)

      val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from binary format *)

      val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
      (** Serialize to Json (compatible with Yojson.Basic.t) *)

      val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from Json (compatible with Yojson.Basic.t) *)

      val name: unit -> string
      (** Fully qualified protobuf name of this message *)

      (**/**)
      type make_t = ?value:[ `not_set | `Addr_const of SymAddrConst.t | `Addr_addr of SymAddrAddr.t ] -> ?attribute_flags:SymAttribute.t list -> unit -> t
      val merge: t -> t -> t
      val to_proto': Runtime'.Writer.t -> t -> unit
      val from_proto_exn: Runtime'.Reader.t -> t
      val from_json_exn: Runtime'.Json.t -> t
      (**/**)
    end

  end
end = struct
  module rec Proto : sig

    (**
{%html:
<p>NOTE:
We do not generalize or otherwise unify relocation attributes across
architectures and instead prefer an explicit mapping of attributes names
to the labels used in the assembly of each architecture.</p>
%}
    *)
    module rec SymAttribute : sig
      type t =
        | GOT
        (**
{%html:
<p>ELF</p>
%}
        *)

        | GOTPC
        | GOTOFF
        | GOTREL
        | PLT
        | PLTOFF
        | PCREL
        | SECREL
        | TLS
        | TLSGD
        | TLSLD
        | TLSLDM
        | TLSCALL
        | TLSDESC
        | TPREL
        | TPOFF
        | DTPREL
        | DTPOFF
        | NTPOFF
        | DTPMOD
        | PAGE
        | PAGEOFF
        | CALL
        | LO
        | HI
        | HIGHER
        | HIGHEST
        | GOTNTPOFF
        (**
{%html:
<p>X86</p>
%}
        *)

        | INDNTPOFF
        | G0
        (**
{%html:
<p>ARM</p>
%}
        *)

        | G1
        | G2
        | G3
        | UPPER16
        | LOWER16
        | LO12
        | LO15
        | LO14
        | HI12
        | HI21
        | S
        | PG
        | NC
        | ABS
        | PREL
        | PREL31
        | TARGET1
        | TARGET2
        | SBREL
        | TLSLDO
        | HI16
        (**
{%html:
<p>MIPS</p>
%}
        *)

        | LO16
        | GPREL
        | DISP
        | OFST
        | H
        (**
{%html:
<p>PPC</p>
%}
        *)

        | L
        | HA
        | HIGH
        | HIGHA
        | HIGHERA
        | HIGHESTA
        | TOCBASE
        | TOC
        | NOTOC

      val name: unit -> string
      (** Fully qualified protobuf name of this enum *)

      (**/**)
      val to_int: t -> int
      val from_int: int -> t Runtime'.Result.t
      val from_int_exn: int -> t
      val to_string: t -> string
      val from_string_exn: string -> t
      (**/**)
    end

    and SymStackConst : sig
      type t = {
        offset:int;
        symbol_uuid:bytes;
      }
      val make: ?offset:int -> ?symbol_uuid:bytes -> unit -> t
      (** Helper function to generate a message using default values *)

      val to_proto: t -> Runtime'.Writer.t
      (** Serialize the message to binary format *)

      val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from binary format *)

      val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
      (** Serialize to Json (compatible with Yojson.Basic.t) *)

      val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from Json (compatible with Yojson.Basic.t) *)

      val name: unit -> string
      (** Fully qualified protobuf name of this message *)

      (**/**)
      type make_t = ?offset:int -> ?symbol_uuid:bytes -> unit -> t
      val merge: t -> t -> t
      val to_proto': Runtime'.Writer.t -> t -> unit
      val from_proto_exn: Runtime'.Reader.t -> t
      val from_json_exn: Runtime'.Json.t -> t
      (**/**)
    end

    and SymAddrConst : sig
      type t = {
        offset:int;
        symbol_uuid:bytes;
      }
      val make: ?offset:int -> ?symbol_uuid:bytes -> unit -> t
      (** Helper function to generate a message using default values *)

      val to_proto: t -> Runtime'.Writer.t
      (** Serialize the message to binary format *)

      val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from binary format *)

      val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
      (** Serialize to Json (compatible with Yojson.Basic.t) *)

      val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from Json (compatible with Yojson.Basic.t) *)

      val name: unit -> string
      (** Fully qualified protobuf name of this message *)

      (**/**)
      type make_t = ?offset:int -> ?symbol_uuid:bytes -> unit -> t
      val merge: t -> t -> t
      val to_proto': Runtime'.Writer.t -> t -> unit
      val from_proto_exn: Runtime'.Reader.t -> t
      val from_json_exn: Runtime'.Json.t -> t
      (**/**)
    end

    and SymAddrAddr : sig
      type t = {
        scale:int;
        offset:int;
        symbol1_uuid:bytes;
        symbol2_uuid:bytes;
      }
      val make: ?scale:int -> ?offset:int -> ?symbol1_uuid:bytes -> ?symbol2_uuid:bytes -> unit -> t
      (** Helper function to generate a message using default values *)

      val to_proto: t -> Runtime'.Writer.t
      (** Serialize the message to binary format *)

      val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from binary format *)

      val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
      (** Serialize to Json (compatible with Yojson.Basic.t) *)

      val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from Json (compatible with Yojson.Basic.t) *)

      val name: unit -> string
      (** Fully qualified protobuf name of this message *)

      (**/**)
      type make_t = ?scale:int -> ?offset:int -> ?symbol1_uuid:bytes -> ?symbol2_uuid:bytes -> unit -> t
      val merge: t -> t -> t
      val to_proto': Runtime'.Writer.t -> t -> unit
      val from_proto_exn: Runtime'.Reader.t -> t
      val from_json_exn: Runtime'.Json.t -> t
      (**/**)
    end

    and SymbolicExpression : sig
      type t = {
        value:[ `not_set | `Addr_const of SymAddrConst.t | `Addr_addr of SymAddrAddr.t ];
        attribute_flags:SymAttribute.t list;
      }
      val make: ?value:[ `not_set | `Addr_const of SymAddrConst.t | `Addr_addr of SymAddrAddr.t ] -> ?attribute_flags:SymAttribute.t list -> unit -> t
      (** Helper function to generate a message using default values *)

      val to_proto: t -> Runtime'.Writer.t
      (** Serialize the message to binary format *)

      val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from binary format *)

      val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
      (** Serialize to Json (compatible with Yojson.Basic.t) *)

      val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from Json (compatible with Yojson.Basic.t) *)

      val name: unit -> string
      (** Fully qualified protobuf name of this message *)

      (**/**)
      type make_t = ?value:[ `not_set | `Addr_const of SymAddrConst.t | `Addr_addr of SymAddrAddr.t ] -> ?attribute_flags:SymAttribute.t list -> unit -> t
      val merge: t -> t -> t
      val to_proto': Runtime'.Writer.t -> t -> unit
      val from_proto_exn: Runtime'.Reader.t -> t
      val from_json_exn: Runtime'.Json.t -> t
      (**/**)
    end

  end = struct
    module rec SymAttribute : sig
      type t =
        | GOT
        (**
{%html:
<p>ELF</p>
%}
        *)

        | GOTPC
        | GOTOFF
        | GOTREL
        | PLT
        | PLTOFF
        | PCREL
        | SECREL
        | TLS
        | TLSGD
        | TLSLD
        | TLSLDM
        | TLSCALL
        | TLSDESC
        | TPREL
        | TPOFF
        | DTPREL
        | DTPOFF
        | NTPOFF
        | DTPMOD
        | PAGE
        | PAGEOFF
        | CALL
        | LO
        | HI
        | HIGHER
        | HIGHEST
        | GOTNTPOFF
        (**
{%html:
<p>X86</p>
%}
        *)

        | INDNTPOFF
        | G0
        (**
{%html:
<p>ARM</p>
%}
        *)

        | G1
        | G2
        | G3
        | UPPER16
        | LOWER16
        | LO12
        | LO15
        | LO14
        | HI12
        | HI21
        | S
        | PG
        | NC
        | ABS
        | PREL
        | PREL31
        | TARGET1
        | TARGET2
        | SBREL
        | TLSLDO
        | HI16
        (**
{%html:
<p>MIPS</p>
%}
        *)

        | LO16
        | GPREL
        | DISP
        | OFST
        | H
        (**
{%html:
<p>PPC</p>
%}
        *)

        | L
        | HA
        | HIGH
        | HIGHA
        | HIGHERA
        | HIGHESTA
        | TOCBASE
        | TOC
        | NOTOC

      val name: unit -> string
      (** Fully qualified protobuf name of this enum *)

      (**/**)
      val to_int: t -> int
      val from_int: int -> t Runtime'.Result.t
      val from_int_exn: int -> t
      val to_string: t -> string
      val from_string_exn: string -> t
      (**/**)
    end = struct
      module This'_ = SymAttribute
      type t =
        | GOT
        (**
{%html:
<p>ELF</p>
%}
        *)

        | GOTPC
        | GOTOFF
        | GOTREL
        | PLT
        | PLTOFF
        | PCREL
        | SECREL
        | TLS
        | TLSGD
        | TLSLD
        | TLSLDM
        | TLSCALL
        | TLSDESC
        | TPREL
        | TPOFF
        | DTPREL
        | DTPOFF
        | NTPOFF
        | DTPMOD
        | PAGE
        | PAGEOFF
        | CALL
        | LO
        | HI
        | HIGHER
        | HIGHEST
        | GOTNTPOFF
        (**
{%html:
<p>X86</p>
%}
        *)

        | INDNTPOFF
        | G0
        (**
{%html:
<p>ARM</p>
%}
        *)

        | G1
        | G2
        | G3
        | UPPER16
        | LOWER16
        | LO12
        | LO15
        | LO14
        | HI12
        | HI21
        | S
        | PG
        | NC
        | ABS
        | PREL
        | PREL31
        | TARGET1
        | TARGET2
        | SBREL
        | TLSLDO
        | HI16
        (**
{%html:
<p>MIPS</p>
%}
        *)

        | LO16
        | GPREL
        | DISP
        | OFST
        | H
        (**
{%html:
<p>PPC</p>
%}
        *)

        | L
        | HA
        | HIGH
        | HIGHA
        | HIGHERA
        | HIGHESTA
        | TOCBASE
        | TOC
        | NOTOC

      let name () = ".gtirb.proto.SymAttribute"
      let to_int = function
        | GOT -> 0
        | GOTPC -> 1
        | GOTOFF -> 2
        | GOTREL -> 3
        | PLT -> 4
        | PLTOFF -> 5
        | PCREL -> 6
        | SECREL -> 7
        | TLS -> 8
        | TLSGD -> 9
        | TLSLD -> 10
        | TLSLDM -> 11
        | TLSCALL -> 12
        | TLSDESC -> 13
        | TPREL -> 14
        | TPOFF -> 15
        | DTPREL -> 16
        | DTPOFF -> 17
        | NTPOFF -> 18
        | DTPMOD -> 19
        | PAGE -> 20
        | PAGEOFF -> 21
        | CALL -> 22
        | LO -> 23
        | HI -> 24
        | HIGHER -> 25
        | HIGHEST -> 26
        | GOTNTPOFF -> 1000
        | INDNTPOFF -> 1001
        | G0 -> 2001
        | G1 -> 2002
        | G2 -> 2003
        | G3 -> 2004
        | UPPER16 -> 2005
        | LOWER16 -> 2006
        | LO12 -> 2007
        | LO15 -> 2008
        | LO14 -> 2009
        | HI12 -> 2010
        | HI21 -> 2011
        | S -> 2012
        | PG -> 2013
        | NC -> 2014
        | ABS -> 2015
        | PREL -> 2016
        | PREL31 -> 2017
        | TARGET1 -> 2018
        | TARGET2 -> 2019
        | SBREL -> 2020
        | TLSLDO -> 2021
        | HI16 -> 3000
        | LO16 -> 3001
        | GPREL -> 3002
        | DISP -> 3003
        | OFST -> 3004
        | H -> 4000
        | L -> 4001
        | HA -> 4002
        | HIGH -> 4003
        | HIGHA -> 4004
        | HIGHERA -> 4005
        | HIGHESTA -> 4006
        | TOCBASE -> 4007
        | TOC -> 4008
        | NOTOC -> 4009
      let from_int_exn = function
        | 0 -> GOT
        | 1 -> GOTPC
        | 2 -> GOTOFF
        | 3 -> GOTREL
        | 4 -> PLT
        | 5 -> PLTOFF
        | 6 -> PCREL
        | 7 -> SECREL
        | 8 -> TLS
        | 9 -> TLSGD
        | 10 -> TLSLD
        | 11 -> TLSLDM
        | 12 -> TLSCALL
        | 13 -> TLSDESC
        | 14 -> TPREL
        | 15 -> TPOFF
        | 16 -> DTPREL
        | 17 -> DTPOFF
        | 18 -> NTPOFF
        | 19 -> DTPMOD
        | 20 -> PAGE
        | 21 -> PAGEOFF
        | 22 -> CALL
        | 23 -> LO
        | 24 -> HI
        | 25 -> HIGHER
        | 26 -> HIGHEST
        | 1000 -> GOTNTPOFF
        | 1001 -> INDNTPOFF
        | 2001 -> G0
        | 2002 -> G1
        | 2003 -> G2
        | 2004 -> G3
        | 2005 -> UPPER16
        | 2006 -> LOWER16
        | 2007 -> LO12
        | 2008 -> LO15
        | 2009 -> LO14
        | 2010 -> HI12
        | 2011 -> HI21
        | 2012 -> S
        | 2013 -> PG
        | 2014 -> NC
        | 2015 -> ABS
        | 2016 -> PREL
        | 2017 -> PREL31
        | 2018 -> TARGET1
        | 2019 -> TARGET2
        | 2020 -> SBREL
        | 2021 -> TLSLDO
        | 3000 -> HI16
        | 3001 -> LO16
        | 3002 -> GPREL
        | 3003 -> DISP
        | 3004 -> OFST
        | 4000 -> H
        | 4001 -> L
        | 4002 -> HA
        | 4003 -> HIGH
        | 4004 -> HIGHA
        | 4005 -> HIGHERA
        | 4006 -> HIGHESTA
        | 4007 -> TOCBASE
        | 4008 -> TOC
        | 4009 -> NOTOC
        | n -> Runtime'.Result.raise (`Unknown_enum_value n)
      let from_int e = Runtime'.Result.catch (fun () -> from_int_exn e)
      let to_string = function
        | GOT -> "GOT"
        | GOTPC -> "GOTPC"
        | GOTOFF -> "GOTOFF"
        | GOTREL -> "GOTREL"
        | PLT -> "PLT"
        | PLTOFF -> "PLTOFF"
        | PCREL -> "PCREL"
        | SECREL -> "SECREL"
        | TLS -> "TLS"
        | TLSGD -> "TLSGD"
        | TLSLD -> "TLSLD"
        | TLSLDM -> "TLSLDM"
        | TLSCALL -> "TLSCALL"
        | TLSDESC -> "TLSDESC"
        | TPREL -> "TPREL"
        | TPOFF -> "TPOFF"
        | DTPREL -> "DTPREL"
        | DTPOFF -> "DTPOFF"
        | NTPOFF -> "NTPOFF"
        | DTPMOD -> "DTPMOD"
        | PAGE -> "PAGE"
        | PAGEOFF -> "PAGEOFF"
        | CALL -> "CALL"
        | LO -> "LO"
        | HI -> "HI"
        | HIGHER -> "HIGHER"
        | HIGHEST -> "HIGHEST"
        | GOTNTPOFF -> "GOTNTPOFF"
        | INDNTPOFF -> "INDNTPOFF"
        | G0 -> "G0"
        | G1 -> "G1"
        | G2 -> "G2"
        | G3 -> "G3"
        | UPPER16 -> "UPPER16"
        | LOWER16 -> "LOWER16"
        | LO12 -> "LO12"
        | LO15 -> "LO15"
        | LO14 -> "LO14"
        | HI12 -> "HI12"
        | HI21 -> "HI21"
        | S -> "S"
        | PG -> "PG"
        | NC -> "NC"
        | ABS -> "ABS"
        | PREL -> "PREL"
        | PREL31 -> "PREL31"
        | TARGET1 -> "TARGET1"
        | TARGET2 -> "TARGET2"
        | SBREL -> "SBREL"
        | TLSLDO -> "TLSLDO"
        | HI16 -> "HI16"
        | LO16 -> "LO16"
        | GPREL -> "GPREL"
        | DISP -> "DISP"
        | OFST -> "OFST"
        | H -> "H"
        | L -> "L"
        | HA -> "HA"
        | HIGH -> "HIGH"
        | HIGHA -> "HIGHA"
        | HIGHERA -> "HIGHERA"
        | HIGHESTA -> "HIGHESTA"
        | TOCBASE -> "TOCBASE"
        | TOC -> "TOC"
        | NOTOC -> "NOTOC"
      let from_string_exn = function
        | "GOT" -> GOT
        | "GOTPC" -> GOTPC
        | "GOTOFF" -> GOTOFF
        | "GOTREL" -> GOTREL
        | "PLT" -> PLT
        | "PLTOFF" -> PLTOFF
        | "PCREL" -> PCREL
        | "SECREL" -> SECREL
        | "TLS" -> TLS
        | "TLSGD" -> TLSGD
        | "TLSLD" -> TLSLD
        | "TLSLDM" -> TLSLDM
        | "TLSCALL" -> TLSCALL
        | "TLSDESC" -> TLSDESC
        | "TPREL" -> TPREL
        | "TPOFF" -> TPOFF
        | "DTPREL" -> DTPREL
        | "DTPOFF" -> DTPOFF
        | "NTPOFF" -> NTPOFF
        | "DTPMOD" -> DTPMOD
        | "PAGE" -> PAGE
        | "PAGEOFF" -> PAGEOFF
        | "CALL" -> CALL
        | "LO" -> LO
        | "HI" -> HI
        | "HIGHER" -> HIGHER
        | "HIGHEST" -> HIGHEST
        | "GOTNTPOFF" -> GOTNTPOFF
        | "INDNTPOFF" -> INDNTPOFF
        | "G0" -> G0
        | "G1" -> G1
        | "G2" -> G2
        | "G3" -> G3
        | "UPPER16" -> UPPER16
        | "LOWER16" -> LOWER16
        | "LO12" -> LO12
        | "LO15" -> LO15
        | "LO14" -> LO14
        | "HI12" -> HI12
        | "HI21" -> HI21
        | "S" -> S
        | "PG" -> PG
        | "NC" -> NC
        | "ABS" -> ABS
        | "PREL" -> PREL
        | "PREL31" -> PREL31
        | "TARGET1" -> TARGET1
        | "TARGET2" -> TARGET2
        | "SBREL" -> SBREL
        | "TLSLDO" -> TLSLDO
        | "HI16" -> HI16
        | "LO16" -> LO16
        | "GPREL" -> GPREL
        | "DISP" -> DISP
        | "OFST" -> OFST
        | "H" -> H
        | "L" -> L
        | "HA" -> HA
        | "HIGH" -> HIGH
        | "HIGHA" -> HIGHA
        | "HIGHERA" -> HIGHERA
        | "HIGHESTA" -> HIGHESTA
        | "TOCBASE" -> TOCBASE
        | "TOC" -> TOC
        | "NOTOC" -> NOTOC
        | s -> Runtime'.Result.raise (`Unknown_enum_name s)

    end

    and SymStackConst : sig
      type t = {
        offset:int;
        symbol_uuid:bytes;
      }
      val make: ?offset:int -> ?symbol_uuid:bytes -> unit -> t
      (** Helper function to generate a message using default values *)

      val to_proto: t -> Runtime'.Writer.t
      (** Serialize the message to binary format *)

      val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from binary format *)

      val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
      (** Serialize to Json (compatible with Yojson.Basic.t) *)

      val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from Json (compatible with Yojson.Basic.t) *)

      val name: unit -> string
      (** Fully qualified protobuf name of this message *)

      (**/**)
      type make_t = ?offset:int -> ?symbol_uuid:bytes -> unit -> t
      val merge: t -> t -> t
      val to_proto': Runtime'.Writer.t -> t -> unit
      val from_proto_exn: Runtime'.Reader.t -> t
      val from_json_exn: Runtime'.Json.t -> t
      (**/**)
    end = struct
      module This'_ = SymStackConst
      let name () = ".gtirb.proto.SymStackConst"
      type t = {
        offset:int;
        symbol_uuid:bytes;
      }
      type make_t = ?offset:int -> ?symbol_uuid:bytes -> unit -> t
      let make ?(offset = 0) ?(symbol_uuid = (Bytes.of_string {||})) () = { offset; symbol_uuid }
      let merge =
      let merge_offset = Runtime'.Merge.merge Runtime'.Spec.( basic ((1, "offset", "offset"), int32_int, (0)) ) in
      let merge_symbol_uuid = Runtime'.Merge.merge Runtime'.Spec.( basic ((2, "symbol_uuid", "symbolUuid"), bytes, ((Bytes.of_string {||}))) ) in
      fun t1 t2 -> {
      	offset = (merge_offset t1.offset t2.offset);
      	symbol_uuid = (merge_symbol_uuid t1.symbol_uuid t2.symbol_uuid);
       }
      let spec () = Runtime'.Spec.( basic ((1, "offset", "offset"), int32_int, (0)) ^:: basic ((2, "symbol_uuid", "symbolUuid"), bytes, ((Bytes.of_string {||}))) ^:: nil )
      let to_proto' =
        let serialize = Runtime'.apply_lazy (fun () -> Runtime'.Serialize.serialize (spec ())) in
        fun writer { offset; symbol_uuid } -> serialize writer offset symbol_uuid

      let to_proto t = let writer = Runtime'.Writer.init () in to_proto' writer t; writer
      let from_proto_exn =
        let constructor offset symbol_uuid = { offset; symbol_uuid } in
        Runtime'.apply_lazy (fun () -> Runtime'.Deserialize.deserialize (spec ()) constructor)
      let from_proto writer = Runtime'.Result.catch (fun () -> from_proto_exn writer)
      let to_json options =
        let serialize = Runtime'.Serialize_json.serialize ~message_name:(name ()) (spec ()) options in
        fun { offset; symbol_uuid } -> serialize offset symbol_uuid
      let from_json_exn =
        let constructor offset symbol_uuid = { offset; symbol_uuid } in
        Runtime'.apply_lazy (fun () -> Runtime'.Deserialize_json.deserialize ~message_name:(name ()) (spec ()) constructor)
      let from_json json = Runtime'.Result.catch (fun () -> from_json_exn json)
    end

    and SymAddrConst : sig
      type t = {
        offset:int;
        symbol_uuid:bytes;
      }
      val make: ?offset:int -> ?symbol_uuid:bytes -> unit -> t
      (** Helper function to generate a message using default values *)

      val to_proto: t -> Runtime'.Writer.t
      (** Serialize the message to binary format *)

      val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from binary format *)

      val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
      (** Serialize to Json (compatible with Yojson.Basic.t) *)

      val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from Json (compatible with Yojson.Basic.t) *)

      val name: unit -> string
      (** Fully qualified protobuf name of this message *)

      (**/**)
      type make_t = ?offset:int -> ?symbol_uuid:bytes -> unit -> t
      val merge: t -> t -> t
      val to_proto': Runtime'.Writer.t -> t -> unit
      val from_proto_exn: Runtime'.Reader.t -> t
      val from_json_exn: Runtime'.Json.t -> t
      (**/**)
    end = struct
      module This'_ = SymAddrConst
      let name () = ".gtirb.proto.SymAddrConst"
      type t = {
        offset:int;
        symbol_uuid:bytes;
      }
      type make_t = ?offset:int -> ?symbol_uuid:bytes -> unit -> t
      let make ?(offset = 0) ?(symbol_uuid = (Bytes.of_string {||})) () = { offset; symbol_uuid }
      let merge =
      let merge_offset = Runtime'.Merge.merge Runtime'.Spec.( basic ((1, "offset", "offset"), int64_int, (0)) ) in
      let merge_symbol_uuid = Runtime'.Merge.merge Runtime'.Spec.( basic ((2, "symbol_uuid", "symbolUuid"), bytes, ((Bytes.of_string {||}))) ) in
      fun t1 t2 -> {
      	offset = (merge_offset t1.offset t2.offset);
      	symbol_uuid = (merge_symbol_uuid t1.symbol_uuid t2.symbol_uuid);
       }
      let spec () = Runtime'.Spec.( basic ((1, "offset", "offset"), int64_int, (0)) ^:: basic ((2, "symbol_uuid", "symbolUuid"), bytes, ((Bytes.of_string {||}))) ^:: nil )
      let to_proto' =
        let serialize = Runtime'.apply_lazy (fun () -> Runtime'.Serialize.serialize (spec ())) in
        fun writer { offset; symbol_uuid } -> serialize writer offset symbol_uuid

      let to_proto t = let writer = Runtime'.Writer.init () in to_proto' writer t; writer
      let from_proto_exn =
        let constructor offset symbol_uuid = { offset; symbol_uuid } in
        Runtime'.apply_lazy (fun () -> Runtime'.Deserialize.deserialize (spec ()) constructor)
      let from_proto writer = Runtime'.Result.catch (fun () -> from_proto_exn writer)
      let to_json options =
        let serialize = Runtime'.Serialize_json.serialize ~message_name:(name ()) (spec ()) options in
        fun { offset; symbol_uuid } -> serialize offset symbol_uuid
      let from_json_exn =
        let constructor offset symbol_uuid = { offset; symbol_uuid } in
        Runtime'.apply_lazy (fun () -> Runtime'.Deserialize_json.deserialize ~message_name:(name ()) (spec ()) constructor)
      let from_json json = Runtime'.Result.catch (fun () -> from_json_exn json)
    end

    and SymAddrAddr : sig
      type t = {
        scale:int;
        offset:int;
        symbol1_uuid:bytes;
        symbol2_uuid:bytes;
      }
      val make: ?scale:int -> ?offset:int -> ?symbol1_uuid:bytes -> ?symbol2_uuid:bytes -> unit -> t
      (** Helper function to generate a message using default values *)

      val to_proto: t -> Runtime'.Writer.t
      (** Serialize the message to binary format *)

      val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from binary format *)

      val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
      (** Serialize to Json (compatible with Yojson.Basic.t) *)

      val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from Json (compatible with Yojson.Basic.t) *)

      val name: unit -> string
      (** Fully qualified protobuf name of this message *)

      (**/**)
      type make_t = ?scale:int -> ?offset:int -> ?symbol1_uuid:bytes -> ?symbol2_uuid:bytes -> unit -> t
      val merge: t -> t -> t
      val to_proto': Runtime'.Writer.t -> t -> unit
      val from_proto_exn: Runtime'.Reader.t -> t
      val from_json_exn: Runtime'.Json.t -> t
      (**/**)
    end = struct
      module This'_ = SymAddrAddr
      let name () = ".gtirb.proto.SymAddrAddr"
      type t = {
        scale:int;
        offset:int;
        symbol1_uuid:bytes;
        symbol2_uuid:bytes;
      }
      type make_t = ?scale:int -> ?offset:int -> ?symbol1_uuid:bytes -> ?symbol2_uuid:bytes -> unit -> t
      let make ?(scale = 0) ?(offset = 0) ?(symbol1_uuid = (Bytes.of_string {||})) ?(symbol2_uuid = (Bytes.of_string {||})) () = { scale; offset; symbol1_uuid; symbol2_uuid }
      let merge =
      let merge_scale = Runtime'.Merge.merge Runtime'.Spec.( basic ((1, "scale", "scale"), int64_int, (0)) ) in
      let merge_offset = Runtime'.Merge.merge Runtime'.Spec.( basic ((2, "offset", "offset"), int64_int, (0)) ) in
      let merge_symbol1_uuid = Runtime'.Merge.merge Runtime'.Spec.( basic ((3, "symbol1_uuid", "symbol1Uuid"), bytes, ((Bytes.of_string {||}))) ) in
      let merge_symbol2_uuid = Runtime'.Merge.merge Runtime'.Spec.( basic ((4, "symbol2_uuid", "symbol2Uuid"), bytes, ((Bytes.of_string {||}))) ) in
      fun t1 t2 -> {
      	scale = (merge_scale t1.scale t2.scale);
      	offset = (merge_offset t1.offset t2.offset);
      	symbol1_uuid = (merge_symbol1_uuid t1.symbol1_uuid t2.symbol1_uuid);
      	symbol2_uuid = (merge_symbol2_uuid t1.symbol2_uuid t2.symbol2_uuid);
       }
      let spec () = Runtime'.Spec.( basic ((1, "scale", "scale"), int64_int, (0)) ^:: basic ((2, "offset", "offset"), int64_int, (0)) ^:: basic ((3, "symbol1_uuid", "symbol1Uuid"), bytes, ((Bytes.of_string {||}))) ^:: basic ((4, "symbol2_uuid", "symbol2Uuid"), bytes, ((Bytes.of_string {||}))) ^:: nil )
      let to_proto' =
        let serialize = Runtime'.apply_lazy (fun () -> Runtime'.Serialize.serialize (spec ())) in
        fun writer { scale; offset; symbol1_uuid; symbol2_uuid } -> serialize writer scale offset symbol1_uuid symbol2_uuid

      let to_proto t = let writer = Runtime'.Writer.init () in to_proto' writer t; writer
      let from_proto_exn =
        let constructor scale offset symbol1_uuid symbol2_uuid = { scale; offset; symbol1_uuid; symbol2_uuid } in
        Runtime'.apply_lazy (fun () -> Runtime'.Deserialize.deserialize (spec ()) constructor)
      let from_proto writer = Runtime'.Result.catch (fun () -> from_proto_exn writer)
      let to_json options =
        let serialize = Runtime'.Serialize_json.serialize ~message_name:(name ()) (spec ()) options in
        fun { scale; offset; symbol1_uuid; symbol2_uuid } -> serialize scale offset symbol1_uuid symbol2_uuid
      let from_json_exn =
        let constructor scale offset symbol1_uuid symbol2_uuid = { scale; offset; symbol1_uuid; symbol2_uuid } in
        Runtime'.apply_lazy (fun () -> Runtime'.Deserialize_json.deserialize ~message_name:(name ()) (spec ()) constructor)
      let from_json json = Runtime'.Result.catch (fun () -> from_json_exn json)
    end

    and SymbolicExpression : sig
      type t = {
        value:[ `not_set | `Addr_const of SymAddrConst.t | `Addr_addr of SymAddrAddr.t ];
        attribute_flags:SymAttribute.t list;
      }
      val make: ?value:[ `not_set | `Addr_const of SymAddrConst.t | `Addr_addr of SymAddrAddr.t ] -> ?attribute_flags:SymAttribute.t list -> unit -> t
      (** Helper function to generate a message using default values *)

      val to_proto: t -> Runtime'.Writer.t
      (** Serialize the message to binary format *)

      val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from binary format *)

      val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
      (** Serialize to Json (compatible with Yojson.Basic.t) *)

      val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from Json (compatible with Yojson.Basic.t) *)

      val name: unit -> string
      (** Fully qualified protobuf name of this message *)

      (**/**)
      type make_t = ?value:[ `not_set | `Addr_const of SymAddrConst.t | `Addr_addr of SymAddrAddr.t ] -> ?attribute_flags:SymAttribute.t list -> unit -> t
      val merge: t -> t -> t
      val to_proto': Runtime'.Writer.t -> t -> unit
      val from_proto_exn: Runtime'.Reader.t -> t
      val from_json_exn: Runtime'.Json.t -> t
      (**/**)
    end = struct
      module This'_ = SymbolicExpression
      let name () = ".gtirb.proto.SymbolicExpression"
      type t = {
        value:[ `not_set | `Addr_const of SymAddrConst.t | `Addr_addr of SymAddrAddr.t ];
        attribute_flags:SymAttribute.t list;
      }
      type make_t = ?value:[ `not_set | `Addr_const of SymAddrConst.t | `Addr_addr of SymAddrAddr.t ] -> ?attribute_flags:SymAttribute.t list -> unit -> t
      let make ?(value = `not_set) ?(attribute_flags = []) () = { value; attribute_flags }
      let merge =
      let merge_oneof_value__Addr_const = Runtime'.Merge.merge Runtime'.Spec.( basic_req ((0, "", ""), (message (module SymAddrConst))) ) in
      let merge_oneof_value__Addr_addr = Runtime'.Merge.merge Runtime'.Spec.( basic_req ((0, "", ""), (message (module SymAddrAddr))) ) in
      let merge_attribute_flags = Runtime'.Merge.merge Runtime'.Spec.( repeated ((4, "attribute_flags", "attributeFlags"), (enum (module SymAttribute)), packed) ) in
      fun t1 t2 -> {
      	value = (match (t1.value, t2.value) with
      	| (`Addr_const v1, `Addr_const v2) -> `Addr_const (merge_oneof_value__Addr_const v1 v2)
      	| (`Addr_addr v1, `Addr_addr v2) -> `Addr_addr (merge_oneof_value__Addr_addr v1 v2)
      	| (v1, `not_set) -> v1
      	| (_, v2) -> v2);
      	attribute_flags = (merge_attribute_flags t1.attribute_flags t2.attribute_flags);
       }
      let spec () = Runtime'.Spec.( oneof (([ oneof_elem ((2, "addr_const", "addrConst"), (message (module SymAddrConst)), ((fun v -> `Addr_const v), (function `Addr_const v -> v | _ -> raise (Invalid_argument "Cannot destruct given oneof")))); oneof_elem ((3, "addr_addr", "addrAddr"), (message (module SymAddrAddr)), ((fun v -> `Addr_addr v), (function `Addr_addr v -> v | _ -> raise (Invalid_argument "Cannot destruct given oneof")))) ], (function | `not_set -> failwith "Impossible case" | `Addr_const _ -> 0 | `Addr_addr _ -> 1))) ^:: repeated ((4, "attribute_flags", "attributeFlags"), (enum (module SymAttribute)), packed) ^:: nil )
      let to_proto' =
        let serialize = Runtime'.apply_lazy (fun () -> Runtime'.Serialize.serialize (spec ())) in
        fun writer { value; attribute_flags } -> serialize writer value attribute_flags

      let to_proto t = let writer = Runtime'.Writer.init () in to_proto' writer t; writer
      let from_proto_exn =
        let constructor value attribute_flags = { value; attribute_flags } in
        Runtime'.apply_lazy (fun () -> Runtime'.Deserialize.deserialize (spec ()) constructor)
      let from_proto writer = Runtime'.Result.catch (fun () -> from_proto_exn writer)
      let to_json options =
        let serialize = Runtime'.Serialize_json.serialize ~message_name:(name ()) (spec ()) options in
        fun { value; attribute_flags } -> serialize value attribute_flags
      let from_json_exn =
        let constructor value attribute_flags = { value; attribute_flags } in
        Runtime'.apply_lazy (fun () -> Runtime'.Deserialize_json.deserialize ~message_name:(name ()) (spec ()) constructor)
      let from_json json = Runtime'.Result.catch (fun () -> from_json_exn json)
    end

  end
end

