(********************************************************)
(*           AUTOGENERATED FILE - DO NOT EDIT!          *)
(********************************************************)
(* Generated by: ocaml-protoc-plugin                    *)
(* https://github.com/andersfugmann/ocaml-protoc-plugin *)
(********************************************************)
(*
  Source: Symbol.proto
  Syntax: proto3
  Parameters:
    debug=false
    annot=''
    opens=[]
    int64_as_int=true
    int32_as_int=true
    fixed_as_int=false
    singleton_record=false
    prefix_output_with_package=false
*)
[@@@ocaml.alert "-protobuf"] (* Disable deprecation warnings for protobuf*)
(**/**)
module Runtime' = Ocaml_protoc_plugin [@@warning "-33"]
module Imported'modules = struct
end
(**/**)
module rec Gtirb : sig
  module rec Proto : sig
    module rec Symbol : sig
      type t = {
        uuid:bytes;
        optional_payload:[ `not_set | `Value of int | `Referent_uuid of bytes ];
        name:string;
        at_end:bool;
      }
      val make: ?uuid:bytes -> ?optional_payload:[ `not_set | `Value of int | `Referent_uuid of bytes ] -> ?name:string -> ?at_end:bool -> unit -> t
      (** Helper function to generate a message using default values *)

      val to_proto: t -> Runtime'.Writer.t
      (** Serialize the message to binary format *)

      val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from binary format *)

      val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
      (** Serialize to Json (compatible with Yojson.Basic.t) *)

      val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from Json (compatible with Yojson.Basic.t) *)

      val name: unit -> string
      (** Fully qualified protobuf name of this message *)

      (**/**)
      type make_t = ?uuid:bytes -> ?optional_payload:[ `not_set | `Value of int | `Referent_uuid of bytes ] -> ?name:string -> ?at_end:bool -> unit -> t
      val merge: t -> t -> t
      val to_proto': Runtime'.Writer.t -> t -> unit
      val from_proto_exn: Runtime'.Reader.t -> t
      val from_json_exn: Runtime'.Json.t -> t
      (**/**)
    end

  end
end = struct
  module rec Proto : sig
    module rec Symbol : sig
      type t = {
        uuid:bytes;
        optional_payload:[ `not_set | `Value of int | `Referent_uuid of bytes ];
        name:string;
        at_end:bool;
      }
      val make: ?uuid:bytes -> ?optional_payload:[ `not_set | `Value of int | `Referent_uuid of bytes ] -> ?name:string -> ?at_end:bool -> unit -> t
      (** Helper function to generate a message using default values *)

      val to_proto: t -> Runtime'.Writer.t
      (** Serialize the message to binary format *)

      val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from binary format *)

      val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
      (** Serialize to Json (compatible with Yojson.Basic.t) *)

      val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from Json (compatible with Yojson.Basic.t) *)

      val name: unit -> string
      (** Fully qualified protobuf name of this message *)

      (**/**)
      type make_t = ?uuid:bytes -> ?optional_payload:[ `not_set | `Value of int | `Referent_uuid of bytes ] -> ?name:string -> ?at_end:bool -> unit -> t
      val merge: t -> t -> t
      val to_proto': Runtime'.Writer.t -> t -> unit
      val from_proto_exn: Runtime'.Reader.t -> t
      val from_json_exn: Runtime'.Json.t -> t
      (**/**)
    end

  end = struct
    module rec Symbol : sig
      type t = {
        uuid:bytes;
        optional_payload:[ `not_set | `Value of int | `Referent_uuid of bytes ];
        name:string;
        at_end:bool;
      }
      val make: ?uuid:bytes -> ?optional_payload:[ `not_set | `Value of int | `Referent_uuid of bytes ] -> ?name:string -> ?at_end:bool -> unit -> t
      (** Helper function to generate a message using default values *)

      val to_proto: t -> Runtime'.Writer.t
      (** Serialize the message to binary format *)

      val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from binary format *)

      val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
      (** Serialize to Json (compatible with Yojson.Basic.t) *)

      val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from Json (compatible with Yojson.Basic.t) *)

      val name: unit -> string
      (** Fully qualified protobuf name of this message *)

      (**/**)
      type make_t = ?uuid:bytes -> ?optional_payload:[ `not_set | `Value of int | `Referent_uuid of bytes ] -> ?name:string -> ?at_end:bool -> unit -> t
      val merge: t -> t -> t
      val to_proto': Runtime'.Writer.t -> t -> unit
      val from_proto_exn: Runtime'.Reader.t -> t
      val from_json_exn: Runtime'.Json.t -> t
      (**/**)
    end = struct
      module This'_ = Symbol
      let name () = ".gtirb.proto.Symbol"
      type t = {
        uuid:bytes;
        optional_payload:[ `not_set | `Value of int | `Referent_uuid of bytes ];
        name:string;
        at_end:bool;
      }
      type make_t = ?uuid:bytes -> ?optional_payload:[ `not_set | `Value of int | `Referent_uuid of bytes ] -> ?name:string -> ?at_end:bool -> unit -> t
      let make ?(uuid = (Bytes.of_string {||})) ?(optional_payload = `not_set) ?(name = {||}) ?(at_end = false) () = { uuid; optional_payload; name; at_end }
      let merge =
      let merge_uuid = Runtime'.Merge.merge Runtime'.Spec.( basic ((1, "uuid", "uuid"), bytes, ((Bytes.of_string {||}))) ) in
      let merge_oneof_optional_payload__Value = Runtime'.Merge.merge Runtime'.Spec.( basic_req ((0, "", ""), uint64_int) ) in
      let merge_oneof_optional_payload__Referent_uuid = Runtime'.Merge.merge Runtime'.Spec.( basic_req ((0, "", ""), bytes) ) in
      let merge_name = Runtime'.Merge.merge Runtime'.Spec.( basic ((3, "name", "name"), string, ({||})) ) in
      let merge_at_end = Runtime'.Merge.merge Runtime'.Spec.( basic ((6, "at_end", "atEnd"), bool, (false)) ) in
      fun t1 t2 -> {
      	uuid = (merge_uuid t1.uuid t2.uuid);
      	optional_payload = (match (t1.optional_payload, t2.optional_payload) with
      	| (`Value v1, `Value v2) -> `Value (merge_oneof_optional_payload__Value v1 v2)
      	| (`Referent_uuid v1, `Referent_uuid v2) -> `Referent_uuid (merge_oneof_optional_payload__Referent_uuid v1 v2)
      	| (v1, `not_set) -> v1
      	| (_, v2) -> v2);
      	name = (merge_name t1.name t2.name);
      	at_end = (merge_at_end t1.at_end t2.at_end);
       }
      let spec () = Runtime'.Spec.( basic ((1, "uuid", "uuid"), bytes, ((Bytes.of_string {||}))) ^:: oneof (([ oneof_elem ((2, "value", "value"), uint64_int, ((fun v -> `Value v), (function `Value v -> v | _ -> raise (Invalid_argument "Cannot destruct given oneof")))); oneof_elem ((5, "referent_uuid", "referentUuid"), bytes, ((fun v -> `Referent_uuid v), (function `Referent_uuid v -> v | _ -> raise (Invalid_argument "Cannot destruct given oneof")))) ], (function | `not_set -> failwith "Impossible case" | `Value _ -> 0 | `Referent_uuid _ -> 1))) ^:: basic ((3, "name", "name"), string, ({||})) ^:: basic ((6, "at_end", "atEnd"), bool, (false)) ^:: nil )
      let to_proto' =
        let serialize = Runtime'.apply_lazy (fun () -> Runtime'.Serialize.serialize (spec ())) in
        fun writer { uuid; optional_payload; name; at_end } -> serialize writer uuid optional_payload name at_end

      let to_proto t = let writer = Runtime'.Writer.init () in to_proto' writer t; writer
      let from_proto_exn =
        let constructor uuid optional_payload name at_end = { uuid; optional_payload; name; at_end } in
        Runtime'.apply_lazy (fun () -> Runtime'.Deserialize.deserialize (spec ()) constructor)
      let from_proto writer = Runtime'.Result.catch (fun () -> from_proto_exn writer)
      let to_json options =
        let serialize = Runtime'.Serialize_json.serialize ~message_name:(name ()) (spec ()) options in
        fun { uuid; optional_payload; name; at_end } -> serialize uuid optional_payload name at_end
      let from_json_exn =
        let constructor uuid optional_payload name at_end = { uuid; optional_payload; name; at_end } in
        Runtime'.apply_lazy (fun () -> Runtime'.Deserialize_json.deserialize ~message_name:(name ()) (spec ()) constructor)
      let from_json json = Runtime'.Result.catch (fun () -> from_json_exn json)
    end

  end
end

