(library
 (name bincaml_analysis_test)
 (package bincaml)
 (modules test_ide_live test_ssadfg)
 (inline_tests)
 (libraries
  bincaml.loader
  bincaml.ast
  bincaml.transforms
  bincaml.util
  bincaml
  bincaml.analysis
  qcheck-alcotest)
 (preprocess
  (pps ppx_expect)))

(test
 (name analysis_tests)
 (package bincaml)
 (modules
  analysis_tests
  test_wrapped_intervals
  test_irreducible_loops
  test_lattice_collections)
 (preprocess
  (pps ppx_here))
 (libraries
  bincaml.loader
  bincaml.ast
  bincaml.transforms
  bincaml.util
  bincaml
  bincaml.analysis
  alcotest
  qcheck-alcotest
  qcheck-core))
