(library
 (name bincaml_analysis_test)
 (modules ide_live known_bits wrapped_intervals)
 (inline_tests)
 (libraries
  bincaml.loader
  bincaml.ast
  bincaml.transforms
  bincaml.util
  bincaml
  bincaml.analysis
  qcheck-alcotest
  )
 (preprocess
  (pps ppx_expect)))


(test
 (modules analysis_tests test_irreducible_loops lattice_collections)
 (name analysis_tests)
 (libraries
  bincaml.loader
  bincaml.ast
  bincaml.transforms
  bincaml.util
  bincaml
  bincaml.analysis
  alcotest
  qcheck-alcotest
  qcheck-core)
 )

