; checks tree-sitter highlights are valid

(rule
 (deps src/parser.c queries/highlights.scm)
 (alias treesit)
 (enabled_if %{bin-available:tree-sitter})
 (action
  (with-stdin-from
   %{project_root}/examples/cat.il
   (ignore-stdout
    (run tree-sitter highlight)))))

; check that grammar.js is up to date.
; requires `bnfc-treesitter` from pac-nix.

; bnfc tree-sitter backend is only run if the fixed tree-sitter fork is
; detected in the output of bnfc --help. this lets us use upstream
; bnfc for the main ocaml parser.

(rule
 (alias treesit)
 (deps %{project_root}/lib/fe/BasilIR.cf)
 (enabled_if %{read:../lib/fe/has-bnfc-tree-sitter})
 (action
  (progn
   (copy %{deps} basilir.cf)
   (run
    bnfc
    --tree-sitter
    --tree-sitter-word
    LocalIdent
    basilir.cf
    --makefile)
   (run sed -i.bak "s/= grammar/= /" tree-sitter-basilir/grammar.js)
   (diff? grammar.bnfc.js tree-sitter-basilir/grammar.js))))

(rule
 (alias treesit)
 (deps (universe))
 (enabled_if
  (not %{read:../lib/fe/has-bnfc-tree-sitter}))
 (action
  (echo
   "tree-sitter/dune: bnfc tree-sitter generation skipped,"
   "because the installed bnfc doesn't support it.\n")))
