; checks tree-sitter highlights are valid

(rule
 (deps src/parser.c queries/highlights.scm)
 (alias treesit)
 (action
  (with-stdin-from
   %{project_root}/examples/cat.il
   (ignore-stdout
    (run tree-sitter highlight)))))

; check that grammar.js is up to date.
; requires `bnfc-treesitter` from pac-nix.

; bnfc tree-sitter backend is only run if the fixed tree-sitter fork is
; detected in the output of bnfc --help. this lets us use upstream
; bnfc for the main ocaml parser.

(rule
 (alias treesit)
 (deps %{project_root}/lib/fe/BasilIR.cf)
 (action
  (progn
   (copy %{deps} basilir.cf)
   (run
    bnfc
    --tree-sitter
    --tree-sitter-word
    LocalIdent
    basilir.cf
    --makefile
    --outputdir=out/tree-sitter-basilir)
   ; compensate for older bnfc emitting into a subfolder of outputdir
   (with-stdout-to
    grammar.bnfc.js.new
    (bash "shopt -s globstar ; sed 's/= grammar/= /' out/**/grammar.js"))
   (diff? grammar.bnfc.js grammar.bnfc.js.new))))

(rule
 (alias treesit)
 (deps (universe))
 (enabled_if
  (not %{read:../lib/fe/has-bnfc-tree-sitter}))
 (action
  (echo
   "tree-sitter/dune: bnfc tree-sitter generation skipped,"
   "because the installed bnfc doesn't support it.\n")))

(alias
 (name runtest)
 (deps
  (alias treesit))
 (enabled_if
  (and %{read:../lib/fe/has-bnfc-tree-sitter} %{bin-available:tree-sitter})))
