// File generated by the BNF Converter (bnfc 2.9.6.2).

module.exports = grammar({
  name: "basilir",
  extras: $ =>[
    /\s/,
    $.token_CommentSingle,
    $.token_CommentMulti,
  ],
  word: $ => $.token_LocalIdent,
  rules: {
    BNFCStart: $ =>
      optional(
        // BNFCStart_Module. BNFCStart ::= Module ;
        $.Module
      ),
    Module: $ =>
      // Module1. Module ::= [Decl] ;
      $.list_Decl,
    list_Decl: $ =>
      choice(
        // []. [Decl] ::= ;
        choice(),
        // (:). [Decl] ::= Decl ";" [Decl] ;
        seq($.Decl, ";", optional($.list_Decl))
      ),
    list_token_BlockIdent: $ =>
      choice(
        // []. [BlockIdent] ::= ;
        choice(),
        // (:[]). [BlockIdent] ::= BlockIdent ;
        $.token_BlockIdent,
        // (:). [BlockIdent] ::= BlockIdent "," [BlockIdent] ;
        seq($.token_BlockIdent, ",", optional($.list_token_BlockIdent))
      ),
    LambdaSep: $ =>
      choice(
        // LambdaSep1. LambdaSep ::= "->" ;
        "->",
        // LambdaSep2. LambdaSep ::= "::" ;
        "::"
      ),
    VarModifiers: $ =>
      choice(
        // Shared. VarModifiers ::= "shared" ;
        "shared",
        // Observable. VarModifiers ::= "observable" ;
        "observable"
      ),
    list_VarModifiers: $ =>
      choice(
        // []. [VarModifiers] ::= ;
        choice(),
        // (:). [VarModifiers] ::= VarModifiers [VarModifiers] ;
        seq($.VarModifiers, optional($.list_VarModifiers))
      ),
    Decl: $ =>
      choice(
        // Decl_Axiom. Decl ::= "axiom" GlobalIdent AttribSet Expr ;
        seq("axiom", $.token_GlobalIdent, optional($.AttribSet), $.Expr),
        // Decl_Mem. Decl ::= "memory" [VarModifiers] GlobalIdent ":" Type VarSpec ;
        seq("memory", optional($.list_VarModifiers), $.token_GlobalIdent, ":", $.Type, optional($.VarSpec)),
        // Decl_Var. Decl ::= "var" [VarModifiers] GlobalIdent ":" Type VarSpec ;
        seq("var", optional($.list_VarModifiers), $.token_GlobalIdent, ":", $.Type, optional($.VarSpec)),
        // Decl_UninterpFun. Decl ::= "val" GlobalIdent AttribSet ":" Type ;
        seq("val", $.token_GlobalIdent, optional($.AttribSet), ":", $.Type),
        // Decl_Fun. Decl ::= "let" GlobalIdent AttribSet ":" Type "=" Expr ;
        seq("let", $.token_GlobalIdent, optional($.AttribSet), ":", $.Type, "=", $.Expr),
        // Decl_FunNoType. Decl ::= "let" GlobalIdent AttribSet "=" Expr ;
        seq("let", $.token_GlobalIdent, optional($.AttribSet), "=", $.Expr),
        // Decl_ProgEmpty. Decl ::= "prog" "entry" ProcIdent AttribSet ;
        seq("prog", "entry", $.token_ProcIdent, optional($.AttribSet)),
        // Decl_ProgWithSpec. Decl ::= "prog" "entry" ProcIdent AttribSet [ProgSpec] ;
        seq("prog", "entry", $.token_ProcIdent, optional($.AttribSet), optional($.list_ProgSpec)),
        // Decl_Proc. Decl ::= "proc" ProcIdent OpenParen [Params] CloseParen "->" OpenParen [Params] CloseParen AttribSet [FunSpec] ProcDef ;
        seq("proc", $.token_ProcIdent, $.token_OpenParen, optional($.list_Params), $.token_CloseParen, "->", $.token_OpenParen, optional($.list_Params), $.token_CloseParen, optional($.AttribSet), optional($.list_FunSpec), optional($.ProcDef))
      ),
    list_Type: $ =>
      choice(
        // []. [Type] ::= ;
        choice(),
        // (:[]). [Type] ::= Type ;
        $.Type,
        // (:). [Type] ::= Type "," [Type] ;
        seq($.Type, ",", optional($.list_Type))
      ),
    ProcDef: $ =>
      choice(
        // ProcDef_Empty. ProcDef ::= ;
        choice(),
        // ProcDef_Some. ProcDef ::= BeginList [Block] EndList ;
        seq($.token_BeginList, optional($.list_Block), $.token_EndList)
      ),
    IntType: $ =>
      // IntType1. IntType ::= INTTYPE ;
      $.token_INTTYPE,
    BoolType: $ =>
      // BoolType1. BoolType ::= BOOLTYPE ;
      $.token_BOOLTYPE,
    BVType: $ =>
      // BVType1. BVType ::= BVTYPE ;
      $.token_BVTYPE,
    MapType: $ =>
      // MapType1. MapType ::= Type1 "->" Type ;
      seq($.Type1, "->", $.Type),
    Type1: $ =>
      choice(
        // TypeIntType. Type1 ::= IntType ;
        $.IntType,
        // TypeBoolType. Type1 ::= BoolType ;
        $.BoolType,
        // TypeBVType. Type1 ::= BVType ;
        $.BVType,
        // TypeParen. Type1 ::= OpenParen Type CloseParen ;
        seq($.token_OpenParen, $.Type, $.token_CloseParen)
      ),
    Type: $ =>
      choice(
        // TypeMapType. Type ::= MapType ;
        $.MapType,
        // _. Type ::= Type1 ;
        $.Type1
      ),
    IntVal: $ =>
      choice(
        // IntVal_Hex. IntVal ::= IntegerHex ;
        $.token_IntegerHex,
        // IntVal_Dec. IntVal ::= IntegerDec ;
        $.token_IntegerDec
      ),
    BVVal: $ =>
      // BVVal1. BVVal ::= IntVal ":" BVType ;
      seq($.IntVal, ":", $.BVType),
    Endian: $ =>
      choice(
        // Endian_Little. Endian ::= "le" ;
        "le",
        // Endian_Big. Endian ::= "be" ;
        "be"
      ),
    Assignment: $ =>
      // Assignment1. Assignment ::= LVar ":=" Expr ;
      seq($.LVar, ":=", $.Expr),
    Stmt: $ =>
      choice(
        // Stmt_Nop. Stmt ::= "nop" ;
        "nop",
        // Stmt_SingleAssign. Stmt ::= Assignment ;
        $.Assignment,
        // Stmt_MemAssign. Stmt ::= LVar "mem:=" Expr ;
        seq($.LVar, "mem:=", $.Expr),
        // Stmt_ScalarStore. Stmt ::= LVar ":=" "store" Expr ;
        seq($.LVar, ":=", "store", $.Expr),
        // Stmt_ScalarLoad. Stmt ::= LVar ":=" "load" Var ;
        seq($.LVar, ":=", "load", $.Var),
        // Stmt_MultiAssign. Stmt ::= OpenParen [Assignment] CloseParen ;
        seq($.token_OpenParen, $.list_Assignment, $.token_CloseParen),
        // Stmt_Load_Var. Stmt ::= LVar ":=" "load" Endian Var Expr IntVal ;
        seq($.LVar, ":=", "load", $.Endian, $.Var, $.Expr, $.IntVal),
        // Stmt_Store_Var. Stmt ::= LVar ":=" "store" Endian Var Expr2 Expr IntVal ;
        seq($.LVar, ":=", "store", $.Endian, $.Var, $.Expr2, $.Expr, $.IntVal),
        // Stmt_Store. Stmt ::= "store" Endian GlobalIdent Expr2 Expr IntVal ;
        seq("store", $.Endian, $.token_GlobalIdent, $.Expr2, $.Expr, $.IntVal),
        // Stmt_DirectCall. Stmt ::= LVars "call" ProcIdent OpenParen CallParams CloseParen ;
        seq(optional($.LVars), "call", $.token_ProcIdent, $.token_OpenParen, optional($.CallParams), $.token_CloseParen),
        // Stmt_IndirectCall. Stmt ::= "indirect" "call" Expr ;
        seq("indirect", "call", $.Expr),
        // Stmt_Assume. Stmt ::= "assume" Expr ;
        seq("assume", $.Expr),
        // Stmt_Guard. Stmt ::= "guard" Expr ;
        seq("guard", $.Expr),
        // Stmt_Assert. Stmt ::= "assert" Expr ;
        seq("assert", $.Expr)
      ),
    list_Assignment: $ =>
      choice(
        // (:[]). [Assignment] ::= Assignment ;
        $.Assignment,
        // (:). [Assignment] ::= Assignment "," [Assignment] ;
        seq($.Assignment, ",", $.list_Assignment)
      ),
    LocalVar: $ =>
      choice(
        // LocalTyped. LocalVar ::= LocalIdent ":" Type ;
        seq($.token_LocalIdent, ":", $.Type),
        // LocalUntyped. LocalVar ::= LocalIdent ;
        $.token_LocalIdent
      ),
    GlobalVar: $ =>
      choice(
        // GlobalTyped. GlobalVar ::= GlobalIdent ":" Type ;
        seq($.token_GlobalIdent, ":", $.Type),
        // GlobalUntyped. GlobalVar ::= GlobalIdent ;
        $.token_GlobalIdent
      ),
    list_LocalVar: $ =>
      choice(
        // (:[]). [LocalVar] ::= LocalVar ;
        $.LocalVar,
        // (:). [LocalVar] ::= LocalVar "," [LocalVar] ;
        seq($.LocalVar, ",", $.list_LocalVar)
      ),
    Var: $ =>
      choice(
        // VarLocalVar. Var ::= LocalVar ;
        $.LocalVar,
        // VarGlobalVar. Var ::= GlobalVar ;
        $.GlobalVar
      ),
    list_GlobalVar: $ =>
      choice(
        // []. [GlobalVar] ::= ;
        choice(),
        // (:[]). [GlobalVar] ::= GlobalVar ;
        $.GlobalVar,
        // (:). [GlobalVar] ::= GlobalVar "," [GlobalVar] ;
        seq($.GlobalVar, ",", optional($.list_GlobalVar))
      ),
    NamedCallReturn: $ =>
      // NamedCallReturn1. NamedCallReturn ::= LVar "=" LocalIdent ;
      seq($.LVar, "=", $.token_LocalIdent),
    list_NamedCallReturn: $ =>
      choice(
        // []. [NamedCallReturn] ::= ;
        choice(),
        // (:[]). [NamedCallReturn] ::= NamedCallReturn ;
        $.NamedCallReturn,
        // (:). [NamedCallReturn] ::= NamedCallReturn "," [NamedCallReturn] ;
        seq($.NamedCallReturn, ",", optional($.list_NamedCallReturn))
      ),
    LVars: $ =>
      choice(
        // LVars_Empty. LVars ::= ;
        choice(),
        // LVars_LocalList. LVars ::= "var" OpenParen [LocalVar] CloseParen ":=" ;
        seq("var", $.token_OpenParen, $.list_LocalVar, $.token_CloseParen, ":="),
        // LVars_List. LVars ::= OpenParen [LVar] CloseParen ":=" ;
        seq($.token_OpenParen, $.list_LVar, $.token_CloseParen, ":="),
        // NamedLVars_List. LVars ::= OpenParen [NamedCallReturn] CloseParen ":=" ;
        seq($.token_OpenParen, optional($.list_NamedCallReturn), $.token_CloseParen, ":=")
      ),
    NamedCallArg: $ =>
      // NamedCallArg1. NamedCallArg ::= LocalIdent "=" Expr ;
      seq($.token_LocalIdent, "=", $.Expr),
    list_NamedCallArg: $ =>
      choice(
        // (:[]). [NamedCallArg] ::= NamedCallArg ;
        $.NamedCallArg,
        // (:). [NamedCallArg] ::= NamedCallArg "," [NamedCallArg] ;
        seq($.NamedCallArg, ",", $.list_NamedCallArg)
      ),
    CallParams: $ =>
      choice(
        // CallParams_Exprs. CallParams ::= [Expr] ;
        $.list_Expr,
        // CallParams_Named. CallParams ::= [NamedCallArg] ;
        $.list_NamedCallArg
      ),
    Jump: $ =>
      choice(
        // Jump_GoTo. Jump ::= "goto" OpenParen [BlockIdent] CloseParen ;
        seq("goto", $.token_OpenParen, optional($.list_token_BlockIdent), $.token_CloseParen),
        // Jump_Unreachable. Jump ::= "unreachable" ;
        "unreachable",
        // Jump_Return. Jump ::= "return" OpenParen [Expr] CloseParen ;
        seq("return", $.token_OpenParen, optional($.list_Expr), $.token_CloseParen),
        // Jump_ProcReturn. Jump ::= "return" ;
        "return"
      ),
    LVar: $ =>
      choice(
        // LVar_Local. LVar ::= "var" LocalVar ;
        seq("var", $.LocalVar),
        // LVar_Global. LVar ::= GlobalVar ;
        $.GlobalVar
      ),
    list_LVar: $ =>
      choice(
        // (:[]). [LVar] ::= LVar ;
        $.LVar,
        // (:). [LVar] ::= LVar "," [LVar] ;
        seq($.LVar, ",", $.list_LVar)
      ),
    list_Block: $ =>
      choice(
        // []. [Block] ::= ;
        choice(),
        // (:[]). [Block] ::= Block ;
        $.Block,
        // (:). [Block] ::= Block ";" [Block] ;
        seq($.Block, ";", optional($.list_Block))
      ),
    StmtWithAttrib: $ =>
      // StmtWithAttrib1. StmtWithAttrib ::= Stmt AttribSet ;
      seq($.Stmt, optional($.AttribSet)),
    list_StmtWithAttrib: $ =>
      choice(
        // []. [StmtWithAttrib] ::= ;
        choice(),
        // (:). [StmtWithAttrib] ::= StmtWithAttrib ";" [StmtWithAttrib] ;
        seq($.StmtWithAttrib, ";", optional($.list_StmtWithAttrib))
      ),
    JumpWithAttrib: $ =>
      // JumpWithAttrib1. JumpWithAttrib ::= Jump AttribSet ;
      seq($.Jump, optional($.AttribSet)),
    PhiExpr: $ =>
      // PhiExpr1. PhiExpr ::= BlockIdent "->" Var ;
      seq($.token_BlockIdent, "->", $.Var),
    list_PhiExpr: $ =>
      choice(
        // []. [PhiExpr] ::= ;
        choice(),
        // (:[]). [PhiExpr] ::= PhiExpr ;
        $.PhiExpr,
        // (:). [PhiExpr] ::= PhiExpr "," [PhiExpr] ;
        seq($.PhiExpr, ",", optional($.list_PhiExpr))
      ),
    PhiAssign: $ =>
      // PhiAssign1. PhiAssign ::= LVar ":=" "phi" OpenParen [PhiExpr] CloseParen ;
      seq($.LVar, ":=", "phi", $.token_OpenParen, optional($.list_PhiExpr), $.token_CloseParen),
    list_PhiAssign: $ =>
      choice(
        // []. [PhiAssign] ::= ;
        choice(),
        // (:[]). [PhiAssign] ::= PhiAssign ;
        $.PhiAssign,
        // (:). [PhiAssign] ::= PhiAssign "," [PhiAssign] ;
        seq($.PhiAssign, ",", optional($.list_PhiAssign))
      ),
    Block: $ =>
      choice(
        // Block_NoPhi. Block ::= "block" BlockIdent AttribSet BeginList [StmtWithAttrib] JumpWithAttrib ";" EndList ;
        seq("block", $.token_BlockIdent, optional($.AttribSet), $.token_BeginList, optional($.list_StmtWithAttrib), $.JumpWithAttrib, ";", $.token_EndList),
        // Block_Phi. Block ::= "block" BlockIdent AttribSet OpenParen [PhiAssign] CloseParen BeginList [StmtWithAttrib] JumpWithAttrib ";" EndList ;
        seq("block", $.token_BlockIdent, optional($.AttribSet), $.token_OpenParen, optional($.list_PhiAssign), $.token_CloseParen, $.token_BeginList, optional($.list_StmtWithAttrib), $.JumpWithAttrib, ";", $.token_EndList)
      ),
    AttrKeyValue: $ =>
      // AttrKeyValue1. AttrKeyValue ::= BIdent "=" Attr ;
      seq($.token_BIdent, "=", $.Attr),
    list_AttrKeyValue: $ =>
      choice(
        // []. [AttrKeyValue] ::= ;
        choice(),
        // (:[]). [AttrKeyValue] ::= AttrKeyValue ;
        $.AttrKeyValue,
        // (:). [AttrKeyValue] ::= AttrKeyValue ";" [AttrKeyValue] ;
        seq($.AttrKeyValue, ";", optional($.list_AttrKeyValue))
      ),
    AttribSet: $ =>
      choice(
        // AttribSet_Some. AttribSet ::= BeginRec [AttrKeyValue] EndRec ;
        seq($.token_BeginRec, optional($.list_AttrKeyValue), $.token_EndRec),
        // AttribSet_Empty. AttribSet ::= ;
        choice()
      ),
    list_Attr: $ =>
      choice(
        // []. [Attr] ::= ;
        choice(),
        // (:[]). [Attr] ::= Attr ;
        $.Attr,
        // (:). [Attr] ::= Attr ";" [Attr] ;
        seq($.Attr, ";", optional($.list_Attr))
      ),
    Attr: $ =>
      choice(
        // Attr_Map. Attr ::= BeginRec [AttrKeyValue] EndRec ;
        seq($.token_BeginRec, optional($.list_AttrKeyValue), $.token_EndRec),
        // Attr_List. Attr ::= BeginList [Attr] EndList ;
        seq($.token_BeginList, optional($.list_Attr), $.token_EndList),
        // Attr_Expr. Attr ::= Expr ;
        $.Expr,
        // Attr_Str. Attr ::= Str ;
        $.token_Str
      ),
    Params: $ =>
      // Params1. Params ::= LocalIdent ":" Type ;
      seq($.token_LocalIdent, ":", $.Type),
    list_Params: $ =>
      choice(
        // []. [Params] ::= ;
        choice(),
        // (:[]). [Params] ::= Params ;
        $.Params,
        // (:). [Params] ::= Params "," [Params] ;
        seq($.Params, ",", optional($.list_Params))
      ),
    Value: $ =>
      choice(
        // Value_BV. Value ::= BVVal ;
        $.BVVal,
        // Value_Int. Value ::= IntVal ;
        $.IntVal,
        // Value_True. Value ::= "true" ;
        "true",
        // Value_False. Value ::= "false" ;
        "false"
      ),
    list_Expr: $ =>
      choice(
        // []. [Expr] ::= ;
        choice(),
        // (:[]). [Expr] ::= Expr ;
        $.Expr,
        // (:). [Expr] ::= Expr "," [Expr] ;
        seq($.Expr, ",", optional($.list_Expr))
      ),
    Expr: $ =>
      choice(
        // _. Expr ::= Expr1 ;
        $.Expr1,
        // Expr_Forall. Expr ::= "forall" AttribSet LambdaDef ;
        seq("forall", optional($.AttribSet), $.LambdaDef),
        // Expr_Exists. Expr ::= "exists" AttribSet LambdaDef ;
        seq("exists", optional($.AttribSet), $.LambdaDef),
        // Expr_Lambda. Expr ::= "fun" AttribSet LambdaDef ;
        seq("fun", optional($.AttribSet), $.LambdaDef)
      ),
    Expr1: $ =>
      choice(
        // _. Expr1 ::= Expr2 ;
        $.Expr2,
        // Expr_FunctionOp. Expr1 ::= Expr1 OpenParen [Expr] CloseParen ;
        seq($.Expr1, $.token_OpenParen, optional($.list_Expr), $.token_CloseParen)
      ),
    Expr2: $ =>
      choice(
        // Expr_Literal. Expr2 ::= Value ;
        $.Value,
        // Expr_Local. Expr2 ::= LocalVar ;
        $.LocalVar,
        // Expr_Global. Expr2 ::= GlobalVar ;
        $.GlobalVar,
        // Expr_Old. Expr2 ::= "old" OpenParen Expr CloseParen ;
        seq("old", $.token_OpenParen, $.Expr, $.token_CloseParen),
        // Expr_Binary. Expr2 ::= BinOp OpenParen Expr "," Expr CloseParen ;
        seq($.BinOp, $.token_OpenParen, $.Expr, ",", $.Expr, $.token_CloseParen),
        // Expr_Assoc. Expr2 ::= BoolBinOp OpenParen [Expr] CloseParen ;
        seq($.BoolBinOp, $.token_OpenParen, optional($.list_Expr), $.token_CloseParen),
        // Expr_Unary. Expr2 ::= UnOp OpenParen Expr CloseParen ;
        seq($.UnOp, $.token_OpenParen, $.Expr, $.token_CloseParen),
        // Expr_LoadBe. Expr2 ::= "load_be" OpenParen IntVal "," Expr "," Expr CloseParen ;
        seq("load_be", $.token_OpenParen, $.IntVal, ",", $.Expr, ",", $.Expr, $.token_CloseParen),
        // Expr_LoadLe. Expr2 ::= "load_le" OpenParen IntVal "," Expr "," Expr CloseParen ;
        seq("load_le", $.token_OpenParen, $.IntVal, ",", $.Expr, ",", $.Expr, $.token_CloseParen),
        // Expr_ZeroExtend. Expr2 ::= "zero_extend" OpenParen IntVal "," Expr CloseParen ;
        seq("zero_extend", $.token_OpenParen, $.IntVal, ",", $.Expr, $.token_CloseParen),
        // Expr_SignExtend. Expr2 ::= "sign_extend" OpenParen IntVal "," Expr CloseParen ;
        seq("sign_extend", $.token_OpenParen, $.IntVal, ",", $.Expr, $.token_CloseParen),
        // Expr_Extract. Expr2 ::= "extract" OpenParen IntVal "," IntVal "," Expr CloseParen ;
        seq("extract", $.token_OpenParen, $.IntVal, ",", $.IntVal, ",", $.Expr, $.token_CloseParen),
        // Expr_Concat. Expr2 ::= "bvconcat" OpenParen [Expr] CloseParen ;
        seq("bvconcat", $.token_OpenParen, optional($.list_Expr), $.token_CloseParen),
        // Expr_Match. Expr2 ::= "match" Expr "with" OpenParen [Case] CloseParen ;
        seq("match", $.Expr, "with", $.token_OpenParen, optional($.list_Case), $.token_CloseParen),
        // Expr_Cases. Expr2 ::= "cases" OpenParen [Case] CloseParen ;
        seq("cases", $.token_OpenParen, optional($.list_Case), $.token_CloseParen),
        // Expr_Paren. Expr2 ::= OpenParen Expr CloseParen ;
        seq($.token_OpenParen, $.Expr, $.token_CloseParen)
      ),
    LambdaParam: $ =>
      choice(
        // LambdaParamLocalIdent. LambdaParam ::= LocalIdent ;
        $.token_LocalIdent,
        // LambdaParam1. LambdaParam ::= LocalIdent ":" Type1 ;
        seq($.token_LocalIdent, ":", $.Type1),
        // LambdaParam2. LambdaParam ::= OpenParen LocalVar CloseParen ;
        seq($.token_OpenParen, $.LocalVar, $.token_CloseParen)
      ),
    list_LambdaParam: $ =>
      choice(
        // []. [LambdaParam] ::= ;
        choice(),
        // (:[]). [LambdaParam] ::= LambdaParam ;
        $.LambdaParam,
        // (:). [LambdaParam] ::= LambdaParam "," [LambdaParam] ;
        seq($.LambdaParam, ",", optional($.list_LambdaParam))
      ),
    LambdaDef: $ =>
      // LambdaDef1. LambdaDef ::= [LambdaParam] LambdaSep Expr ;
      seq(optional($.list_LambdaParam), $.LambdaSep, $.Expr),
    BinOp: $ =>
      choice(
        // BinOpBVBinOp. BinOp ::= BVBinOp ;
        $.BVBinOp,
        // BinOpBVLogicalBinOp. BinOp ::= BVLogicalBinOp ;
        $.BVLogicalBinOp,
        // BinOpIntLogicalBinOp. BinOp ::= IntLogicalBinOp ;
        $.IntLogicalBinOp,
        // BinOpIntBinOp. BinOp ::= IntBinOp ;
        $.IntBinOp,
        // BinOpEqOp. BinOp ::= EqOp ;
        $.EqOp
      ),
    UnOp: $ =>
      choice(
        // UnOpBVUnOp. UnOp ::= BVUnOp ;
        $.BVUnOp,
        // UnOp_boolnot. UnOp ::= "boolnot" ;
        "boolnot",
        // UnOp_intneg. UnOp ::= "intneg" ;
        "intneg",
        // UnOp_booltobv1. UnOp ::= "booltobv1" ;
        "booltobv1",
        // UnOp_gamma. UnOp ::= "gamma" ;
        "gamma",
        // UnOp_classification. UnOp ::= "classification" ;
        "classification"
      ),
    Case: $ =>
      choice(
        // CaseCase. Case ::= Expr "->" Expr ;
        seq($.Expr, "->", $.Expr),
        // CaseDefault. Case ::= "_" "->" Expr ;
        seq("_", "->", $.Expr)
      ),
    list_Case: $ =>
      choice(
        // []. [Case] ::= ;
        choice(),
        // (:[]). [Case] ::= Case ;
        $.Case,
        // (:). [Case] ::= Case "|" [Case] ;
        seq($.Case, "|", optional($.list_Case))
      ),
    EqOp: $ =>
      choice(
        // EqOp_eq. EqOp ::= "eq" ;
        "eq",
        // EqOp_neq. EqOp ::= "neq" ;
        "neq"
      ),
    BVUnOp: $ =>
      choice(
        // BVUnOp_bvnot. BVUnOp ::= "bvnot" ;
        "bvnot",
        // BVUnOp_bvneg. BVUnOp ::= "bvneg" ;
        "bvneg"
      ),
    BVBinOp: $ =>
      choice(
        // BVBinOp_bvand. BVBinOp ::= "bvand" ;
        "bvand",
        // BVBinOp_bvor. BVBinOp ::= "bvor" ;
        "bvor",
        // BVBinOp_bvadd. BVBinOp ::= "bvadd" ;
        "bvadd",
        // BVBinOp_bvmul. BVBinOp ::= "bvmul" ;
        "bvmul",
        // BVBinOp_bvudiv. BVBinOp ::= "bvudiv" ;
        "bvudiv",
        // BVBinOp_bvurem. BVBinOp ::= "bvurem" ;
        "bvurem",
        // BVBinOp_bvshl. BVBinOp ::= "bvshl" ;
        "bvshl",
        // BVBinOp_bvlshr. BVBinOp ::= "bvlshr" ;
        "bvlshr",
        // BVBinOp_bvnand. BVBinOp ::= "bvnand" ;
        "bvnand",
        // BVBinOp_bvnor. BVBinOp ::= "bvnor" ;
        "bvnor",
        // BVBinOp_bvxor. BVBinOp ::= "bvxor" ;
        "bvxor",
        // BVBinOp_bvxnor. BVBinOp ::= "bvxnor" ;
        "bvxnor",
        // BVBinOp_bvcomp. BVBinOp ::= "bvcomp" ;
        "bvcomp",
        // BVBinOp_bvsub. BVBinOp ::= "bvsub" ;
        "bvsub",
        // BVBinOp_bvsdiv. BVBinOp ::= "bvsdiv" ;
        "bvsdiv",
        // BVBinOp_bvsrem. BVBinOp ::= "bvsrem" ;
        "bvsrem",
        // BVBinOp_bvsmod. BVBinOp ::= "bvsmod" ;
        "bvsmod",
        // BVBinOp_bvashr. BVBinOp ::= "bvashr" ;
        "bvashr"
      ),
    BVLogicalBinOp: $ =>
      choice(
        // BVLogicalBinOp_bvule. BVLogicalBinOp ::= "bvule" ;
        "bvule",
        // BVLogicalBinOp_bvugt. BVLogicalBinOp ::= "bvugt" ;
        "bvugt",
        // BVLogicalBinOp_bvuge. BVLogicalBinOp ::= "bvuge" ;
        "bvuge",
        // BVLogicalBinOp_bvult. BVLogicalBinOp ::= "bvult" ;
        "bvult",
        // BVLogicalBinOp_bvslt. BVLogicalBinOp ::= "bvslt" ;
        "bvslt",
        // BVLogicalBinOp_bvsle. BVLogicalBinOp ::= "bvsle" ;
        "bvsle",
        // BVLogicalBinOp_bvsgt. BVLogicalBinOp ::= "bvsgt" ;
        "bvsgt",
        // BVLogicalBinOp_bvsge. BVLogicalBinOp ::= "bvsge" ;
        "bvsge"
      ),
    IntBinOp: $ =>
      choice(
        // IntBinOp_intadd. IntBinOp ::= "intadd" ;
        "intadd",
        // IntBinOp_intmul. IntBinOp ::= "intmul" ;
        "intmul",
        // IntBinOp_intsub. IntBinOp ::= "intsub" ;
        "intsub",
        // IntBinOp_intdiv. IntBinOp ::= "intdiv" ;
        "intdiv",
        // IntBinOp_intmod. IntBinOp ::= "intmod" ;
        "intmod"
      ),
    IntLogicalBinOp: $ =>
      choice(
        // IntLogicalBinOp_intlt. IntLogicalBinOp ::= "intlt" ;
        "intlt",
        // IntLogicalBinOp_intle. IntLogicalBinOp ::= "intle" ;
        "intle",
        // IntLogicalBinOp_intgt. IntLogicalBinOp ::= "intgt" ;
        "intgt",
        // IntLogicalBinOp_intge. IntLogicalBinOp ::= "intge" ;
        "intge"
      ),
    BoolBinOp: $ =>
      choice(
        // BoolBinOp_booland. BoolBinOp ::= "booland" ;
        "booland",
        // BoolBinOp_boolor. BoolBinOp ::= "boolor" ;
        "boolor",
        // BoolBinOp_boolimplies. BoolBinOp ::= "boolimplies" ;
        "boolimplies"
      ),
    RequireTok: $ =>
      choice(
        // RequireTok_require. RequireTok ::= "require" ;
        "require",
        // RequireTok_requires. RequireTok ::= "requires" ;
        "requires"
      ),
    EnsureTok: $ =>
      choice(
        // EnsureTok_ensure. EnsureTok ::= "ensure" ;
        "ensure",
        // EnsureTok_ensures. EnsureTok ::= "ensures" ;
        "ensures"
      ),
    RelyTok: $ =>
      choice(
        // RelyTok_rely. RelyTok ::= "rely" ;
        "rely",
        // RelyTok_relies. RelyTok ::= "relies" ;
        "relies"
      ),
    GuarTok: $ =>
      choice(
        // GuarTok_guarantee. GuarTok ::= "guarantee" ;
        "guarantee",
        // GuarTok_guarantees. GuarTok ::= "guarantees" ;
        "guarantees"
      ),
    FunSpec: $ =>
      choice(
        // FunSpec_Require. FunSpec ::= RequireTok Expr ;
        seq($.RequireTok, $.Expr),
        // FunSpec_Ensure. FunSpec ::= EnsureTok Expr ;
        seq($.EnsureTok, $.Expr),
        // FunSpec_Rely. FunSpec ::= RelyTok Expr ;
        seq($.RelyTok, $.Expr),
        // FunSpec_Guar. FunSpec ::= GuarTok Expr ;
        seq($.GuarTok, $.Expr),
        // FunSpec_Captures. FunSpec ::= "captures" [GlobalVar] ;
        seq("captures", optional($.list_GlobalVar)),
        // FunSpec_Modifies. FunSpec ::= "modifies" [GlobalVar] ;
        seq("modifies", optional($.list_GlobalVar)),
        // FunSpec_Invariant. FunSpec ::= "invariant" BlockIdent Expr ;
        seq("invariant", $.token_BlockIdent, $.Expr)
      ),
    VarSpec: $ =>
      choice(
        // VarSpec_Classification. VarSpec ::= "classification" Expr ;
        seq("classification", $.Expr),
        // VarSpec_Empty. VarSpec ::= ;
        choice()
      ),
    ProgSpec: $ =>
      choice(
        // ProgSpec_Rely. ProgSpec ::= RelyTok Expr ;
        seq($.RelyTok, $.Expr),
        // ProgSpec_Guarantee. ProgSpec ::= GuarTok Expr ;
        seq($.GuarTok, $.Expr)
      ),
    list_FunSpec: $ =>
      choice(
        // []. [FunSpec] ::= ;
        choice(),
        // (:). [FunSpec] ::= FunSpec [FunSpec] ;
        seq($.FunSpec, optional($.list_FunSpec))
      ),
    list_ProgSpec: $ =>
      choice(
        // []. [ProgSpec] ::= ;
        choice(),
        // (:). [ProgSpec] ::= ProgSpec [ProgSpec] ;
        seq($.ProgSpec, optional($.list_ProgSpec))
      ),
    token_BVTYPE: $ =>
      /bv\d+/,
    token_INTTYPE: $ =>
      /int/,
    token_BOOLTYPE: $ =>
      /bool/,
    token_BIdent: $ =>
      /\.(_|[a-zA-Z])([#\$\._~]|(\d|[a-zA-Z]))*/,
    token_LocalIdent: $ =>
      /([#_]|[a-zA-Z])([#\$\._]|(\d|[a-zA-Z]))*/,
    token_GlobalIdent: $ =>
      /\$([#\$\._]|(\d|[a-zA-Z]))+/,
    token_BlockIdent: $ =>
      /%([#\$\._]|(\d|[a-zA-Z]))+/,
    token_ProcIdent: $ =>
      /@([#\$\._]|(\d|[a-zA-Z]))+/,
    token_OpenParen: $ =>
      /\(/,
    token_CloseParen: $ =>
      /\)/,
    token_BeginList: $ =>
      /\[/,
    token_EndList: $ =>
      /\]/,
    token_BeginRec: $ =>
      /\{/,
    token_EndRec: $ =>
      /\}/,
    token_Str: $ =>
      /"([^"\\]|\\["\\fnrt])*"/,
    token_IntegerHex: $ =>
      /0x([abcdef]|\d)+/,
    token_IntegerDec: $ =>
      /\d+/,
    token_CommentSingle: $ =>
      /\/\/.*\n/,
    token_CommentMulti: $ =>
      /\/\*[^*]*\*([^\*\/][^*]*\*|\*)*\//,
  },
});
