
/**
 * @file Basilir grammar for tree-sitter
 * @author UQ PAC
 * @license MIT
 */

/// <reference types="tree-sitter-cli/dsl" />
// @ts-check

module.exports = grammar({
  name: "basilir",

  extras: ($) => [
    new RustRegex("\\s"),
  ],

  rules: {
    // TODO: add the actual grammar rules
    source_file: $ => repeat(choice($.keyword, $.other)),
    keyword: $ => choice("assert",
"assume",
"axiom",
"be",
"block",
"booland",
"boolimplies",
"boolnot",
"boolor",
"booltobv1",
"bvadd",
"bvand",
"bvashr",
"bvcomp",
"bvconcat",
"bvlshr",
"bvmul",
"bvnand",
"bvneg",
"bvnor",
"bvnot",
"bvor",
"bvsdiv",
"bvsge",
"bvsgt",
"bvshl",
"bvsle",
"bvslt",
"bvsmod",
"bvsrem",
"bvsub",
"bvudiv",
"bvuge",
"bvugt",
"bvule",
"bvult",
"bvurem",
"bvxnor",
"bvxor",
"call",
"ensure",
"ensures",
"entry",
"eq",
"exists",
"extract",
"false",
"forall",
"goto",
"guarantee",
"guard",
"indirect",
"intadd",
"intdiv",
"intge",
"intgt",
"intle",
"intlt",
"intmod",
"intmul",
"intneg",
"intsub",
"invariant",
"le",
"load",
"memory",
"neq",
"nop",
"old",
"phi",
"proc",
"prog",
"rely",
"require",
"requires",
"return",
"shared",
"sign_extend",
"store",
"true",
"unreachable",
"var",
"zero_extend"),
    other: $ => choice(new RustRegex("//.*\\n"),
new RustRegex("/\\*.*?\\*/"),
new RustRegex("bv(\\d)+"),
new RustRegex("int"),
new RustRegex("bool"),
new RustRegex("\\.(_|[a-zA-Z])([#$\\._~]|\\d|[a-zA-Z])*"),
new RustRegex("([#_]|[a-zA-Z])([#$\\._]|\\d|[a-zA-Z])*"),
new RustRegex("\\$([#$\\._]|\\d|[a-zA-Z])+"),
new RustRegex("%([#$\\._]|\\d|[a-zA-Z])+"),
new RustRegex("@([#$\\._]|\\d|[a-zA-Z])+"),
new RustRegex("\\["),
new RustRegex("\\]"),
new RustRegex("\\{"),
new RustRegex("\\}"),
new RustRegex("::|->"),
new RustRegex("\"([^\\\"]|\\\\[^\"])*\""),
new RustRegex("0x([abcdef]|\\d)+"),
new RustRegex("(\\d)+"),
new RustRegex("[a-zA-Z]([a-zA-Z]|\\d|_|\\')*"),
new RustRegex(";|,|:|declare-fun|\\(|\\)|->|define-fun|=|:="),
new RustRegex("(\\d)+"),
new RustRegex("(\\d)+\\.(\\d)+(e(-)?(\\d)+)?"),
new RustRegex("\"([^\\\"]|\\\\[^\"])*\""),
new RustRegex("'([^\\']|\\\\[^'])*'"),
new RustRegex("\\s+")),
  }
});
