(library
 (public_name bincaml_lsp)
 (name bincaml_lsp)
 (modules raw_tokens)
(libraries
           linol-lwt
           linol
           lsp
           bincaml
           bincaml.basilir
  )
  (flags (-w -27 -w -39 -w -33 -w -23))
 (preprocess (pps ppx_deriving.show ppx_deriving.eq ppx_deriving.ord))
 )
