(* This file is generated by ortac wrapper,
   edit the original interface file instead *)
include Demo
module Ortac_runtime = Ortac_runtime
let __projection_size__001_ __arg0 =
  let __error__003_ =
    Ortac_runtime.Errors.create
      {
        Ortac_runtime.start =
          {
            pos_fname = "demo.mli";
            pos_lnum = 5;
            pos_bol = 167;
            pos_cnum = 167
          };
        Ortac_runtime.stop =
          {
            pos_fname = "demo.mli";
            pos_lnum = 6;
            pos_bol = 269;
            pos_cnum = 280
          }
      } "__projection_size__001_" in
  let result =
    try to_size __arg0
    with
    | Stack_overflow | Out_of_memory as e ->
        (Ortac_runtime.Errors.report __error__003_; raise e)
    | e ->
        ((Ortac_runtime.Unexpected_exception { allowed_exn = []; exn = e })
           |> (Ortac_runtime.Errors.register __error__003_);
         Ortac_runtime.Errors.report __error__003_;
         raise e) in
  Ortac_runtime.Errors.report __error__003_; result
let __projection_contents__002_ __arg0_1 =
  let __error__004_ =
    Ortac_runtime.Errors.create
      {
        Ortac_runtime.start =
          {
            pos_fname = "demo.mli";
            pos_lnum = 8;
            pos_bol = 282;
            pos_cnum = 282
          };
        Ortac_runtime.stop =
          {
            pos_fname = "demo.mli";
            pos_lnum = 9;
            pos_bol = 392;
            pos_cnum = 403
          }
      } "__projection_contents__002_" in
  let result_1 =
    try to_list __arg0_1
    with
    | Stack_overflow | Out_of_memory as e ->
        (Ortac_runtime.Errors.report __error__004_; raise e)
    | e ->
        ((Ortac_runtime.Unexpected_exception { allowed_exn = []; exn = e })
           |> (Ortac_runtime.Errors.register __error__004_);
         Ortac_runtime.Errors.report __error__004_;
         raise e) in
  Ortac_runtime.Errors.report __error__004_; result_1
let to_size __arg0 =
  let __error__003_ =
    Ortac_runtime.Errors.create
      {
        Ortac_runtime.start =
          {
            pos_fname = "demo.mli";
            pos_lnum = 5;
            pos_bol = 167;
            pos_cnum = 167
          };
        Ortac_runtime.stop =
          {
            pos_fname = "demo.mli";
            pos_lnum = 6;
            pos_bol = 269;
            pos_cnum = 280
          }
      } "to_size" in
  Ortac_runtime.Errors.report __error__003_;
  (let result =
     try to_size __arg0
     with
     | Stack_overflow | Out_of_memory as e ->
         (Ortac_runtime.Errors.report __error__003_; raise e)
     | e ->
         ((Ortac_runtime.Unexpected_exception { allowed_exn = []; exn = e })
            |> (Ortac_runtime.Errors.register __error__003_);
          Ortac_runtime.Errors.report __error__003_;
          raise e) in
   Ortac_runtime.Errors.report __error__003_; result)
let to_list __arg0_1 =
  let __error__004_ =
    Ortac_runtime.Errors.create
      {
        Ortac_runtime.start =
          {
            pos_fname = "demo.mli";
            pos_lnum = 8;
            pos_bol = 282;
            pos_cnum = 282
          };
        Ortac_runtime.stop =
          {
            pos_fname = "demo.mli";
            pos_lnum = 9;
            pos_bol = 392;
            pos_cnum = 403
          }
      } "to_list" in
  Ortac_runtime.Errors.report __error__004_;
  (let result_1 =
     try to_list __arg0_1
     with
     | Stack_overflow | Out_of_memory as e ->
         (Ortac_runtime.Errors.report __error__004_; raise e)
     | e ->
         ((Ortac_runtime.Unexpected_exception { allowed_exn = []; exn = e })
            |> (Ortac_runtime.Errors.register __error__004_);
          Ortac_runtime.Errors.report __error__004_;
          raise e) in
   Ortac_runtime.Errors.report __error__004_; result_1)
let make i a_1 =
  let __error__005_ =
    Ortac_runtime.Errors.create
      {
        Ortac_runtime.start =
          {
            pos_fname = "demo.mli";
            pos_lnum = 11;
            pos_bol = 405;
            pos_cnum = 405
          };
        Ortac_runtime.stop =
          {
            pos_fname = "demo.mli";
            pos_lnum = 15;
            pos_bol = 587;
            pos_cnum = 639
          }
      } "make" in
  let __check__006_ =
    try
      Ortac_runtime.Gospelstdlib.(>=)
        (Ortac_runtime.Gospelstdlib.integer_of_int i)
        (Ortac_runtime.Gospelstdlib.integer_of_int 0)
    with
    | e ->
        ((Ortac_runtime.Specification_failure
            { term = "i >= 0"; term_kind = Check; exn = e })
           |> (Ortac_runtime.Errors.register __error__005_);
         true) in
  Ortac_runtime.Errors.report __error__005_;
  (let t_1 =
     try make i a_1
     with
     | Invalid_argument _ as e ->
         ((if true && __check__006_
           then
             (Ortac_runtime.Unexpected_checks { terms = [] }) |>
               (Ortac_runtime.Errors.register __error__005_);
           Ortac_runtime.Errors.report __error__005_);
          raise e)
     | Stack_overflow | Out_of_memory as e ->
         ((if not __check__006_
           then
             (Ortac_runtime.Uncaught_checks { term = "i >= 0" }) |>
               (Ortac_runtime.Errors.register __error__005_);
           Ortac_runtime.Errors.report __error__005_);
          raise e)
     | e ->
         ((Ortac_runtime.Unexpected_exception { allowed_exn = []; exn = e })
            |> (Ortac_runtime.Errors.register __error__005_);
          (if not __check__006_
           then
             (Ortac_runtime.Uncaught_checks { term = "i >= 0" }) |>
               (Ortac_runtime.Errors.register __error__005_);
           Ortac_runtime.Errors.report __error__005_);
          raise e) in
   if
     not
       (try
          (__projection_contents__002_ t_1) =
            (Ortac_runtime.Gospelstdlib.List.init
               (Ortac_runtime.Gospelstdlib.integer_of_int i) (fun _ -> a_1))
        with
        | e ->
            ((Ortac_runtime.Specification_failure
                {
                  term = "t.contents = List.init i (fun _ -> a)";
                  term_kind = Post;
                  exn = e
                })
               |> (Ortac_runtime.Errors.register __error__005_);
             true))
   then
     (Ortac_runtime.Violated_condition
        { term = "t.contents = List.init i (fun _ -> a)"; term_kind = Post })
       |> (Ortac_runtime.Errors.register __error__005_);
   if
     not
       (try (__projection_size__001_ t_1) = i
        with
        | e ->
            ((Ortac_runtime.Specification_failure
                { term = "t.size = i"; term_kind = Post; exn = e })
               |> (Ortac_runtime.Errors.register __error__005_);
             true))
   then
     (Ortac_runtime.Violated_condition
        { term = "t.size = i"; term_kind = Post })
       |> (Ortac_runtime.Errors.register __error__005_);
   if not __check__006_
   then
     (Ortac_runtime.Uncaught_checks { term = "i >= 0" }) |>
       (Ortac_runtime.Errors.register __error__005_);
   Ortac_runtime.Errors.report __error__005_;
   t_1)
let get t_2 i_1 =
  let __error__007_ =
    Ortac_runtime.Errors.create
      {
        Ortac_runtime.start =
          {
            pos_fname = "demo.mli";
            pos_lnum = 17;
            pos_bol = 641;
            pos_cnum = 641
          };
        Ortac_runtime.stop =
          {
            pos_fname = "demo.mli";
            pos_lnum = 20;
            pos_bol = 798;
            pos_cnum = 838
          }
      } "get" in
  let __check__010_ =
    try
      let __t1__008_ =
        Ortac_runtime.Gospelstdlib.(<=)
          (Ortac_runtime.Gospelstdlib.integer_of_int 0)
          (Ortac_runtime.Gospelstdlib.integer_of_int i_1) in
      let __t2__009_ =
        Ortac_runtime.Gospelstdlib.(<)
          (Ortac_runtime.Gospelstdlib.integer_of_int i_1)
          (Ortac_runtime.Gospelstdlib.integer_of_int (to_size t_2)) in
      __t1__008_ && __t2__009_
    with
    | e ->
        ((Ortac_runtime.Specification_failure
            { term = "0 <= i < to_size t"; term_kind = Check; exn = e })
           |> (Ortac_runtime.Errors.register __error__007_);
         true) in
  Ortac_runtime.Errors.report __error__007_;
  (let a_2 =
     try get t_2 i_1
     with
     | Invalid_argument _ as e ->
         ((if true && __check__010_
           then
             (Ortac_runtime.Unexpected_checks { terms = [] }) |>
               (Ortac_runtime.Errors.register __error__007_);
           Ortac_runtime.Errors.report __error__007_);
          raise e)
     | Stack_overflow | Out_of_memory as e ->
         ((if not __check__010_
           then
             (Ortac_runtime.Uncaught_checks { term = "0 <= i < to_size t" })
               |> (Ortac_runtime.Errors.register __error__007_);
           Ortac_runtime.Errors.report __error__007_);
          raise e)
     | e ->
         ((Ortac_runtime.Unexpected_exception { allowed_exn = []; exn = e })
            |> (Ortac_runtime.Errors.register __error__007_);
          (if not __check__010_
           then
             (Ortac_runtime.Uncaught_checks { term = "0 <= i < to_size t" })
               |> (Ortac_runtime.Errors.register __error__007_);
           Ortac_runtime.Errors.report __error__007_);
          raise e) in
   if
     not
       (try
          a_2 =
            (Ortac_runtime.Gospelstdlib.List.nth
               (__projection_contents__002_ t_2)
               (Ortac_runtime.Gospelstdlib.integer_of_int i_1))
        with
        | e ->
            ((Ortac_runtime.Specification_failure
                {
                  term = "a = List.nth t.contents i";
                  term_kind = Post;
                  exn = e
                })
               |> (Ortac_runtime.Errors.register __error__007_);
             true))
   then
     (Ortac_runtime.Violated_condition
        { term = "a = List.nth t.contents i"; term_kind = Post })
       |> (Ortac_runtime.Errors.register __error__007_);
   if not __check__010_
   then
     (Ortac_runtime.Uncaught_checks { term = "0 <= i < to_size t" }) |>
       (Ortac_runtime.Errors.register __error__007_);
   Ortac_runtime.Errors.report __error__007_;
   a_2)
let set t_3 i_2 a_3 =
  let __error__011_ =
    Ortac_runtime.Errors.create
      {
        Ortac_runtime.start =
          {
            pos_fname = "demo.mli";
            pos_lnum = 22;
            pos_bol = 840;
            pos_cnum = 840
          };
        Ortac_runtime.stop =
          {
            pos_fname = "demo.mli";
            pos_lnum = 26;
            pos_bol = 1091;
            pos_cnum = 1193
          }
      } "set" in
  let ___ortac_copy_1 = Ortac_runtime.copy t_3 in
  if
    not
      (try
         let __t1__012_ =
           Ortac_runtime.Gospelstdlib.(<=)
             (Ortac_runtime.Gospelstdlib.integer_of_int 0)
             (Ortac_runtime.Gospelstdlib.integer_of_int i_2) in
         let __t2__013_ =
           Ortac_runtime.Gospelstdlib.(<)
             (Ortac_runtime.Gospelstdlib.integer_of_int i_2)
             (Ortac_runtime.Gospelstdlib.integer_of_int (to_size t_3)) in
         __t1__012_ && __t2__013_
       with
       | e ->
           ((Ortac_runtime.Specification_failure
               { term = "0 <= i < to_size t"; term_kind = Pre; exn = e })
              |> (Ortac_runtime.Errors.register __error__011_);
            true))
  then
    (Ortac_runtime.Violated_condition
       { term = "0 <= i < to_size t"; term_kind = Pre })
      |> (Ortac_runtime.Errors.register __error__011_);
  Ortac_runtime.Errors.report __error__011_;
  (let () =
     try set t_3 i_2 a_3
     with
     | Stack_overflow | Out_of_memory as e ->
         (Ortac_runtime.Errors.report __error__011_; raise e)
     | e ->
         ((Ortac_runtime.Unexpected_exception { allowed_exn = []; exn = e })
            |> (Ortac_runtime.Errors.register __error__011_);
          Ortac_runtime.Errors.report __error__011_;
          raise e) in
   if
     not
       (try
          (__projection_contents__002_ t_3) =
            (Ortac_runtime.Gospelstdlib.List.mapi
               (fun j ->
                  fun x ->
                    if j = (Ortac_runtime.Gospelstdlib.integer_of_int i_2)
                    then a_3
                    else x) (__projection_contents__002_ ___ortac_copy_1))
        with
        | e ->
            ((Ortac_runtime.Specification_failure
                {
                  term =
                    "t.contents = List.mapi (fun j x -> if j = (i : integer) then a else x) (old t.contents)";
                  term_kind = Post;
                  exn = e
                })
               |> (Ortac_runtime.Errors.register __error__011_);
             true))
   then
     (Ortac_runtime.Violated_condition
        {
          term =
            "t.contents = List.mapi (fun j x -> if j = (i : integer) then a else x) (old t.contents)";
          term_kind = Post
        })
       |> (Ortac_runtime.Errors.register __error__011_);
   Ortac_runtime.Errors.report __error__011_;
   ())
