(library
 (public_name bincaml.loader)
 (name loader)
 (modules loadir)
 (inline_tests)
 (preprocess
  (pps ppx_expect ppx_deriving.show ppx_deriving.eq ppx_deriving.ord))
 (libraries
  pp_loc
  BasilIR
  lang
  bincaml.ast
  bincaml.util
  zarith
  iter
  logs
  mtime
  trace.core
  str))

; (library
;  (public_name bincaml.backends)
;  (name backends)
;  (modules boogie)
;  (libraries containers containers-data containers.pp backends)
;  (inline_tests))

(library
 (public_name bincaml)
 (modules passes script invariants)
 (libraries
  bincaml.gtirb
  loader
  containers.pp
  pp_loc
  BasilIR
  lang
  transforms
  bincaml.backends
  bincaml.ast
  bincaml.util
  logs
  mtime
  trace.core)
 (preprocess
  (pps ppx_deriving.show ppx_deriving.eq ppx_deriving.ord)))
