(rule
 (targets bayat1.il)
 (deps %{bin:bincaml})
 (mode fallback)
 (action
  (run make "SRCS=%{dep:bayat1.c}" -f %{dep:../Makefile} %{targets})))

(rule
 (targets bayat2.il)
 (deps %{bin:bincaml})
 (mode fallback)
 (action
  (run make "SRCS=%{dep:bayat2.c}" -f %{dep:../Makefile} %{targets})))

(library
 (name dsa_tests)
 (package bincaml)
 (inline_tests
  (deps bayat1.il bayat2.il))
 (modules inline)
 (libraries bincaml.util bincaml)
 (preprocess
  (pps ppx_expect)))
