(cram
 (applies_to expr_smt)
 (package bincaml)
 (enabled_if %{bin-available:cvc5})
 (deps
  %{bin:bincaml}
  ../../examples/cntlm-output.il
  expr_smt_check.sexp
  concat.il))

(cram
 (applies_to
  *
  \
  expr_smt
  malloc_free
  memory_safety
  memory_interproc
  memory_phis)
 (package bincaml)
 (deps
  loop_dfg.sexp
  ../../examples/loop.il
  %{bin:bincaml}
  ssa-multi-deps.il
  memassign.il
  ptrrec1.il
  ../../examples/sqrt.il
  ../../examples/irreducible_loop_1.il
  ../../examples/cat.il
  ../../examples/cntlm-output.il
  ../../examples/cntlm-simp-output.il
  incorrect_types.il
  ../../examples/x-output.il
  inter_dead.il
  typefail.sexp
  typepass.sexp
  sva.sexp
  basicssa.sexp
  roundtrip.sexp
  gammavars.sexp
  ../../examples/gamma.il
  linear_copy.sexp
  ../../examples/linear_copy.il
  inter_dead.sexp
  ../../examples/const.il
  const.sexp
  ../../examples/collapse_edge.il
  collapse_edge.sexp
  ll_simple.il
  ll_simple.sexp
  ll_real.sexp
  ll_spec.il
  ll_spec.sexp
  repeated_ssa.il
  repeated_ssa.sexp
  boogie_phis.il
  boogie_phis.sexp
  ../../bin/main.exe))

(cram
 (applies_to malloc_free memory_safety memory_interproc memory_phis)
 (package bincaml)
 (enabled_if
  (and %{bin-available:boogie} %{bin-available:cvc5}))
 (deps
  %{bin:bincaml}
  ../../examples/memory/malloc_free.il
  ../../examples/memory/malloc_free_oob.il
  ./malloc_free.sexp
  ../../examples/memory/memory_interproc.il
  ./memory_interproc.sexp
  ../../examples/memory/memory_safety.il
  ./memory_safety.sexp
  ./memory_phis.il
  ./memory_phis.sexp))
