(library
 (public_name bincaml.transforms)
 (name transforms)
 (modules
  cse_elim
  irreducible_loop
  chop_reachable
  ssa
  dsa
  cf_tx
  livevars
  cleanup_cfg
  may_read_uninit
  type_check
  memory_encoding
  memory_specification
  function_summaries
  boogie_prepass
  gamma_vars
  const_prop
  linear_copy)
 (libraries
  bincaml.analysis
  patricia-tree
  loader
  lang
  zarith
  fix
  ocamlgraph
  containers
  containers-data
  iter
  containers.pp
  trace.core
  bincaml.util)
 (inline_tests)
 (preprocess
  (pps
   ppx_here
   ppx_deriving.show
   ppx_deriving.eq
   ppx_deriving.ord
   ppx_deriving.map
   ppx_deriving.iter
   ppx_deriving.fold
   ppx_deriving.enum
   ppx_expect)))
