(rule
 (target includes.gen)
 (enabled_if
  (and
   (= %{system} "macosx")
   %{bin-available:brew}))
 (action
  (with-stdout-to
   includes.gen
   (bash "echo $(brew --prefix)/include"))))

(rule
 (target includes.gen)
 (enabled_if
  (not
   (and
    (= %{system} "macosx")
    %{bin-available:brew})))
 (action
  (with-stdout-to
   includes.gen
   (echo "()"))))

(library
 (public_name capstone_arm64_disas)
 (name capstone)
 (modules capstone)
 (foreign_stubs
  (language c)
  (include_dirs
   (include includes.gen))
  (names capst))
 (c_library_flags -lcapstone))

(test
 (name test_capstone)
 (modules test_capstone)
 (libraries capstone))
