(rule
 (target includes.gen)
 (enabled_if
  (= %{system} "macosx"))
 (deps capst.c)
 (action
  (with-stdout-to
   includes.gen
   (system
    "if cc -E capst.c >/dev/null; then echo '()'; else echo $(brew --prefix)/include; fi"))))

(rule
 (target includes.gen)
 (enabled_if
  (<> %{system} "macosx"))
 (action
  (with-stdout-to
   includes.gen
   (echo "()"))))

(library
 (public_name capstone_arm64_disas)
 (name capstone)
 (modules capstone)
 (foreign_stubs
  (language c)
  (include_dirs
   (include includes.gen))
  (names capst))
 (c_library_flags -lcapstone))

(test
 (name test_capstone)
 (modules test_capstone)
 (libraries capstone))
