name: ci

on:
  pull_request:
  merge_group:
  workflow_dispatch:
  push:
    branches:
      - main

permissions: read-all

env:
  OPAMCONFIRMLEVEL: unsafe-yes

jobs:

  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      - uses: ./.github/actions/bincaml-setup
        with:
          ocaml-compiler: "5.4"

      - run: opam lint
        if: "!cancelled()"
      - run: dune build @fmt --display=quiet
        if: "!cancelled()"
      - run: dune build '@treesit'
        if: "!cancelled()"

  test:
    strategy:
      matrix:
        include:
          - { v: "5.3", os: ubuntu }
          - { v: "5.4", os: ubuntu }
          - { v: "5.4", os: macos }
      fail-fast: false
    timeout-minutes: 20
    runs-on: ${{ matrix.os }}-latest

    env:
      dune_args: ${{ matrix.os == 'macos' && '--ignore-promoted-rules' || '' }}

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: ./.github/actions/bincaml-setup
        with:
          ocaml-compiler: ${{ matrix.v }}

      - run: |
          if command -v brew; then echo LIBRARY_PATH="$LIBRARY_PATH:$(brew --prefix)/lib" >> "$GITHUB_ENV"; fi

      - run: opam exec -- dune build $dune_args --profile=release
        if: "!cancelled()"
      - run: opam exec -- dune runtest $dune_args --force
        if: "!cancelled()"

  nix-docs-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true

      - uses: nixbuild/nix-quick-install-action@v35
      - uses: nix-community/cache-nix-action@v7
        with:
          # restore and save a cache using this key
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          # if there's no cache hit, restore a cache by this prefix
          restore-prefixes-first-match: nix-${{ runner.os }}-
          # collect garbage until the Nix store size (in bytes) is at most this number
          # before trying to save a new cache
          # 1G = 1073741824
          gc-max-store-size-linux: 1G
          # do purge caches
          purge: true
          # purge all versions of the cache
          purge-prefixes: nix-${{ runner.os }}-
          # created more than this number of seconds ago
          purge-created: 0
          # or last accessed this duration (ISO 8601 duration format)
          # before the start of the `Post Restore and save Nix store` phase
          purge-last-accessed: P1DT12H
          # except any version with the key that is the same as the `primary-key`
          purge-primary-key: never

      - run: ./in-nix echo "Preparing Nix shell"

      - run: nix build .#bincamlDocs.docs -L
        shell: bash

      - uses: actions/upload-pages-artifact@v3
        with:
          path: result/.

  docs-deploy:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: false

    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}

    needs: docs-build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      id-token: write
      pages: write

    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
