name: build and test linux

on:
  pull_request:
  merge_group:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: build_test
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        include:
          - ocaml-version: "5.4"
            container: ghcr.io/agle/bincaml-ci-containers/ci-5.4:latest
          - ocaml-version: "5.3"
            container: ghcr.io/agle/bincaml-ci-containers/ci-5.3-doc:latest

    runs-on: ubuntu-latest
    container: ${{ matrix.container }}

    steps:
      - uses: actions/checkout@v6
      - run: opam install -t . --deps-only
      - run: opam exec -- dune build '@install'
      - run: opam exec -- dune runtest --force --profile=release

  lint-fmt:
    name: format 
    runs-on: ubuntu-latest
    container: ghcr.io/agle/bincaml-ci-containers/ci-5.4:latest
    steps:
      - uses: actions/checkout@v6
      - run: opam exec -- dune build @fmt --display=quiet

  lint-opam:
    name: lint-opam 
    runs-on: ubuntu-latest
    container: ghcr.io/agle/bincaml-ci-containers/ci-5.4:latest
    steps:
      - uses: actions/checkout@v6
      - run: opam lint
