name: build and test

on:
  pull_request:
  merge_group:
  workflow_dispatch:
  push:
    branches:
      - main

permissions: read-all

jobs:
  build_test_macos:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
        compiler_version:
          - 5.3.0
          - 5.4.0

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout tree
        uses: actions/checkout@v5
        with:
          submodules: true

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.compiler_version }}

      - run: opam option --global 'archive-mirrors+="https://opam.ocaml.org/cache"'
      - run: opam repository --all add pac https://github.com/uq-pac/opam-repository.git
      - run: opam install . --deps-only --with-test
      - run: LIBRARY_PATH="$LIBRARY_PATH:/opt/homebrew/lib" opam exec -- dune build --ignore-promoted-rules --profile=release
      - run: LIBRARY_PATH="$LIBRARY_PATH:/opt/homebrew/lib" opam exec -- dune runtest --ignore-promoted-rules --force

  build:
    name: build_test
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        include:
          - ocaml-version: "5.4"
            container: ghcr.io/agle/bincaml-ci-containers/ci-5.4:latest
          - ocaml-version: "5.3"
            container: ghcr.io/agle/bincaml-ci-containers/ci-doc-5.3:latest

    runs-on: ubuntu-latest
    container: ${{ matrix.container }}

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - run: opam repository --all add pac https://github.com/uq-pac/opam-repository.git
      - run: opam install -t . --deps-only
      - run: opam exec -- dune build --profile=release
      - run: opam exec -- dune runtest --force


  treesit:
    name: treesitter
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        include:
          - ocaml-version: "5.4"
            container: ghcr.io/agle/bincaml-ci-containers/ci-5.4:latest

    runs-on: ubuntu-latest
    container: ${{ matrix.container }}

    steps:
      - uses: actions/checkout@v6
      - run: opam repository --all add pac https://github.com/uq-pac/opam-repository.git
      - run: opam install -t . --deps-only
      - run: opam exec -- dune build '@treesit'

  lint-fmt:
    name: format
    runs-on: ubuntu-latest
    container: ghcr.io/agle/bincaml-ci-containers/ci-doc-5.3:latest
    steps:
      - uses: actions/checkout@v6
      - run: opam repository --all add pac https://github.com/uq-pac/opam-repository.git
      - run: opam exec -- dune build @fmt --display=quiet

  lint-opam:
    name: lint-opam
    runs-on: ubuntu-latest
    container: ghcr.io/agle/bincaml-ci-containers/ci-doc-5.3:latest
    steps:
      - uses: actions/checkout@v6
      - run: opam repository --all add pac https://github.com/uq-pac/opam-repository.git
      - run: opam lint

  build-nix:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - uses: cachix/install-nix-action@v31

    - run: nix build .#bincaml
      name: Test building bincaml
    - run: nix build .#bincaml_lsp
      name: Test building bincaml_lsp
    - run: nix develop .#no-fp
      name: Test Nix dev shell

  opam:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    needs: [ ]

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - uses: ocaml/setup-ocaml@v3
